modules/edu.gemini.seqexec.web/build.sbt, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/SemanticUI.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/message/CloseableMessage.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuitSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/seqexec-semantic.html, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/RestRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/play/WebServerLauncher.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/test/scala/edu/gemini/seqexec/web/common/Arbitraries.scala
This PR builds on the Web UI by loading the contents of the Seqexec Queue (Canned data ATM), Implements #8. At startup it will request the current queue using an ajax request and display the contents of the queue on the queue table. Some notes:
* Both backends can be used to serve the application
* This PR starts using [Diode](http://ochrons.github.io/diode/index.html), which is the scala.js version of the [Flux Architecture](http://facebook.github.io/flux/) for React applications
* The code contains logic to display an indicator while loading and to display proper error in case of a failure
Below there is a small video (á la @tpolecat) with the happy path and an error case. In both cases the server has an artificial 3 seconds delay, otherwise you cannot see the loading process while …
=> Seqexec Queue load

.travis.yml, build.sbt
This PR brings travis support to ocs3. It uses the GitHub repo to host the ocs bundles.
I changed the config so that you cannot merge PRs unless the build passes
=> Travis configuration

README.md, modules/edu.gemini.seqexec.web/build.sbt, project/plugins.sbt
I'm raising this PR for discussion as I don't need this right away. I want, at some moment, display the version of the software on the UI. I'd think the best way to do this is by bringing the information from sbt avoiding repetition, and that's exactly what the [sbt-buildinfo](https://github.com/sbt/sbt-buildinfo) plugin does.
This PR integrates buildinfo into the build and will generate a managed class with the content as
```scala
package edu.gemini.seqexec.web.client
import scala.Predef._
/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
/** The value is "edu_gemini_seqexec_web_client". */
val name: String = "edu_gemini_seqexec_web_client"
/** The value is "0.1-SNAPSHOT". */
val version: String = "0.1-SNAPSHOT"
override val toString: String = {
"name: %s, …
```
=> sbt-buildinfo into the build

modules/edu.gemini.seqexec.server/build.sbt, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Executor.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Controller.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2ControllerSim.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosSouth.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Instrument.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/package.scala, modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/DhsClientSimSpec.scala
This PR gives me an opportunity to dig into the seqexec server and fix a specific problem I'm having. I want to test with a mock dhs client. The current implementation only lets you use the real DHS client making it impossible harder to work without the VPN and it maybe risky to do calls to the real DHS
It is still an open question how'll configure the Seqexec, right now it is set to simulated instruments, simulated tcs and the new mock dhs client but we need to find out a way to properly configure it for different scenarios
This PR fixes #35
=> DhsClient simulator

modules/edu.gemini.seqexec.web/build.sbt, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/JwtAuthentication.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/play/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/play/UserAction.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/LDAPAuthenticationService.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/LDAPService.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/TestAuthenticationService.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/authentication.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/security/JWTTokensSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/main/scala/edu/gemini/seqexec/web/common/authentication.scala, project/Settings.scala
This PR sets the basis to support authentication on the Seqexec webapp.
It can do authentication against the LDAP/AD server, with support for a test in-memory auth database for testing. This is done with the [UboundId SDK](unboundid.com/products/ldapsdk/) library. Besides authentication we can read the display name
Once auth is established it will construct a [JSON Web Token](https://jwt.io/) and return it to the client as a cookie. See the rationale behind using a [cookie for storing](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage) the token. Tokens are built using the [JWT Scala](https://github.com/pauldijou/jwt-scala) library using HMAC with SHA-512 and a single secret key
Note that this approach is stateless, we don't need to store the cookies as they …
=> Authentication part I

modules/edu.gemini.seqexec.web/build.sbt, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/play/SeqexecUIApiRoutes.scala, project/Settings.scala
The Websocket channel was made using `scalaz-stream`. The http4s backend was able to use the stream directly, but the play backend was left pending as it is not compatible with `scalaz-stream` preferring `akka-streams` instead.
This PR uses the `streamz` library to convert from one type of stream to the other, letting the play backend use the same data source
Fixes #55
=> Play Websockets

modules/edu.gemini.seqexec.web/build.sbt, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/SeqexecApp.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/log.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/play/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/main/scala/edu/gemini/seqexec/web/common/LogMessage.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/test/scala/edu/gemini/seqexec/web/common/ArbitrariesWebCommon.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/test/scala/edu/gemini/seqexec/web/common/LogMessagePicklingSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/test/scala/edu/gemini/seqexec/web/common/LogPicklingSpec.scala, project/Settings.scala
This PR integrates onto the client the scala.js version of  java util logging. This lets us use the same api on the frontend and backend. Additionally it will post the log messages to the backend so that we can have a record of the client activity
Fixes #14
=> Client logging

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/authentication.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/events.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ExecutorImpl.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LoginBox.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/NavBar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/TopMenu.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/SemanticUI.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/common.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/button/Button.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/input/Input.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/label/Label.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/menu/Item.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/package.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/JwtAuthentication.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/TokenAuthenticator.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/play/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/play/UserAction.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/LDAPAuthenticationService.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/TestAuthenticationService.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/authentication.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/security/JWTTokensSpec.scala, project/Settings.scala
This PR updates the UI to support authentication. It adds:
* Login box to enter username/password
* Logout button
* Checks authentication at startup
* Restrict functions depending if a user is logged in
This is mostly an UI PR but it contains a few changes to the backend, in particular a fix to make http4s support optional authentication, an extractor of user credentials for play and restrictions on certain routes
some screenshots:
Login box
Restricted access for anonymous users
Run button enabled for logged in users
=> Authentication part II (UI)

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/SeqexecApp.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LoginBox.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/log.scala
This PR brings an implementation of WebSocket reconnections. The application tries to open the connection at startup and if it fails, or the connection breaks at a later point, it will try to reconnect after some delay. This is implemented as a state machine using diode to handle state transitions
The delay is growing doubling every time a reconnect is attempted, up to a max of 1 min.
Note that this PR doesn't contain UI, that will come later
Another missing bit is re-syncing the data. Once we reconnect we need to query the current state of the server to update the UI
=> Reconnecting WebSocket

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/FreeLDAPAuthenticationService.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/authentication.scala
The AD server names were changing rendering the logging functionality of ocs3 inoperable
This PR fixes the server names and adds support for failover. The server will attempt first cpo and if it fails it will attempt sbf before giving up
=> AD Server name changes

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SequenceSearch.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/TabularMenu.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/TextMenuSegment.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/WebSocketsConsole.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/main/scala/edu/gemini/seqexec/web/common/model.scala, project/Settings.scala
This PR changes the Ui to always have the running step visible as required on the seqexec specs document. Basically if you have more steps than visible on the steps table, the ui should autoscroll to make the running step always visible
Changing the scroll position on a page can only be done on plain javascript and that collides with React way of handling the DOM. This was solved by creating  a React `Ref` to the scroll pane and hook into React lifecycle events to calculate the new scroll position, store it in the component's state and then make it effective
There are still some open issues with this like
* If the user scrolls manually, should the position be reset?
* Pausing is not supported in this schema
* For fully executed sequences, should we focus on the first or the last row?
I'll …
=> Track sequence running step

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Handler.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/model.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/HandlerSpec.scala
With the *Zipper* there is now a deeper data hierarchy with a top level *Queue*, *Sequence*s, *Step*s, *Execution*s and *Action*s. Previously there were only the equivalent of *Execution*s and *Action*s. Also with this structure it comes support for marking `Execution`s as completed instead of remove them.
The executions for each test can be seen printed to the console. The tests themselves only check that the executions finish.
Don't bother too much reviewing this PR since the changes are quite messy. It can be considered as a starting point for the Zipper based execution.
=> Seqexec execution with a Zipper

.gitignore, .travis.yml, README.md, project/SeqexecEngineModules.scala, project/SeqexecWebModules.scala
This PR fixes one of the trouble running test that interact with the DOM. There has been no reliable way to run these on any of the Scala.js runtime environments, since rhino is to weak and slow to execute `jQuery` and `node` doesn't have a DOM
On this PR we use [jsdom](https://github.com/tmpvar/jsdom) that runs in `node` but provides a DOM basic environment. Note that this requires you installing node and jsdom but that is going to become the default for scala.js anyway
With this PR we can finally run the client-side tests on travis and we can build more meaningful tests in the future
=> Tests with jsdom

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Handler.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
With these changes there is now a Process of `SeqexecEvent`s that in theory could be used directly by the client to display the state of execution.
=> SEGNG-34 Attach the event with each generated Engine state output

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/execution.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/step.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/CurrentSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepZSpec.scala
These are the initial unit tests intended to catch the bug causing extra executions to be reported. These tests still don't reveal the bug I was chasing, but since it's not critical, I'm moving it back to the backlog and will revisit it later.
Obviously there is plenty of room for improvement of these tests but I'm sending this PR now because I don't want to get bogged down writing tests when there are other tasks with more priority.
=> SEQNG-46 Initial engine unit tests

modules/edu.gemini.seqexec.server/build.sbt, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Commands.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ODBProxy.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
Read engine startup settings from configuration file app.cfg. The settings are then applied to the Seqexec engine. The implementation of the settings themselves is a bit dirty (uses mutability), but I think it is OK, has they are not supposed to change in run-time.
I also moved the code that configures the Seqexec engine inside ```SeqexecEngine```
=> SEQNG-52: Implementation of engine startup options

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Handler.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/HandlerSpec.scala
This was necessary in order to reload extra sequences after a sequence was finished. We want to keep the Engine running along with the web server.
I don't know if it's worth sending a PR for this kind of *microcommits*, I could directly push it to `feature/engine` if you prefer.
=> Keep engine running after finalizing

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala
This is a small suggestion for a change. It seems strange to have inner classes defined inside another class. Normally you'd put them in the companion object.
I got a compiler warning due to the original code:
```
[warn] /Users/cquiroz/Projects/ocs3/modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala:116: The outer reference in this type test cannot be checked at run time.
[warn]   final case class Error(t: ErrorType, msg: String) {
[warn]                    ^
[warn] one warning found
```
What do you think?
=> Move DhsClientHttp inner classes to the DhsClientHttp object

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
Trying to start the web application I found a missing configuration item, and traced to the typo on the `app.conf` file
=> Fixed typo on setting name

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/SharedModel.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
This is the first PR towards SEQNG-58A. It skips the direct response when loading the sequence instead relying on the event through the websocket
It also adds a metadata element to the sequence that should contain extra data in the future
This PR is mostly to get comments about the approach taken to further integrate the new engine into the UI
=> SEGNG-58A: Replace Sequence in the client with SequenceView

.travis.yml, build.sbt, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SequenceSearch.scala, project/SeqexecEngineModules.scala, project/SeqexecWebModules.scala, project/Settings.scala, project/plugins.sbt
This PR updates the version of several of our libraries. In particular, scala.js 0.6.13 is going to be important moving forward
Another small update is a change on travis to only build the distribution packages for non-PR builds
The changes reduce time from app 13m to app 8m
=> Version bump

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
Now the engine is launchedonly once when starting the server and uses `scalaz-streams` *topic*s to broadcast the output to every client. I implemented this similar to how was in a previous version of the executor.
I tested it with Firefox and Chrome at the same time.
=> SEQNG-66 Broadcast engine output to each connected websocket

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Execution.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/NewBooPicklers.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ConfigUtil.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ConfigUtilOps.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Tcs.scala, modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/ConfigUtilSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuitQueueHandlerSpec.scala
This PR is not strictly client-side but it is required for the front end. The `Step` on the backend doesn't carry the configuration from the OT, though it reads it to build the tasks. On this PR a field is added to `Step` to take the config along
It is not that nice to carry all that data when is not really used but I don't know any other options.
Some other minor changes are included in particular to a utility class `ConfigUtilOps` to manipulate configurations.
I'm also ignoring in this PR a test that fails randomly and needs to be reworked
=> SEQNG-58C: Replace Sequence in the client with SequenceView

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
In addition to having more granular transition states, this also ensures that a
separate `Task` is launched when the state is updated solving the issue of having delays in between in some state transitions.
When manually testing, the first `Step` is still not shown as `Running` but that's a separate issue that I'll fix in another PR. For this concrete bugfix, please, check that that the `Start` event shows up right after clicking *Start*.
=> SEQNG-79 Introduce `Executing` and `Next` system events #resolve

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/FreeLDAPAuthenticationService.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/authentication.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/security/JWTTokensSpec.scala, project/Settings.scala
This PR started simply as an upgrade to the latest version of http4s but it grew as tests have been added that showed a few bugs
the latest version of http4s changes the way authentication is performed so we should attempt to do it but it showed a harder problem than planned. However the current system still works
This exercise showed some of the limitations of http4s, leading to at least one PR submitted to the project
=> SEQNG-65: Upgrade to http4s 0.15.0

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
Concretely:
- Wire up UI button with stop route.
- Remove `Pause` button.
- Fix regression where the sequence didn't fully stop after more events were
introduced.
- Initial attempt of labeling the Step status when in Paused state.
The way the current Step status is displayed in the UI now when paused is strange. This is because there are different cases involving the underlying `Execution`s which are not shown to the client. In the next meeting I can explain with a demo what is going on under the hood and why displaying the Paused status of a Step is trickier than it initially seems.
=> SEQNG-85 Enable Stop from Web UI

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
I thought this would be harder but it was actually a trivial fix.
Notice that if you pause during an observation it will mark that `Step` as `Done` and there won't be any other `Paused` Step in the `Sequence`. As we discussed, it's still open for discussion how we are going to represent that case, so you may consider the current behavior provisional.
=> SEQNG-88 Fix showing first Step as Done

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/SemanticUI.scala
This is an prototype UI to include buttons for exposure control at the row level and a progress bar for the observation process. There is no functionality attached just the following changes:
* Made the running step taller
* Add buttons for pause/stop/abort at the row level
* Added a progress bar that should display how long to complete the observation
The code doesn't tell much so here is a screenshot
=> SEQNG-93: UI elements for exposure control

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/button/Button.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/package.scala
This is a small change to the observation control buttons adding tooltips and making them instrument and state dependent
=> SEQNG-97: Add and update observe control buttons based on existing seqexec

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
Updated according to the latest comments from @andrewwstephens 
Added abort button for Nod&Shuffle mode:
Added stop/abort buttons in pause mode
=> SEQNG-97: Add and update observe control buttons based on existing seqexec 

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
This PR is another mockup of the UI updating the sequence control buttons. After some discussions this has been distilled to 2 buttons: `Run sequence from step N` and `Pause`
At the beginning we should start from step 1
However the user can select starting from a later step clicking the correct row:
Once we run only Pause is visible
And if we pause we return to the `Run from step N` where N is the next step to be executed and it can be again overriden manually:
=> SEQNG-99: Add missing buttons for sequence control

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
The problem was that the sequence was being stopped but when that happened, the event sent to the clients was a NewLogMessage, without the new state of the sequence. I created a new type of event, a generic update, to send the new state to the clients.
=> Fixed bug that made the sequence appear as running in the clients after it was paused.

app/seqexec-server-test-l64/src/main/resources/app.conf
This is a small change to make the test seqexec connect to the production odb
Note that this won't write to the ODB, only read programs to make it easier for our users
Do you think they should use the test ODB/OT?
=> Preparation for release

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala
This started as a bug with the `fileId` but it turns out all the *done* steps were in reverse order. After figuring out the root cause of the bug, the fix was trivial.
=> SEQNG-128 Fix order of done steps

modules/edu.gemini.seqexec.server/src/main/resources/DhsHdr.xml, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2ControllerSim.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosSouth.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Header.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Instrument.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/package.scala
I had to scale down the scope of the task. Now it only include the infrastructure that will allow me to add the keywords.
I separated the writing of the keywords to the DHS from the reading of the values. That way I can test without accessing the EPICS systems.
=> SEQNG-123: Base implementation of FITS keywords.

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
Still missing the observer/operator names, and the current observing conditions. Those features will require a bit more work, so I'll put them in separate tasks. The main complication is that most of the OCS keywords are set when the sequence is loaded, but the observer/operator names and the current observing conditions are set when the sequence is run. I would need a mechanism to inject those values in the already constructed Actions. Maybe just rebuild the whole sequence?
=> SEQNG-132 Real values for OCS keywords.

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala
Implemented the capture of exception. This was bothering me today, because the test DHS was down, and that caused that the server crashed unceremoniously. 
For some reason the connection timeout exception didn't produce an error message.
=> SEQNG-09: Capture exceptions when executing actions.

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Epics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Header.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
This commit includes all the Flamingos-2 keywords set by Seqexec. There are two keywords in the old Seqexec that are filled with values read from the instrument. I implemented them, only to find that they are not actually sent to the DHS. I left the code in (except for the part that writes the keywords).
=> SEQNG-134 Implemented Flamingos-2 keywords.

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Execution.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
The main idea to provide partial results for an Action is to divide the Action in several sub-actions. Each actions ends and gives as a result a value and the next action, except for the last one that only gives the final result. The execution engine treats all of them as the same Action when it comes to the action status, and stores the last partial result in the state.
The partial results don't have an effect in the client, yet.
=> SEQNG-114 Implemented partial results from Actions.

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
This is the server part for SEQNG-139. From the client it should be possible to be possible to call the functions wrapping the AJAX requests.
The primary place to store the names is in the Sequence metadata of the engine.
I wasn't sure about the format for the URL routes for the setters, so if you prefer a different scheme I can change it.
=> Setters for Operator and Observer names in the server side

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
For now the default values for the keywords are always sent even if they are changed in the UI.
We need some way to access the application state at the time we are sending the keywords.
=> SEQNG-148 SEQNG-149 Add default keyword values for Operator, Observer and Raw observing conditions

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/input/Input.scala
This is the first PR for SEQNG-139. It enables the Observer text fiel on the UI at the sequence level. It took quite a bit of effort to get it to play correctly given the way React works, there maybe still some use cases not covered
The field will take the name of the logged in user and will update the backend when loosing the focus.
Still missing:
[ ] Update the backend before run
[ ] Update the backend while running
[ ] More testing
[ ] Complete the Operator field
Here's a screenshot in FF
=> SEQNG-139A: Add Operator and Astronomer name to the client

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Resource.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
Sequences can be now run in parallel when there are no `Resource`s shared among other *running* Sequences. Otherwise the Sequence can't be run.
The primary store for resources is the `Step`, from there the resources needed by a `Sequence` are calculated.
This is an initial implementation, there are still several things to polish. Off the top of my head:
- Find out at load time resources are needed for each Step. The test use synthetic Sequences with resources hardcoded, but in the real application there is no way to create them.
- Complete types of resources.
- Check resources in Pending steps only. Now it takes into account the completed ones too. - Provide some kind of feedback when a attempting to run a Sequence fails because of shared resources.
- Add flag to indicate which Sequences …
=> SEQNG-158 Initial support for resource management

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceDefaultToolbar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/input/Input.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/input/InputEV.scala
This is one of the trickiust UI related PRs so far. It enables the observer and operator field to autodetect when they change and submit to the backend. It is not ideal to do this on every char typed, lest it produce too much traffic, so the interim solution was to submit when the input field looses focus. However this fails if the user stay on the text field
The solution un this PR sets up a timer to detect changes every 2 seconds and submits
Several border cases made this a bit harder but it seems to work satisfactorily and has been tested with multiple clients to do the right thing
As usual for UI PRs the code doesn't tell that much
=> SEQNG-162: Improve text fields change detection

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/JwtAuthentication.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/TokenAuthenticator.scala
This is a small change that improves security closing the option to do unauthorized seqexec commands using e.g. curl
Given that this is useful for development it remains possible  in dev mode
=> SEQNG-59: Protected routes for Seqexec Engine commands

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GwsEpics.scala
While compiling I noted a warning in `GwsEpics`:
```
[warn] /Users/cquiroz/Projects/ocs3/modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GwsEpics.scala:26: Suspicious application of an implicit view (scala.this.Predef.Integer2int) in the argument to Option.apply.
[warn]   def health: Option[Int] = Option(state.getIntegerAttribute("health").value)
```
This PR fixes that hidden implicit conversion
=> Fixes warning

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/authentication.scala, project/Common.scala, project/Settings.scala
At the beginning of the project we had the client talk json via upickle to the backend but then we switched to binary. However we still had a little use for upickle when doing the construction of the JSON Web tokens.
This PR remove that dependencies and uses argonaut instead which is already a dependency
=> Remove upickle dependency

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/JwtAuthentication.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/TokenAuthenticator.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/authentication.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/security/JWTTokensSpec.scala
The auth tokens on the seqexec are set to expire n hours after login. This has the effect that on a long night you could still be working and be logged out
This PR sets a shorten time to live but it renews it every time there is activity which is more logical in my opinion
=> SEQNG-117: Seqexec auth expiring

build.sbt, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Engine.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/encoder/BooEncoders.scala
This is still not ready to merge because I have to implement the conditions in the server but I wanted to get early feedback at engine level in case I'm doing something wrong.
Notice that now `Conditions` is imported from the ODB modell, so the `SeqexecODB` dependency was added to the `engine`.
`Conditions.WORST`, which under the hood sets all conditions to `ANY`, is the default value but you might want some other default.
=> SEQNG-173 Make `Conditions` a global value in Engine

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Engine.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/WebSocketsEventsHandlerSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
Now the client can access the conditions by looking them up in `SequencesQueue`.
The tests are now slower, now they take ~22 min instead of 8 min, because after introducing the conditions there are more combinations of Arbitrary `SequenceQueue`s to test the serialization, so any ideas about how to reduce the number of tests while actually including the Conditions in the serializations tests are welcome. I wrote in the commit message of the tests what I already tried.
Another thing to watch out is that now the HTTP response to a Sequence load request is just its id instead of a `SequencesQueue`. Everything seems to be working fine but I'm 100% sure there are no issues related to this change. Including the previously set conditions in the response would have been tricky.
I have the uneasy …
=> SEQNG-177 Make Conditions globally readable by the client

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Resource.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
The original goal was to not configure TCS for calibration steps. In the road towards that goal I implemented the identification of step types, which I think is the big contribution of this PR.
I am not totally sure about one aspect of the implementation thought. The type of step determines the resources used, the systems that must be configured, and the headers. I created classes for the types, and separate functions to calculate the resources, systems and headers. There is some repeated code between those functions, so maybe they could be consolidated. The other aspect that may be changed is that I think there should be a relationship between resources and systems.
=> SEQNG-172 Made systems configured in step depend on step type.

modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
This avoids a brief error message that was showing in the UI while loading. The
default conditions returned don't seem to used anywhere.
In the end there was an issue with that response. I think it's alright to send the default conditions because I don't think it's used anywhere, but I might be wrong.
=> Respond with a dummy SequencesQueue when loading a Sequence

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Engine.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceDefaultToolbar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/WebSocketsEventsHandlerSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
This PR re enables the operator field on the side bar. It required an update to the backend to move the operator to a higher level along the conditions.
The operator field is getting the same treatment as the observer field and updates will be detected on the background
=> SEQNG-186: Synchronize operator field across clients

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
Now instead of doing nothing, it explicitly sends an event indicating that the Sequence couldn't be run because some resources are busy.
The *Run* button in the UI still appears greyed out after this event but I don't think it's worth fixing because I think we shouldn't even show the *Run* button when there are busy resources (to be done in another PR).
This event will be used only when trying to run the sequence through the HTTP API.
=> Send distinct engine event when trying to run a Sequence where some resource are busy

.gitignore, app/seqexec-server-gn-test/src/main/resources/app.conf, app/seqexec-server-gs-test/src/main/resources/app.conf, app/seqexec-server-gs/src/main/resources/app.conf, build.sbt, project/AppsCommon.scala, version.sbt
This PR simplifies the settings used for the production and test seqexec servers. All settings are now in github and the private ones are stored locally on each host. In particular the certificates keystore are on the hosts. They are version controlled but stored in a separate repository
Version number is increased for the next release
=> SEQNG-198: Store settings for production servers locally

app/seqexec-server-gs/src/main/resources/app.conf, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsEpics.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
This has been bothering me for a while. EPICS gets initialized from the system environment variable, but when it is not present we get an NPE
This PR adds a configuration variable to set it explicitly. If not present the system will revert to the environment variable
=> SEQNG-83: Epics configuration for systems

.gitignore, build.sbt, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/odbclient/ODBClient.scala, project/Settings.scala
This PR includes a very small client to read an observation name from the ODB using the odbbrowser API
We may need to move this to another package on the next subtask
=> SEQNG-227: Read the title from the ODB

modules/edu.gemini.p1backend/edu.gemini.p1backend.server/src/main/scala/edu/gemini/p1backend/server/http4s/WebServerLauncher.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala, project/Settings.scala, project/plugins.sbt
Across the board library updates. Explicitly scalajs-react is not included as we need to do larger job at porting the UI
=> Library updates

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LoginBox.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceDefaultToolbar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/label/Label.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/table/TableHeader.scala
This PR updates the UI to show the observation name on the screen. Note that this is hidden for anonymous users. This is disabled only on the UI, In a future PR the feed will anonymize such data to avoid potential disclosures
=> SEQNG-229: Display the title on the client

build.sbt, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SeqexecEventPrismSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, project/Settings.scala
We are hiding some data, specifically the observation name, for anonymous users. However this is enforced at the UI level but the data is present on the WebSocket stream. This PR adds a filter so that anonymous and logged in users can get different data
Note that I started using [Monocle](http://julien-truffaut.github.io/Monocle/) for lenses. @tpolecat and @swalker2m, please let me know if that's ok
=> SEQNG-243: Anonymize sensitive data on client feed

app/seqexec-server-gn-test/src/main/resources/app.conf, app/seqexec-server-gs-test/src/main/resources/app.conf, app/seqexec-server-gs/src/main/resources/app.conf, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala, modules/edu.gemini.web.server.common/src/main/scala/edu/gemini/web/server/common/RedirectRoutes.scala
This is a simple but useful improvement. If you hit the seqexec by mistake using http, it will redirect you to the https secure site
The code is ready but it needs a small change to the firewall rules on each machine that will be requested to ITS
=> SEQNG-247: Redirect http calls to https

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
Used the feature implemented in SEQNG-241 to remove the use of Queue.enqueueOne and the calls to unsafePerformAsync.
I  paid more attention to the managing of errors when loading sequences, and I think I may have fixed SEQNG-237.
=> SEQNG-249 Rewrote automatic load to remove calls to unsafePerformAsync

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ODBProxy.scala
While testing I found a bug when reading the name of several observations in parallel. This was traced back to the http4s module providing xml decoding. Until that's fixed this PR brings a workaround
=> Fixes bug when parsing in parallel

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SeqexecEventPrismSpec.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
At the moment every time the ODB is polled a log message is created and sent to the client wasting bandwidth. This PR adds a new type of `NullEvent` that is not sent to the client
=> SEQNG-205: Add NullEvent for events that should not be sent to the client

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/misc/wsstress.yml
I did some stress test for websockets on the application using artillery. This is the file used to do the testing
Some more information was written on the wiki at https://github.com/gemini-hlsw/ocs3/wiki/Stress-testing
=> SEQNG-253: Test file to stress websockets

.travis.yml, build.sbt, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SeqexecEventPrismSpec.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SharedModelArbitraries.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalControllerEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client.cli/src/main/scala/edu/gemini/seqexec/web/client/cli/SeqexecTerminal.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/FreeLDAPAuthenticationService.scala, project/Common.scala, project/Settings.scala
This PR uses the typelevel compiler on ocs3. I found troubles compiling the JS side, while it compiles files it produces invalid js that fails on tests and on creating an executable js for the browser
Hence, I'm only use typelevel for the JVM side until this can be fixed. I'm planning to create a minimal demo to submit for a fix
Using the typelevel compiler requires some code changes especially on terms of more strict match exhaustiveness
=> SEQNG-270: Typelevel compiler

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SequenceDisplayHandlerSpec.scala
This PR indicates on the queue table what's the selected tab on the sequence area. It also has some UI improvements for queue tables with man entries
This change is motivated by difficulties on seeing the current state when there are many sequences on the queue.
Here's a screenshot with one sequence running and another being displayed
=> SEQNG-281: Display on the queue the selected tab

app/seqexec-server-gn-test/src/main/resources/app.conf, app/seqexec-server-gs-test/src/main/resources/app.conf
The test odb server changed name for the last release. This PR updates those names for the seqexec
=> Updated name of the odb servers to match current state

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/EpicsUtil.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ODBProxy.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/package.scala
Runtime errors are not captured anymore, letting the application crash.
=> SEQNG-284: Let it crash

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
We had the buttons earlier to check the UI but this would be confusing for the users. Let's hide them
=> SEQNG-292: Hide the observation control buttons for F2

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/ArbitrariesWebClient.scala
We have been searching for this error for a while where in some cases the metadata of a sequence is lost. To fix it I converted the `Instrument` type into an `ADT` thus making it impossible to construct a sequence with invalid metadata. This revealed the issue deep in the engine
=> SEQNG-290: Errors loading partially executed sequence

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Execution.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceToolbars.scala
After #283 we can now load empty sequences, however running them produces an exception and it puts the engine on an infinite loop
This PR fixes both problems and also removes the buttons on the UI to run empty sequences
=> SEQNG-302: Exception when loading a sequence without steps

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/ExecutionSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
This change allows to have the Actions change to take into account the current values of parameters like the observer name or the observing conditions.
=> Actions are now realized just before executing.

app/seqexec-server-gs/src/main/resources/app.conf, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
Change the default smartGCal host to be the test odb. Only the production seqexec is configured for the production smartGCal instance
=> SEQNG-296: Fix smart gcal exposure times

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceToolbars.scala
This is a small change to let users set the operator as the empty string unlike the current situation where the empty string is set as `None`
=> SEQNG-308: Failure to set observer and operator to the empty string

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceToolbars.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
This is a small change that will make the sequence buttons to re-render every time there is a change on the top model. While this maybe slower in practice there is no appreciable difference and it makes it update e.g. in the case there is a sync and there are no changes on the remote side
=> SEQNG-310: Sync action not refreshing

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
This fixes a small bug where the operator is set for the first set of sequences but not for newly queued sequences
=> SEQNG-311: Set the observer for newly scheduled observations

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosHeader.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
There is one change affects all instruments. The "after" keywords are now send in the reverse order, which means the late instrument keywords sent by Seqexec will go before the TCS keywords. That is the same ordering for keywords sent by the instrument itself.
=> SEQNG-309 Fixed ordering of some GMOS keywords.

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceToolbars.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/label/Label.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SequenceDisplayHandlerSpec.scala
This PR changes the logic on the UI to keep completed sequences on the sequences table when completed though they get removed from the queue table as seen below
This was tricky because the state is removed from the server so we have to keep an extra copy on the client. This also mean that the completed sequence will disappear on a page refresh but that's likely ok
I added a small improvement to the tabs displaying the current running step
=> SEQNG-288: Completed observations should remain

build.sbt, project/plugins.sbt, version.sbt
With this PR I propose that we use [sbt-git](https://github.com/sbt/sbt-git) to generate the version number. This is based on tags and what is provided by [git-describe](https://git-scm.com/docs/git-describe)
The benefit is that our public version will always match what software version on github as we often forget to update the version number or even release uncommited changes. The UI gets the actual version number too
=> SEQNG-319: Use sbt-git to generate the application version

build.sbt, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SeqexecEventPrismSpec.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SharedModelArbitraries.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/logback.xml, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/logging/AppenderForClients.scala
A custom logback appender is created to send some of the log messages of the server to the client. This requires a bit of hackery as this is a java API that doesn't fit too well with the rest of the scala structure
The messages sent to the client have a certain structure (level, timestamp, msg) to eventually let clients to filter and sort messages on the UI
=> SEQNG-322: Add an appender to forward messages to the client

build.sbt
Add jvm configuration properties to support remote monitoring via JMX and remote debugging. This has been already tested on seqexec-gs-test
=> SEQNG-318: Enable debugging on the seqexec JVM

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Resource.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Gmos.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/InstrumentSystem.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsController.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerEpics.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
I noted that we have 3 trait/classes called `Instrument` in ocs3. This is an attempt to have only one. I've merged two definitions on the engine and model and renamed one to `InstrumentSystem`
I tried to convert `InstrumentSystem` to a typeclass to augment the `Instrument` enum instance but I failed 😢 , but this is an improvement nonetheless
=> SEQNG-335: Unify the models for Instrument

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ODBProxy.scala, project/Settings.scala
This PR brings the new ocs library versions done by @swalker2m to fix this on the seqexec client library
=> SEQNG-359: ODB doesn't send engineering parameters for FLAMINGOS-2 observations

build.sbt, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Commands.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ODBProxy.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, project/Settings.scala
Thanks to #322 we are extracting more information about a sequence from the ODB. In this PR we use this to obtain the title of the sequence (thus avoiding an extra call to the odb browser) and we also read the file names of previously executed steps
Thus we can display de file id of previous executions when loading a sequence like
=> SEQNG-312: Display file id of already executed steps

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Execution.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala
This PR is to request comments as this is not properly working right now
The idea on this PR is to change the engine to read the file id at the beginning of the observation, and then send an extra event to the client at the start of the observation
=> SEQNG-122: Get fileId in the engine state as soon as the observation starts

build.sbt
This file preserves the logging configuration file on all the seqexec distributions eventually allowing it to be changed at runtime
This also fixes an issue on the `acm` bundle that didn't let distributions to be built
=> SEQNG-372: logback configuration should be in a file

build.sbt, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LoginBox.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/NavBar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/ResourcesBox.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/dropdown/DropdownMenu.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/message/CloseableMessage.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/index-dev.html, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/package.scala, modules/edu.gemini.web.client.facades/src/main/scala/edu/gemini/web/client/facades/semanticui/SemanticUI.scala, modules/edu.gemini.web.client.facades/src/main/scala/edu/gemini/web/client/facades/semanticui/SemanticUIModal.scala, project/Settings.scala, project/plugins.sbt
We have been loading javascript dependencies using `webjars` instead of directly from `npm`. This method is being deprecated in favor of using `scalajs-bundler` to load `npm` modules.
This has several benefits:
* Direct access to the latest versions
* Better downstream management of dependencies
* We can get a reduced version of semantic-ui modules
And the most important of all, this lets us use `react` components directly. They are only supported via `npm` modules
This PR has been very long as the intersection of `sbt` and `npm` is complicated. There are some possible improvements but they will be done later on when possible
The interaction with `semantic/jquery` took quite a bit of effort and this leads me to attempt to use `semantic/react` instead in the future
as a result of this PR …
=> SEQNG-246: Use scalajs-bundler

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gcal/GcalControllerSim.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerSim.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/package.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/tcs/Tcs.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/logging/AppenderForClients.scala
This is a partial update to reduce logging that reaches the user. It mostly consist in converting `info` to `debug` and a special case for the `security` logger
There is likely some more work to do in this context but this is a first step
=> SEQNG-395A: Reduce user facing logging

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ActionType.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqexecEngineSpec.scala
This PR calculates the current observation status on each step out of the executions and adds it to the state sent to the clients
=> SEQNG-397: Send observation state to the clients

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/test/scala/edu/gemini/seqexec/web/common/ArbitrariesWebCommon.scala
Sometimes we have an error on a test happening because the bounds used to generate test cases is bogus
=> Fix for a test that fails if the generator bounds are wrong

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqexecEngineSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
This PR updates the UI to display the abort/stop button only when observing. It will also indicate when we are configuring and observing
The video below shows how it works now:
https://www.dropbox.com/s/ll3ay292vazy7n0/screencast%202017-10-30%2014-31-44.mp4?dl=0
=> SEQNG-116: Don't display observe controls until exposing

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/ControlMenu.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/Footer.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LogArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceAnonymousToolbar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceInfo.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceObserverField.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/label/Label.scala
After some discussion we are considering to update the layout of the application. We want to better use the space removing the width restrictions and vertical layers
This PR is not final, it needs a lot of polishing but I wanted to show it to get comments.
The main changes are:
* Use of the full width of the browser
* Removal of titles to gain vertical space
* Reduce nesting of sections
* Move headers section next to the queue area
* Remove top bar and replace it with a status bar at the bottom
Here's a screenshot. Let me know what you think before I can continue
https://monosnap.com/file/JsNR3B1XcpG1T77fzjdKVc0Qg1FSkg
=> SEQNG-398: Update layout

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ODBProxy.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecFailure.scala
It is possible to put sequences without steps though they are meaningless to the seqexec. This PR filters those out. This is part of SEQNG-404 but there are several bits pending
=> SEQNG-404A: Don't display sequences in the queue without steps

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/ModelLensesSpec.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SharedModelArbitraries.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/lenses.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
This is a first step to add step details. This one includes the object type as a label on the right hand side of the table. I'm sending this to gather opinions, i'm not totally sold on this design. For example what colors would be appropriate? Could we just use a single letter for the object type or an icon?
=> SEQNG-367A: Show a summary of the configuration for each step

build.sbt, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/ModelLensesSpec.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SharedModelArbitraries.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepSettings.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala, modules/edu.gemini.web.client.facades/src/main/scala/edu/gemini/web/client/facades/semanticui/utils.scala
As part of SEQNG-367 this PR includes a display for the offsets. it displays it numerically and with a graphical widget showing in which quadrant the offset is placed. This PR required getting deeper into JS functions to get the numbers to align properly and to use the canvas. This will be useful in the future
Should we display this for 0 offsets?
=> SEQNG-367B: Offset display

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerEpics.scala
Old Seqexec wrote the value to an EPICS menu record (therefore, the user friendly value), which was then converted to values WLEN or SEL for the CAD record. In the new Seqexec I bypassed the menu record.
=> SEQNG-401 Fixed value for disperser mode parameter.

build.sbt, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LogArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/css/virtualized.css, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/package.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/main/scala/edu/gemini/seqexec/web/common/FixedLengthBuffer.scala, project/Common.scala, project/Settings.scala, project/plugins.sbt
In this PR we replace the log text area by a table. It uses react-virtualized that allows an efficient rendering of large tables with the style matching the SemanticUI tables
=> SEQNG-347: Use a structured table to display results

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepSettings.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
It seems that we have many settings, probably too many to display in a single column. This PR adds some refactoring and puts the offset and type onto their own columns. More columns will be added as part of SEQNG-367
=> SEQNG-422: Split settings into columns

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/OffsetFns.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepSettings.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
This PR changes the UI hiding the offset columns if all the steps have zero offsets, e.g. when taking darks
With column offsets:
Without:
=> SEQNG-426: Don't show offset column for nil offsets

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelLenses.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/ModelLensesSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepSettings.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
This PR adds a column with coadds and exposure time. The formatting depends on the instrument with Gmos using no decimals, F2, GNIRS and NIFS with 1 decimal and the rest with 2 decimals
coadds is shown only for instrument supporting it
Some screenshots:
F2
GMOS:
and finally an example with coadds. This is to demonstrate the code only, GMOS won't show the coadds in general
Fake GMOS with coadds:
=> SEQNG-425: Show coadds x exptime

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceAnonymousToolbar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceInfo.scala
We are reading the target name from the target value of the first science step of a sequence. This makes daycalibrations to look like they don't have a target. Which normally doesn't matter but it looks a bit strange.
This PR changes that to use the word `DAYCAL` for those cases
Here's a screenshot:
=> SEQNG-439: Give a placeholder target name for calibrations

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
It has been requested that completed steps be displayed as grayed out or disabled
A screenshot:
=> SEQNG-440: Show completed steps as disabled

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelLenses.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/enumerations.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/ModelLensesSpec.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SharedModelArbitraries.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepSettings.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala, project/Settings.scala
This PR adds a display for the FPU. This is instrument dependent so unfortunately we had to copy the FPU enumerations from ocs. Hopefully this won't be needed when we use the gem model
It was tested with F2, GmosS and GmosN
Note that the steps table is getting very crowded. I added a task to review this as a whole once all the subcomponents are completed
Some screenshots
F2:
GmosS with built in masks
GmosN with custom masks
=> SEQNG-424: Show FPU

modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CarState.java, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Engine.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Execution.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/SystemEvent.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/UserEvent.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/ExecutionSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/EpicsUtil.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/tcs/TcsEpics.scala, modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqTranslateSpec.scala, modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqexecEngineSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
This PR modifies the definition of Action, adding a state. Execution is no longer a collection of Actions and Results, but a collection of Actions in (possibly) different states.
Actions can now end in a Paused state. In that case the Sequence is considered as still running. A new event was introduced, ActionResume, which provide a Task that is run as the continuation of the paused Action.
This will be used to implement the observe pause/resume. As I envision it, the pause will directly send a pause command to the instrument, causing the currently running observe Action to end with a Pause result. The resume will put an ActionResume. Its Task will send the resume to the instrument, and wait for the completion of the observation.
=> Action pause and resume

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
Tiny fix. `colSpan` should match the amount of columns and that's been increasing lately
=> SEQNG-448: Breakpoint bar should extends to all the width of the table

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelLenses.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/enumerations.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/ModelLensesSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepSettings.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
This PR adds support to display the filter for GmosS, GmosN and F2. As for FPU unfortunately we need to copy the filter names from ocs.
Some other ui tweaks are added to match the font size of filter and fpu
=> SEQNG-443: Show filter

modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaService.java, modules/edu.gemini.seqexec.server/src/main/resources/Gmos.xml, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2Epics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosEpics.scala
Before, the monitoring would check the gm:apply and gm:dc:observeC fields to check when the command started and was completed (or paused, or failed). It also checked the consistency of the CLID fields, and would treat a change on the CLID as an error. In other words, it treated the observe as an atomic command; a new command issued while the observe was in progress was treated as an error. This caused problems for issuing commands abort, stop or pause.
The solution implemented is to treat the observe command as a command with a delayed status. The command execution is monitored normally with the records gm:apply and gm:applyC, and then the value of gm:dc:observeC is monitored to find when the observation finishes.
=> SEQNG-450 Changed monitoring procedure for observe.

modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Execution.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/SystemEvent.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/UserEvent.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/EpicsUtil.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/InstrumentSystem.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/Gmos.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosController.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerSim.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosEpics.scala, modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqTranslateSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
Send "continue" command to GMOS when the user presses the resume button. It checks that the sequence is running and the observe Action is active.
The resumed observation monitoring is the same that for non resumed observations, including the detection of  stop or abort commands.
The "pause" and "continue" command were tested with the real instrument.
=> SEQNG-353 Implemented observe resume command for GMOS.

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2ControllerSim.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
The breakpoint mark shouldn't be present on errors or the first step
Also this adds more configurability to the erroring flamingos2 controller simulator
=> SEQNG-454: Disable the breakpoint mark on the first step and on error

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
Small fix to display the correct step to be executed after an error. It also enables the sync button when in error state
=> SEQNG-430: Do not change Run button label on error

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/logback.xml, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/main/scala/edu/gemini/seqexec/web/common/commands.scala
I've been struggling with slow compilation times and very large generated js size. In particular the size of the unoptimized generated js means we spend a long time compiling  and creates issues to run it quickly on firefox. 
After some research I found one issue with how the macros and implicits for boopickle can lead to an explosion of generated code. Turns out that explicitly defining a couple of missing implicits and changing the order are helpful.
Thanks to this we went from:
| subject  |Before |After|
| ------------- | ------------- |---------|
| Generated classes  | 12K  | 200 |
| Unoptimized JS  | 39M  | 12M |
| Optimized JS | 5.9M | 3.2M |
This PR would alleviate a bit my problems but there are still optimizations to do on this area
A moral of the story is that simple details …
=> Generated size reduction

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala
The status bar can block part of the UI if the height of the screen is too low. This fixes that adding a border to the log area
Also in this PR there are some improvements on small sizes though there is still work to do on that area. It was tested on an iPad and iPhone 6s
=> SEQNG-432: Status bar blocks last line of log

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/EpicsUtil.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/InstrumentSystem.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/Gmos.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosController.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerSim.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosEpics.scala, modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqTranslateSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
The Stop and Abort normally work by having the Observe Action running and monitoring certain EPICS channels, while the Stop (or Abort) command is sent in a concurrent thread. The Observe Action detects that an EPICS command was executed, and when the observation ends, it finishes with a proper result.
This changes when the Observe is paused. In that case, the Observe Action stops running, and finishes with a Paused result. The Stop and Abort resume the action providing a continuation Task. The Task sends the EPICS command and monitors some EPICS channels to detect when the observation ends.
The functionality was tested with the real instrument.
=> SEQNG-445 SEQNG-446 Implemented stop and abort while paused for GMOS.

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LogArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
There is a request to make the page fit on the console ops without a scroll bar. this PR does it by manipulating the css through some magic and reducing the height of the log area. This is how it looks on the consoles:
And on the emulator with some notes:
This change has a drawback on larger screen as it wastes space. So the central part with the steps will grow and shrink (to some extent) on window changes. This can be appreciated on the following video
https://monosnap.com/file/0UVbfezmevwrpOOsdj9b6FzRPjyZiZ
=> SEQNG-437: Shorten web page

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
Stopping an exposure doesn't produce an error anymore. Step is declared completed, but sequence execution is still halted.
=> SEQNG-463 Finish stopped exposure normally.

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala
This is a small fix for a case where both `Cancel Pause` and `Pause` could be displayed at the same time
=> SEQNG-466: Hide Pause Sequence button when paused

build.sbt
While source maps are theoretically useful in practice I never use them and introduce a non trivial delay on compilation. it reduced the client cold build from 100s  to 70s
This PR will disable source maps in all cases
=> SEQNG-392: Disable the creation of source maps

build.sbt
These flags may let us narrow down the excessive GC usage on the seqexec in production
=> Added flags to diagnose possible memory leak

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosHeader.scala
The value for MASKNAME is the current mask, or None, depending on the location of the FPU.
=> SEQNG-476 Force MASKNAME to None if FPU is OUT-OF-BEAM.

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
This handles a couple of border cases when syncing the page url at startup if there are sequences already loaded
=> SEQNG-438: Instrument routes should auto select sequences

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala
This PR will display the queue sorted by the sequence id. Before it was backed by a map keys, thus sorting was undefined
The changes as purely front end as there isn't much benefit on having the list sorted on the backend
=> SEQNG-483: Sort session queue

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerEpics.scala
This is to fix an issue with Seqexec always configuring the grating when position was mirror, because the requested position was all lower case, while the status value was all upper case.
=> SEQNG-486 Case insensitive comparison of current and required disperser

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/UserEvent.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqTranslateSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
The skip function is now functional. The current implementation makes the skip override the breakpoints, so it is desirable to have the UI indicate this. There is also an issue with the current step indicator in the UI if that step is marked to be skipped.
=> SEQNG-474 Implemented skip function.

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
Small UI updates to better display skipped states. it properly calculates which is the next step to run on the presence of skips
=> SEQNG-503: Update current step mark when leading steps are marked to be skipped

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/UserEvent.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SharedModelArbitraries.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
Also, errors while loading sequences are now logged as warnings, and errors in the observe commands are logged as errors.
=> SEQNG-451 Log error messages from failed actions.

modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaApplySenderImpl.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaCarRecord.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaCommandSenderTest.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaService.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CarStateGEM5.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CarStateGeneric.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/XMLBuilder.java, modules/edu.gemini.epics.acm/src/main/resources/CaSchema.xsd, modules/edu.gemini.epics.acm/src/test/java/edu/gemini/epics/acm/test/CaCommandSenderTest.java, modules/edu.gemini.seqexec.server/src/main/resources/Gnirs.xml, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsEpics.scala
GEM5 systems use a definition for the CAR values that is different from later systems. I had to implement a workaround.
I put a new flag in the definition of a Apply record in the Schema file. it is used by XMLBuilder to automatically use the right definition for CAR records.
=> SEQNG-518 Implemented workaround for non-compliant CAR in GEM5 systems.

build.sbt, project/Settings.scala, project/plugins.sbt
This is an experimental option to reduce the code size on the client by only including the data for our relevant timezones. Note this is using a SNAPSHOT of `scala-java-time` I expect it to go final after some more testing
=> Use a custom tzdb

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/InstrumentSystem.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/Gmos.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/Gnirs.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsController.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerEpics.scala
The translation of the GNIRS configuration to the actual EPICS parameters is a bit complicated. I tried to define an internal configuration model that minimized the number of parameters, while keeping its expressiveness to the same level as the current Seqexec.
Conversions are spread between the classes `Gnirs` and `GnirsControllerEpics`. The criteria I used is that if I could reduce the number of parameters in the model, I did the conversion in `Gnirs`. But if the input parameter was already part of the model, then I put the translation inside `GnirsControllerEpics`.
=> Implemented GNIRS Instrument class

modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaApplySenderImpl.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaCommandSender.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaCommandSenderImpl.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaParameterImpl.java, modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaStatusAcceptorImpl.java, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/operations.scala, modules/edu.gemini.seqexec.server/src/main/resources/Gnirs.xml, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/Gnirs.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/tcs/TcsControllerEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/tcs/TcsEpics.scala
This PR includes several fixes for GNIRS:
* Changed the channels for parameters *exposure time* and *coadds* to be the same used by the ISD. (Why the ISD shows the input parameters and not the applied values is beyond me).
* Fixed `NullPointerException` in `CaApplySenderImp`
* Implemented an ugly workaround to an issue with the AG in-position (should work on a better solution).
* Incremented timeouts for waiting for telescope an AG in-position.
* Read *coadds* from the right property.
* Implemented support for `Enum` parameters in Command Sender. I thought I needed it for GNIRS, but at the end it was not necessary.
=> Several fixes for GNIRS

modules/edu.gemini.seqexec.server/src/main/resources/Gnirs.xml, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/EpicsUtil.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsEpics.scala
GNIRS focus has to be reset every time some of the componentes move. The implementation delays the application of the parameters, allowing to check if there is any at all. The same implementation allows now avoid applying an empty configuration. I thing the same technique should be applied to the other systems, once refined.
=> SEQNG-521 Special behavior for GNIRS focus configuration.

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerEpics.scala
The problem was hidden in GMOS, but crashed the Seqexec in the South because of GNIRS.
=> SEQNG-530 Prevent accessing EPICS objects before initialization.

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/css/virtualized.css
This PR updates the table to highlight the row when the mouse hovers over it. It's easier to see on the video
it also fixes a bug on calculating the row heights
=> SEQNG-500: Restore highlight on hover

build.sbt, project/Settings.scala
Use the official release of scala-java-time. This release is a lot smaller and thus reduces the time to build the fast optimized client
=> Updated to use scala-java-time 2.0.0-M13

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepProgressControl.scala
This feature got lost when we moved to `react-virtualized`. This restores displaying the file id for executed steps
=> SEQNG-312: Display fileId of executed steps

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
I noted the browser debugger doesn't understand well these empty responses, so I'm returning an empty string instead. This change has no effect in the application except when displaying the logs on development
=> Don't return empty responses

modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/tcs/TcsControllerEpics.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
As requested we'll keep a longer log in memory in clients and reduce some messages from INFO to DEBUG
=> SEQNG-533: Keep more log in the scroll buffer

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/label/Label.scala
This is the first part of a change to get the urls to contain the step. Once I started I noted several small defects that could be improved and they are contained on this PR:
* Display the routes on the title
* Have proper links displayed when hovering on a table
* Some small improvements on what's loaded when a sequence is running or the page is just launched with elements on the queue
=> SEQNG-413A: URL markers for step id

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LogArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTable.scala
These are some improvements to the way tables are displayed. For example, when a table was too short the borders didn't extend all the way down and we'd get double borders sometimes
The difference is subtle but enough for me to notice it
=> SEQNG-525: Fix border for tables shorter than full heigh

modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelLenses.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/enumerations.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/properties.scala, modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/ModelLensesSpec.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepSettings.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTable.scala
This adds, for GMOS-S, a column in the steps table for the disperser, with the form:
`${dispersername} @ ${centralWavelength} nm`
=> SEQNG-540: Added code to display disperser column for GMOS-S

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
This PR will convert the queue table to `react-virtualized`. This will unify the look and feel also keep the headers always in place
=> SEQNG-502: Convert the queue table to use react-virtualized

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala
This is a tiny fix to support displaying the step settings table for done steps. Those are marked as disabled but this fix lets the last column to accept clicks
=> SEQNG-440: Enable displaying settings of disabled steps

modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Engine.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/SystemEvent.scala, modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/UserEvent.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala, modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelLenses.scala, modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/events.scala, modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
When there is a resource conflict (an attempt to run a sequence no an instrument in use) a notification is displayed. However, this is displayed to all the clients. This fixes that and only the user requesting running the sequence will be notified
=> SEQNG-212: Display an indication on the UI when there are resource conflicts

build.sbt, project/build.properties, project/plugins.sbt
This PR changes the way to calculate the version in such a way that the hash is always shown. The format is
`<last-tag>+<commits-after-last-tag>-<hash>|-<date>-<time>-UNCOMMITED|`
The part between `|` is only used if there are uncommitted changes
There are 4 scenarios:
* We are on a tag without Uncommitted changes, in that case, the version is:
**0.8.7+0-468910be**
* We are on a tag with uncommmited changes:
**0.8.7+0-468910be-20180321-1931-UNCOMMITED**
* We have commits after the last tag:
**0.8.6+17-468910be**
* Commits after the last tag and uncommited changes
**0.8.7+0-468910be-20180321-1931-UNCOMMITED**
@tpolecat, @swalker2m , @arturog8m  Does this seem right?
=> Use sbt-dynver to produce the version

build.sbt, project/Settings.scala
The GMP has been updated upstream to run on java 1.8 and scala 2.12
This PR updates the dependencies to use the new release
=> SEQNG-575: GMP update

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/OffsetDisplayCell.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/edu.gemini.web.client.facades/src/main/scala/edu/gemini/web/client/facades/semanticui/utils.scala, project/plugins.sbt
The width of the columns on the obs queue was fixed and sometimes that produced text to be truncated. This PR adds a simple calculation of the text length to better estimate the columns' width
It also fixes some styles issues that sometimes made the table misaligned
Before:
After:
=> SEQNG-583: Obs queue column widths sometimes too narrow

modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
Cats.IO does not catch fatal VM errors, so the test that verified that those errors were not caught became unnecessary.
=> SEQNG-586 Modified exceptions test, removed unnecessary cases.

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/encoder/BooPickleInstances.scala
This is a small improvement on how boopickle is encoded in http4s. It reduces a byte array copy per message.  I hope to provide these encoders to be integrated in http4s
=> Improved encoding of boopickle

build.sbt
When there is an OOM only the thread the exception happened dies. With the JVM setting below the whole process should die
Note we need a newer jvm for this so on the build machine I installed build 1.7.1
=> SEQNG-591 Instruct the jvm to crash on OOM

modules/edu.gemini.epics.acm/src/test/java/edu/gemini/epics/acm/test/CaStatusAcceptorTest.java, modules/edu.gemini.epics.acm/src/test/java/edu/gemini/epics/acm/test/XMLBuilderTest.java, project/Settings.scala
This PR contains the epics libraries with the latest versions of jca and caj. @jluhrs you can use these for testing of the epics issues but the unit tests are failing.
=> Updated epics libraries

build.sbt, project/Settings.scala, project/plugins.sbt
Scala.js update to 0.6.23. this is a bit more complex update as scala.js only crossprojects have been deprecated in favor or `sbt-crossproject`
=> Scala.js upgrade and use sbt-crossproject

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/webpack/dev.webpack.config.js
Small bug out of the build refactoring. The webpack-dev-server proxy wasn't properly proxying one of the routes used in intialization
=> Correctly proxy the start event

modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/resources/less/style.less, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala, modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTable.scala, project/Settings.scala
Likely as a result of the large Ui refactoring there are some visual artifacts on the tables. This PR fixes them. The table's code is still a bit ad-hoc but I plan to make it more generic when I add support for resizable columns
Before:
After:
=> Fixes for table border alignment

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/model.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala, modules/seqexec/web/server/src/test/scala/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
The sync button gets disable after pressing Sync. Thes PR fixes it by moving the state of sync in progress to the top level model
There is also an extra simplification as the `sync` url routes are different than for other commands. This PR fixes that and simplifying the routes definition on the server side as well
=> SEQNG-601: Sync button disabled

build.sbt, project/plugins.sbt
A new version of `scalajs-bundler` now properly exports the list of assets. `sbt-native-packager` can now use this list to properly package the app in one pass
=> Update scalajs-bundler and simplify app build

.travis.yml
The build is a bit flaky failing sometimes when building the optimized clients. Scala.js hasn't confirmed support for node 10.x which is now the default in travis
This PR forces to use node 9
=> Use node 9 in travis

build.sbt, modules/core/shared/src/test/scala/gem/arb/ArbTime.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPI.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPIController.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala, modules/seqexec/server/src/test/scala/seqexec/server/gpi/GpiSpec.scala
First pass at reading GPI configuration from the OCS. This will evolve as we need to actually use this values when configuring the instrument
I added a dependency to gem/core to use some of the arbitraries :D We could call gem/ocs3 integration done 😄
Code is formatted at 80 columns with scalfmt
=> SEQNG-611: GPI Configuration Model

modules/ephemeris/src/main/scala/gem/horizons/HorizonsNameQuery.scala, modules/ephemeris/src/test/scala/gem/horizons/HorizonsNameQuerySpec.scala
This PR brings the Horizons [asteroid format updates](https://github.com/gemini-hlsw/ocs/pull/1472) over from the `ocs` project.  Unfortunately I cannot add a test case for one of the formats because there don't seem to be any examples that produce it.  The objects were all reclassified as comets.
=> Support new asteroid formats

app/seqexec-server/src/main/resources/app.conf, modules/seqexec/web/client/src/webpack/prod.webpack.config.js, modules/seqexec/web/client/src/webpack/webpack.parts.js
During the last ui build update we lost [css autoprefixing](https://css-tricks.com/autoprefixing-css-variables/). We used to do that with scalacss but we removed that. Now we can re enable it with `webpack` and `postcss/nano`.
Note the process is fairly slow so it is only enabled for the final production
=> SEQNG-612: Enable autoprefixing on production

modules/ephemeris/src/main/scala/gem/horizons/HorizonsEphemerisQuery.scala, modules/ephemeris/src/test/scala/gem/horizons/HorizonsEphemerisQueryPagingPropSpec.scala, modules/ephemeris/src/test/scala/gem/horizons/HorizonsEphemerisQuerySpec.scala
This PR fixes the [Random ephemeris test failure](https://github.com/gemini-hlsw/gem/issues/278) issue.  The problem was in the code that pages a long request into smaller queries that are palatable for horizons.  One of the complications is that a query for just a single element doesn't work.  The previous version of this code would try to shrink the next-to-last query by one element and thereby make the last query request two elements in this case.  I tried to simplify the logic somewhat and just request an extra element instead.   It's still a bit convoluted unfortunately.
=> Horizons paging bugfix

modules/seqexec/model/src/main/scala/seqexec/model/Model.scala, modules/seqexec/web/client/src/main/resources/dev.js, modules/seqexec/web/client/src/main/resources/prod.js, modules/seqexec/web/client/src/main/scala/seqexec/web/client/SeqexecApp.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala, modules/seqexec/web/server/src/test/scala/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
This is a bug leftover from the ui build revamp. it used to be that the client will be custom built for each site with the site name embedded on the html. However now that is generated by webpack and for testing it was left at GS.
This fix changes how the client starts. It will query the site before launching and will configure itself for that site. This is slightly inefficient and could be improved by changing the build but that will be an involved task
This has been tested changing the site locally and also verified building the distributions for GN and GS
=> SEQNG-627: Web server does not honor site configuration

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/OffsetDisplayCell.scala, project/plugins.sbt
A minor scala.js update got a lot more complicated due to a bug fix on the floating point formatting algorithim
=> Update to scala.js 0.6.24

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/SequenceArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/checkbox/Checkbox.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/input/InputEV.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/slider/Slider.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/WebpackResources.scala, project/Common.scala, project/Settings.scala
This brings several libraries up to date including:
* http4s
* scalajs-react
* react-virtualized
I also noted we still had a bit of scalaz usage on the client, this PR removes that as well
I'm also skipping checking some legacy dependencies for updates. 
@tpolecat There are a few updates on the db side libs but I didn't want to update those
=> Lib updates

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/SequenceArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/button/Button.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/button/ButtonGroup.scala
This is an idea I got from using GPI. often I'd like to check the config of step N and then check step N+1 but this meant navigating back to the steps table.
In this PR I'm adding buttons to navigate directly on the config page. I hope it is useful.
I'm also using this PR to check if I can reuse semantic ui less variables. This will be very helpful on theming.
=> SEQNG-631: Support navigating steps from the configuration table

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
Just some css changes to fix SEQNG-645. now it looks correct:
=> SEQNG-645 Fixes display for rows with breakpoints and completed

modules/seqexec/model/src/main/scala/seqexec/model/Model.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/SeqexecApp.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/Footer.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecUI.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/SequenceArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceAnonymousToolbar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/model.scala
Another removal of a duplicate case from the seqexec mini model and use of the core `Site` class instead
=> SEQNG-648: Use Site type from core

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers.scala
Small css fixes for alignments on the steps table. I added a handler to simulate more easily events like running a step without having to actually run a sequence
before:
after:
before:
after:
=> SEQNG-655 Fix UI alignment issues on the running steps

build.sbt, build/buildkite-build.sh, build/buildkite-pipeline.yml, modules/ctl/src/main/scala/free/ctl.scala, modules/ctl/src/main/scala/hi/deploy.scala, modules/ctl/src/main/scala/low/docker.scala, modules/ctl/src/main/scala/main.scala, project/ImageManifest.scala
This is work toward getting continuous deployment working. It fixes the deploy stuff to use the versioning scheme @cquiroz came up with, so we're now consistent there; and it adds a step to create a docker image for `develop` merge builds (i.e., not for PRs or other branches) and deploys it to the test machine `sbfocstest-lv1`, HTTP REST on 9090 and telnet on 9091. Each deployment destroys the previous one; there is no data migration yet.
This also splits the log up into sections and adds wee emojis to delight and entertain.
=> Auto-deploy to sbfocstest-lv1 for `develop` merges

modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
The reported bug was that Seqexec was not setting the GNIRS parameter `centralWavelength`. The cause was a bug in the function that compares the current value to the requested value.
I also change the comparison criteria to use a relative threshold. That makes more sense for floating point numbers.
=> SEQNG-651 Fixed function smartSetDoubleParam.

build.sbt, project/ImageManifest.scala
This removes the `gem.history` label from our docker images (this used to contain a list of commit hashes but it turns out there's a size limit) and instead generates a `GIT_HISTORY` file with one commit hash per line (head is the release commit) that shows up at `/opt/docker/GIT_HISTORY` in the container filesystem. This allows the production release process to verify that the running version's commit hash exists in the new version's history. If so then database migration is supported and we can attempt an upgrade release.
For reference
docker run --entrypoint "/bin/cat" <image-hash> /opt/docker/GIT_HISTORY
will list the file contents. I will circle back and fix the upgrade deployment logic to use this.
=> remove history label, add history file

modules/seqexec/web/client/src/main/resources/dev.js, modules/seqexec/web/client/src/main/resources/prod.js, modules/seqexec/web/client/src/main/resources/theme/semantic.less, modules/seqexec/web/client/src/webpack/webpack.parts.js
Semantic UI Css is fairly big but it can be reduced by selecting a subset of the widgets
This PR does that reducing the css size from 545Kb to 408Kb
=> SEQNG-662: Reduce semantic ui css

build.sbt, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/QueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/model.scala, modules/shared/web/client/src/main/scala/web/client/table/package.scala, modules/shared/web/client/src/test/scala/web/client/table/TableSpec.scala
This is a fairly large PR which makes the basis to make all tables columns-resizable and to remove a family of quirks related to state being lost when the core model changes. The changes are fairly big so I'm testing them on the step config table before tackling the Steps table where the bugs are more evident
This PR contains:
* Made the Step Config table columns resizable
* Factor out some common code for tables with resizable columns
* Preserve the resize and scroll position across model changes. This can be observed on the image below where the column sizes and scroll position is kept when the step changes:
=> SEQNG-661: Resizable config table and preserve state

modules/seqexec/web/server/TLS.md
Actually, the full cert chain is recommended according to ITS. Here the documentation has been updated
=> Update procedure to chain the certificates for TLS

build.sbt, project/Settings.scala
We have been using a simple react component to do copy to clipboard. This component is now outdated and not being maintained which is reflected in this error message
```
[error] warning " > react-copy-to-clipboard@5.0.0" has incorrect peer dependency "react@^15.3.0".
```
This PR removes this dependency and uses a pure scala component instead
=> SEQNG-595: Copy to clipboard component

modules/service/src/main/scala/gem/Service.scala, modules/web/src/main/scala/Application.scala
I'm reopening this PR in the new buildkite world now that the JSON codec for observations is working again. It provides a minimal API for fetching observations from the database, looking ahead to converting the seqexec.
I believe this signature in the `Service` API:
```scala
def queryObservationById(id: Observation.Id): M[Observation]
```
should probably be changed to handle the presumably common case in which the indicated observation doesn't exist.  I wanted to get feedback first though since we should have a common way of handling this and we may want to update the DAO API accordingly.  At the moment, everything assumes the named observation exists.
=> Observation import and fetch service API

modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/Gcal.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPI.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/ObsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/QueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, project/Settings.scala
Some minor simplifications:
* Use `extractAs[A]` instead of `extract().as[A]`
* Remove some parameters on the table columns that default correctly upstream
=> Code simplifications

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/seqexec/web/client/src/webpack/dev.webpack.config.js, project/Settings.scala
It was requested for the inactive instrument tabs to have a border too:
=> SEQNG-669: Add a border to inactive instrument tabs

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/QueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/shared/web/client/src/main/scala/web/client/table/package.scala
This PR makes the log table columns resizable. I'm also expanding code reuse across all the tables;
Here is how it looks like:
=> SEQNG-666: Make log table columns resizable

build.sbt, modules/giapi/src/main/scala/giapi/client/commands.scala, modules/giapi/src/main/scala/giapi/client/gpi/GPIClient.scala, modules/giapi/src/main/scala/giapi/client/package.scala, modules/giapi/src/test/scala/giapi/client/GiapiCommandSpec.scala, modules/giapi/src/test/scala/giapi/client/GiapiStatusSpec.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPI.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPIController.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/web/server/src/main/resources/app.conf, project/Settings.scala
This is a fairly important change and should not be merged until tested with an instrument.
When a giapi command is sent it can reply that something is excuted right away or that it will complete later. At the moment we assume that it will eventually complete but that may not be always true due to instrument code bugs or other unforseen events.
This PR changes the api so each command will take a timeout and fail if the timeout isn't fullfilled
This led to using some advanced `cats-effect` functions which took me a while to grasp.
The PR also improves the testing situation and it even test the particular case of a command never completing
=> SEQNG-633: Add timeout for configuring

modules/seqexec/web/client/src/main/resources/dev.js, modules/seqexec/web/client/src/main/scala/seqexec/web/client/SeqexecApp.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers.scala
This is a UI development only improvement
When doing UI development we use webpack-dev-server with Hot module replacement (HMR) which listens for code updates and refreshes the page. It is a very good utility and helps a lot during UI development
However, the seqexec ui uses websockets and those are not closed when the ui is reloaded leading to some overhead and duplicate messages. This PR listens to HMR reloads and kills the previous web socket connection
=> SEQNG-598: Reset websocket connection upon HMR updates

modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerSim.scala
This is a small improvement on how tcs logging is done from:
to
=> Improve TCS subsystem logging

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
It was requested to make the executed rows more visible:
Before
After
The changes may look extensive but i'm mostly cleaning up variables usage on the css/less
=> SEQNG-668 Change the background of executed rows

modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/model/src/test/scala/seqexec/model/SharedModelArbitraries.scala, project/Settings.scala
Some time ago i tried to use `scalacheck-shapeless` to do automatic derivation of `Arbitrary`. While it removes boiler plate it increases substantially compilation time
Here I'm removing it and write the arbitraries explicitly 
It should have some 20-30s of compilation time
=> Don't use arbitrary automatic derivation

modules/seqexec/model/src/main/scala/seqexec/model/enum/Resource.scala
Oddly this changed perhaps when copying it from the old Model class?
I guess it is another indicator to use `Instrument` from gem
/cc @tpolecat
=> Bad naming of instruments

build/buildkite-build.sh, build/weigh.sh, build/weigh_in.py, modules/seqexec/web/client/src/webpack/prod.webpack.config.js, modules/seqexec/web/client/src/webpack/webpack.parts.js
We used to have checks on the js asset sizes on travis. The move to buildkite broke them and this PR restores them by adapting the script setting github statuses
I also added checks for the fully optimized assets
=> Asset size checks

modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
I've been trying to uncover a memory leak without much success. I suspect the odb refresh is the reason but I'm not totally sure
However talking to the fs2 they indicate it maybe related to our usage of `fixedRate` and suggest `fixedDelay` instead
This change doesn't affect the application but can give us a solution no the leak
=> Switch to fixedDelay

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala
When setting a breakpoint the table jumps to the first row which is quite annoying.
Also there is a bug on SEQNG-491 when a sequence is larger than the table. If you scroll to a lower position and hover the scroll position is reset to 0 which essentially makes it impossible to click on a lower breakpoint
This PR fixes both by keeping track of the scroll position and resetting it on reload.
Performance is also improved by reducing the amount of redraws
=> SEQNG-705: Fix for hovering out of range

build.sbt, modules/core/shared/src/test/scala/gem/Arbitraries.scala, modules/seqexec/model/src/main/scala/seqexec/model/SequencesQueue.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala, modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/QueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecUIModel.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/LoadedSequencesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/SequenceDisplayHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/model.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/CircuitReaderSpec.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ModelSpec.scala, modules/seqexec/web/shared/src/test/scala/seqexec/web/common/ArbitrariesWebCommon.scala, modules/shared/web/client/src/test/scala/web/client/table/TableArbitraries.scala, modules/shared/web/client/src/test/scala/web/client/table/TableSpec.scala
In diode one of the features is `RefTo` which lets you do references across the model. While teorethically nice in practice they don't work well as we need usually two actions to get the model correct. This is more evident when doing a load sequence which ends up being unnecessarily slow
In this PR I remove this simplifying the updates though by necessity this requires a bit more manual bookkeeping.
In addition I'm using monocle Lenses to generate diode `ModelRW` instances as they are easier to build and compose
The PR is largish but it is mostly test code
=> SEQNG-703: Remove use of RefTo in the model

modules/seqexec/model/src/main/scala/seqexec/model/Notification.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala
This change prevents to assign a sequence to an instrument if the current one is running.
It also includes some changes to a show a notification to the user. The actual pop-up will be implemented in SEQNG-712
=> SEQNG-606 Don't load sequence if instrument is in use.

modules/seqexec/model/src/main/scala/seqexec/model/Step.scala, modules/seqexec/model/src/main/scala/seqexec/model/enum/Resource.scala, modules/seqexec/model/src/test/scala/seqexec/model/ModelSpec.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecMain.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/UserNotificationBox.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/reusability.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/SequenceArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ClientStatus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/model.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/CircuitReaderSpec.scala
This bug took a lot of effort to fix but uncovered a fundamental mismatch between diode's `ModelProxy` and scalajs-react `Reusability`. I've opted to get rid of `ModelProxy` on the components
Also `Eq` instances have been improved for `Step`
=> SEQNG-708: Client does not update state of configured systems

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/QueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/OffsetDisplayCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/shared/web/client/src/main/scala/web/client/table/package.scala, modules/shared/web/client/src/main/scala/web/client/utils.scala, modules/shared/web/client/src/test/scala/web/client/table/TableArbitraries.scala
On the resizable columns if one makes a column too narrow you get weird effects like:
This provides a fix by setting a minimum width and also adds some small style fixes
This is happening because the header width has a minimum which depends on how css clips it. For the same reason cannot be easily measured and it is easier to just measure it on the browser
=> SEQNG-704: Bad queue layout if column resized too small

modules/db/src/main/scala/gem/dao/ObservationDao.scala, modules/db/src/main/scala/gem/dao/ProgramDao.scala, modules/db/src/main/scala/gem/dao/SmartGcalDao.scala, modules/db/src/test/scala/gem/dao/ObservationDaoSpec.scala, modules/service/src/main/scala/gem/Service.scala, modules/web/src/main/scala/Application.scala, project/plugins.sbt
This PR addresses feedback from #606, splitting the observation retrieval options in two: fetch vs. query.  Fetch expects an observation with the indicated ID to exist and raises an error if it doesn't while query returns optional results.
I let this update trickle all the way down to `ObservationDao`, though I suppose another option would be to leave the DAO with just the original exception raising option and handle the query option by dealing with the exception in `Service`.
=> Fetch vs. Query

modules/web/src/test/scala/ApplicationSpec.scala
Following a suggestion from #606, this PR offers a few basic `gem.web.Application` tests.  For the most part they just check that things are hooked up correctly.  In particular more extensive testing of the program listing query could be provided if we keep it in its current form.
=> Application Tests

modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPIController.scala
=> SEQNG-701: Fixed giapi channel to set the GPI prism

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/QueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecUI.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/InstrumentsTabs.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/Pages.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/InitialSyncHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/LoadedSequencesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/TableStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/handlers.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/CircuitReaderSpec.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/PagesSpec.scala, modules/shared/web/client/src/main/scala/web/client/utils.scala
One annoying thing on the main steps tables is the tendency to go to step 0 after switching tabs or running a step. This PR is an improvement. When a sequence is loaded or previewed it will jump to the next step to run and will remember if the user scrolls
=> SEQNG-413: Jump to next step to run

modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala, modules/seqexec/model/src/main/scala/seqexec/model/events.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecEventSpec.scala, modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/reusability.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/TabOperations.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/NotificationsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/OperationsStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/RemoteRequestsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ModelSpec.scala, modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala
With the change of the user notification system we lost the box for Resources Busy. This PR fixes that and adds some improvements to the way operations state is handled. We use this to enable/disable buttons during the duration of an operation
=> SEQNG-716: Resources box dialog box is not displayed

build.sbt, modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Sequence.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Step.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/EngineSpec.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
The `update` method in `Sequence.State.Zipper` was trying to do too many things. It was used to refresh the steps `executions` when, for example, the operator name changed, and also to update the whole sequence when reloading it from the ODB. I separated it into two functions, `update` and `reload`.
=> SEQNG-715 Fixed code that updates and reloads sequences

modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/StandardHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerSim.scala
This is a small PR that forces the AC pickup mirror to be parked in the AG unit if the instrument in use is in port 1 (bottom port). It only has an effect if the TCS is configured for that step. That means, it will be used for GCAL calibrations or on sky observations, but ignored for Biases or Darks.
=> SEQNG-700 Force AC park if instrument is in port 1.

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
As per SEQNG-690, there was some confusion in the sequence table  due to the repetition of a "Control" column. (The first column with the icon had the tooltip "Control", and the second had the name "Control.")
As per the recommendation in the task, I changed the column name to Execution Progress.
Here is a snippet showing this. Please let me know if this is what was expected :-).
=> SEQNG-690: Change control column name

modules/seqexec/model/src/main/scala/seqexec/model/ExecutionQueue.scala, modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala, modules/seqexec/model/src/main/scala/seqexec/model/SequencesQueue.scala, modules/seqexec/model/src/main/scala/seqexec/model/package.scala, modules/seqexec/model/src/test/scala/seqexec/model/ExecutionQueueSpec.scala, modules/seqexec/model/src/test/scala/seqexec/model/ModelLensesSpec.scala, modules/seqexec/model/src/test/scala/seqexec/model/ModelSpec.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecAppRootModel.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecUIModel.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/InitialSyncHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/LoadedSequencesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/TableStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/handlers.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/SequencesOnDisplaySpec.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala, modules/seqexec/web/shared/src/test/scala/seqexec/web/model/boopickle/ModelBooPicklersSpec.scala
This updates the client model to carry the calibration queue to the client. I also did some work on tests to make them faster and did some formatting
=> SEQNG-561: Add calibration queue to the global state for the client

modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Event.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Handle.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/UserEvent.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/SequenceSpec.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/StepSpec.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala, modules/seqexec/model/src/main/scala/seqexec/model/enum/BatchCommandState.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala
Running the calibration queue means that at any point in time after the user commanded to run the queue, if any sequence in the queue can be run, it must be running.
When the command arrives, every sequence in the queue that can be run (minding resource usage) is started. Then, whenever a sequence finishes and frees resources, the check is repeated.
=> Run calibration queue.

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/reusability.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/TabOperations.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/OperationsStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/RemoteRequestsHandler.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
I've been refactoring the client side handling of remote requests to reduce the reliance on booleans and properly handle remote errors.
This time is pause:
=> Pause operation

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceInfo.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
I've been trying to simplify the client side model removing some shorcuts and relying more on lenses as possible
This in one of those refactorings to remove a kludge to avoid `Option` in certain cases, but it was kind of cheating
=> Refactoring of sequence extracting lenses

build.sbt, modules/seqexec/model/src/main/scala/seqexec/model/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/QueueTabContent.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/QueueToolbar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/reusability.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/CalibrationQueues.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/QueueOperations.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecUIModel.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/QueueControlFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueOperationsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueRequestsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/RemoteRequestsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/icon/Icon.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/shared/web/client/src/main/scala/web/client/table/SortableRow.scala, modules/shared/web/client/src/main/scala/web/client/table/package.scala, project/Settings.scala
This PR adds all daycal calibrations to the queue. It doesn't do much of practical value beyond exercising the model but this PR also adds a substantial amount of infrastructure and it is getting large already
I'm also adding an extra dependency to support resorting the quee table
=> SEQNG-564: Add button to send day cal sequences to the calibration queue

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/CalibrationQueues.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/AppTableStates.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/CalQueueControlFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/CalQueueFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueOperationsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/TableStateHandler.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
The state of the column's widths and scroll location of the cal table should be stored in the model to preserve it when doing changes.
This PR does exactly that.
=> SEQNG-735: Store the state of the cal tables at the root model

modules/acm/src/main/java/edu/gemini/epics/acm/CaWindowStabilizer.java, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
A premature AG in-position has being mentioned as a possible cause for SEQNG-652. This PR implements a similar check as the one in place in the Tcl Seqexec. The in-position value has to stay unchanged for 1 second before being declared valid.
=> SEQNG-652 Added stabilization check for TCS and AG in-position.

modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
Small mistake preventing the removal of indivdual seqs of the cal queue
=> SEQNG-763 Fixed setting the url when removing an item from the queue

modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOST.scala
Right now, we dont want to deal with missing parameters, as in the architecturing of this initial implementation, there will absolutely be missing parameters since not every combination of parameters is compatible. (Enforcing parameter compatibility is someting we will worry about later, as this is just for initial testing and will be thrown away / modified heavily as GHOST moves on.)
Thus, right now, we extract the parameters, populate a `GHOSTConfig` object, and return it as having "succeeded" in the extraction.
=> SEQNG-643: Fixing GHOST fromSequenceConfig to always return a GHOSTConfig (for now).

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SequenceTabContent.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/TabContentFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/LoadedSequencesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/SequenceDisplayHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
When a sequence completes we want to still display it though it has been removed from the server side model. Thus we copy the state, however there were some bugs on the process
This PR fixes that and it also fixes a small bug leading to SEQNG-765
=> SEQNG-768: Do not remove the last executed sequence

modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala, modules/seqexec/model/src/main/scala/seqexec/model/enum/BatchCommandState.scala, modules/seqexec/model/src/main/scala/seqexec/model/enum/BatchExecState.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueToolbar.scala
* Calibration queue status is Completed as long has it has run at least once, and there are no unrun sequences in the queue.
* It goes back to Idle if it is Completed, but a new sequence is added.
* Now it is possible to add or remove sequences to the Calibration queue while it is running.
* It now attempts to start a new added sequence, if the queue is running.
* Fixed bug where sequences removed from the Session queue were not removed from the calibration queue.
=> Fixed some issues with calibration queue status

modules/seqexec/model/src/main/scala/seqexec/model/authentication.scala, modules/seqexec/model/src/main/scala/seqexec/model/enum/Resource.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala, modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/GemModelBooPicklers.scala, modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala, modules/seqexec/web/shared/src/test/scala/seqexec/web/model/boopickle/GemModelBooPicklersSpec.scala, modules/seqexec/web/shared/src/test/scala/seqexec/web/model/boopickle/ModelBooPicklersSpec.scala
I've noted we don't always explicitly define all boo picklers leading to bigger size. From now on this should fail to compile rather than use the auto generated pickler via macros
=> Make all BooPicklers explicit

build.sbt
the TZDB changed yesterday and it breaks the parser and the build
While this will be fixed upstream, in the interim we need to fix the tzdb version
=> Fix the tzdb version

modules/seqexec/model/src/main/scala/seqexec/model/enum/QueueManipulationOp.scala, modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTabContent.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/CalibrationQueues.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/CalQueueFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueOperationsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueStateHandler.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/shared/web/client/src/main/scala/web/client/table/SortableRow.scala, modules/shared/web/client/src/main/scala/web/client/table/package.scala, project/Settings.scala
When a user edits the cal queue the other uses don't have an indication, except when the table changes. This PR is an attempt to improve this using animations. It is also an opportunity for me to learn about animations:
Here are some videos, FF is on the left and the user edits it and Chrome is on the right and the user can see the changes:
Adding sequences:
https://monosnap.com/file/tVTTXDPgxFLcWxd8MmclNcG6yvqaqU#
Clear the queue:
https://monosnap.com/file/9JbApHs4hvEYjgEJYW3OkEdMNTgmvA
Remove elements:
https://monosnap.com/file/liJNeSEc2cU93VBgnsv9GZJe4DnL7q#
Animations are hard 😄 this is as far as I probably want to go with this
The changes were tested in Chrome and FF in OSX
The PR also fixes SEQNG-761
=> SEQNG-734: Indicate when the cal queue table changes

modules/seqexec/model/src/main/scala/seqexec/model/enum/QueueManipulationOp.scala, modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTabContent.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/QueueSeqOperations.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueOperationsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueRequestsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala, modules/shared/web/client/src/main/scala/web/client/style/package.scala, modules/shared/web/client/src/main/scala/web/client/table/ColumnWidth.scala, modules/shared/web/client/src/main/scala/web/client/table/TableState.scala, modules/shared/web/client/src/main/scala/web/client/table/package.scala, project/Settings.scala
This is a relatively large change to support reordering of the elements on the cal queue:
https://monosnap.com/file/aVgw2RtxrzbxRnnLJ6dePVpCyx7T61#
The change produced several regressions on animation, and updates, they should be fixed by the most part but some may have escaped
=> SEQNG-738: Support reordering of the queue

modules/giapi/src/main/scala/giapi/client/gpi/GPIClient.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/Settings.scala, modules/seqexec/server/src/main/scala/seqexec/server/TranslateSettings.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
There is a serious bug on the current seqexec which doesn't let GPI to run as the configuration of GHOST is passed instead
This is an easy mistake to make, so besides a fix I added tagged types to ensure the correct type is passed
Also we have `SeqexecServer.Settings` and `SeqTranslate.Settings` which is quite confusing. I moved both to their own classes and renamed the latter to `TranslateSettings`
=> SEQNG-778: GPI configuration not being picked up

modules/seqexec/server/src/main/scala/seqexec/server/ConfigUtilOps.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOST.scala
The support to take a `Config` object and parse angles from it was not implemented; GHOST needs the target information to send to the instrument.
This adds:
1. The logic to GHOST to parse `Angle` and `HourAngle`; and
2. Now also follows the same pattern as GPI, where it can result in errors arising from incorrect `Config` entries.
=> SEQNG-779: Fixed GHOST to parse angles

modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPIController.scala
When making this PR for GHOST, @tpolecat and @jluhrs had some good comments about how we should be using `SeqActionF.apply` to clean up `EitherT.liftF(Sync[F].delay(...))` code, since it does the same thing and is much less verbose and clearer:
https://github.com/gemini-hlsw/ocs3/pull/711
This is code I grabbed from `GPIController` directly, and just changed the names.
Because of the code reuse, we should consider moving `applyConfig` to a parent class (right now there is no shared parent class), especially  if other GIAPI instruments will be similar. (I see now that the code for the non-GIAPI instruments is quite different and doesn't share this.)
=> SEQNG-783: Switched GPIController to use SeqActionF.apply.

modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Sequence.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/EngineSpec.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/SequenceSpec.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/StepSpec.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/TestUtil.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerLensesSpec.scala
The sequence data used by the execution engine and the sequence data used by the seqexec server (the upper level) are kept in separate Maps. This PR uses Lenses magic join those Maps in a single one, while keeping the execution engine agnostic of the extra data required by upper level.
=> SEQNG-796 Merged engine and server sequence data in a single Map.

build.sbt, modules/seqexec/model/src/main/scala/seqexec/model/ObservationProgress.scala, modules/seqexec/model/src/main/scala/seqexec/model/events.scala, modules/seqexec/model/src/main/scala/seqexec/model/package.scala, modules/seqexec/model/src/test/scala/seqexec/model/ModelSpec.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecEventSpec.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala, modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala, modules/seqexec/web/shared/src/test/scala/seqexec/web/model/boopickle/ModelBooPicklersSpec.scala, project/Settings.scala
The seqexec engine is sending countdown time updates as regular global model updates. This changes it by sending a specific `ObservationProgress` event
I also updated several libs to their latest versions
=> SEQNG-789: Export countdown time on the websocket channel

modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/StatusAndLoadedSequencesFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/TabFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/WebSocketHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala
While testing i noted a small bug where if you are on a config page of seq X and the seq is updated, e.g. when running the view will jump back to the main table
This PR fixes this and do some refactoring
=> SEQNG-794: Fix bad navigation when on config page

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala
This change makes the Exposure and Filter columns optional in the StepsTable, since GHOST does not yet currently have these properties and we hence don't want these columns to be displayed when a GHOST observation is selected.
Here is the result for GHOST:
Here is the result for GMOS, appearing the same as before:
=> SEQNG-682: GHOST UI changes, round 1.

modules/seqexec/model/src/main/scala/seqexec/model/operations.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/StepsTableAndStatusFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/StepsTableFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepBreakStopCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTools.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/reusability/package.scala
Updates to the steps tables are slow to be applied. This was traced as too much data being passed to the components. This PR passes less data which reduces the amount of data being checked to decide what to render.
This could be further improved removing some of the data of the step config but the results with this PR are very good. Table updates are rendered much faster with these changes
=> SEQNG-793 Improved rendering times on the steps table

modules/seqexec/model/src/main/scala/seqexec/model/ObservationProgress.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ObservationsProgressStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/AllObservationsProgressState.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
As a continuation of https://github.com/gemini-hlsw/ocs3/pull/725 we can do the same on the client side. This avoids a UI glitch when ending a step and starting the next
=> SEQNG-813: Index obs progress by ons id and step id

modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/AppTableStates.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/StatusAndLoadedSequencesFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SessionQueueArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SessionQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecAppRootModel.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecUIModel.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
A bug in a previous refactoring produced that not all changes to the global state be reflected on the session queue, e.g. when going from one step to the next
This PR fixes this and adds some improvements to reduce the amount of refreshes
=> SEQNG-786: Better change handling on the session queue

modules/seqexec/web/client/src/main/scala/seqexec/web/client/SeqexecApp.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
When the client start is now making 2 calls, one to read the site and another to tell the browser who the user is. These 2 calls can be merged into one making the client startup a bit faster
=> SEQNG-746 Reduce startup calls for site to 1

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
Small bug fix, the stop/abort buttons were disabled after resume
=> SEQNG-510 Enable stop/abort after resuming an obs

modules/seqexec/model/src/main/scala/seqexec/model/package.scala, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SessionQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceInfo.scala
The original default was missleading as there can be flats for day and night. This is how it looks now
=> SEQNG-815 Display None for unknown targets

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SessionQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/CalibrationQueueTab.scala
After several failed attempts to integrate libraries to do DnD I resorted to do this with the plain HTML5 DnD API. the API is well know for its quirks so it maybe not that robust but seems to work fine in Chrome/FF
This version is also limited and less polished as I'd like but given we have other ways to add seqs to the queue I'll accept this limited version.
Now it is possible to grab a sequenc from the session table and drop it on teh daytime queue tab. This also lets you do this even if other tab is selected.
Here's a video
https://monosnap.com/file/payj5aY8sm1agn62g9VYu2hJtXDh2H#
=> SEQNG-718: Support D&D to the cal queue

modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOSTController.scala
HI all,
Last week when speaking with the instrument team from Australia, I received some answers that necessitated changes to the way GHOSTController worked: hence, this PR.
The idea for each IFU is:
1. If the standard resolution configuration is set, use it.
2. Otherwise if the high resolution configuration is set, use it.
3. Otherwise the IFU must be moved out of the way: request it to be parked.
We are also temporarily turning off observes since they will not be involved in tonight's testing, and all we want to do is test configuration applies.
=> SEQNG-678: GHOST configuration

modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/StepsTableFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepBreakStopCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SubsystemControlCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/RemoteRequestsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/TabOperations.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/reusability/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/SequencesOnDisplaySpec.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/package.scala
This PR adds buttons to request configuring a subsystem for a given step. This lets you select a step and it will show the buttons for that step. The backend is not yet implemented so it is just simulated but it would let @jluhrs to test
Here it is in action
https://monosnap.com/file/CVwpsSr7tsTPGdLJij3fDEgKLJO4b7#
There are several things pending though
* Get the state to be reflected on all clients
* Forbid multiple clients requesting the same resource
* Display configuration error messages
* Show activity on the rest of the UI
=> SEQNG-806: Add system configuration buttons in steps

modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOST.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOSTController.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala
During GHOST testing, it was discovered that the seqexec had illegal values for declination. This was due to me using `HourAngle` and `Angle` instead of `RightAscension` and `Declination`, as I should have.
This fixes that.
=> SEQNG-825: Fix GHOST coordinates

modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java
This solves the issue with Seqexec crashing on startup if GNIRS was not available (could have happened with other instruments, but was discovered with GNIRS).
=> SEQNG-826 Catch errors when binding to stop and abort channels.

modules/seqexec/server/src/main/resources/Flamingos2.xml, modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/ProgressUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Epics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsEpics.scala
Countdowns are not so pretty when dealing with the real world.
1. Seqexec now uses the FLAMINGOS-2 provided countdown.
2. Guarded against limit cases, like the countdown not having a valid value for several seconds after starting the observation.
3. I had to implement a special case for FLAMINGOS-2, because its countdown does not count down the exposition, but the whole observe command.
=> Several countdown fixes

modules/acm/src/main/java/edu/gemini/epics/acm/CaApplySenderImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala
New Seqexec was not producing the error message that the old one was causing when trying to use an obsolete filter in FLAMINGOS2. The root of the issue was in the instrument, but I still put some checks in Seqexec to reject the obsolete filters.
=> SEQNG-830 Better handling of obsolete FLAMINGOS2 filters

modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriController.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriHeader.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
Seqexec Server is now able to read NIRI sequences and run them in simulation mode.
Still missing:
- EPICS code
- Show NIRI sequences in client
- FITS headers
=> First implementation of NIRI support

modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOST.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOSTController.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala
Hi all,
Here is my refactoring of the `GHOSTConfig` into more type-safe classes.
NOTE that it currently won't pass test cases and I'm hoping someone can give me some direction.
It's still inevitable that we have to check what fields come from the OT to determine asterism type (unless we change the OT), so I check the IFU coordinates and create the appropriate GHOST mode based on that.
Since I've divided up `GHOSTConfig` into a hierarchy of modes, I had to change the `Gen` / `Arbitrary` for `GHOSTConfig` and its subclasses. Now I'm having trouble with the `GhostSpec` and while I think I have a vague understanding of why this error is happening, I'm not sure how to solve it in the best way.
The error is in the `checkAll` in `GhostSpec`: …
=> SEQNG-788: GHOST Configuration

modules/seqexec/server/src/main/resources/Gmos.xml, modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
There was an issue with the check to decide if the GNIRS bias had to be reapplied. The value read from the instrument has the opposite sign.
I got a bit sidetracked. I moved the GNIRS function to check parameters before applying them, to `EpicsUtil`, and changed the GMOS code to use it. That is in the first commit.
=> SEQNG-818 Fixed GNIRS bias check

modules/seqexec/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
`SeqexecEngine` is a fairly large class at the core of the seqexec. This PR splits a part of it, the part reading the ODB queue to simplify things
=> Refactor SeqexecEngine extracting the odb loading functions

.gitignore, modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala, modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/GiapiInstrumentController.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SubsystemControlCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ConditionsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/LoadedSequencesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OpenConnectionHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/RemoteRequestsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/SequenceExecutionHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/UserLoginHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/WebSocketHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/handlers.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
Mechanical refactoring of places where `Functor.as` or `Functor.void` can be used instead of `map`
=> Functor.as/void

modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala
We have to keep tabs when they are completed on the client while they are removed on the server. The last PR broke that but this PR restores that functionality
=> Fix to keep completed tabs

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/TableContainer.scala
The table container should not be reusable, or at least it should consider all vals to do so
=> SEQNG-844: UI not being updated properly after step completes

modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala
This is a tiny bug, if an obs is in preview but it is removed from the odb queue it remains in preview. This PR will remove it from the UI
=> SEQNG-458 Clean the preview tab if removed from the odb queue

build.sbt, modules/giapi/src/main/scala/giapi/client/GiapiDb.scala, modules/giapi/src/main/scala/giapi/client/GiapiStatusDb.scala, modules/giapi/src/main/scala/giapi/client/ghost/GhostClient.scala, modules/giapi/src/main/scala/giapi/client/gpi/GpiClient.scala, modules/giapi/src/main/scala/giapi/client/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/Settings.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
This is the first part of SEQNG-630. In this task we want to create an in memory db that track status item values. In the second part we'll want to use those value to decide if we really need to configure the instrument or not
This task let me learn quite a bit of `cats-effect` but I'm probably making some mistakes. @tpolecat I'd appreciate if we reviewed it
The creation of the db is fairly straightforward but the integration with `GpiClient` and with the rest of the seqexec involved some challenges. Some are commented inline
This PR doesn't change the functionality and it has been tested against GPI
=> SEQNG-630A: Don't send apply if the config won't change

modules/giapi/src/main/scala/giapi/client/GiapiStatusDb.scala, modules/giapi/src/main/scala/giapi/client/gpi/GpiClient.scala, modules/giapi/src/main/scala/giapi/client/package.scala
This is the next step of SEQNG-630. We need to initialize the status db on startup otherwise we only get values when the items change
=> SEQNG-630B: Initialize the db upon startup

modules/giapi/src/main/scala/giapi/client/GiapiConfig.scala, modules/giapi/src/main/scala/giapi/client/ghost/GhostClient.scala, modules/giapi/src/main/scala/giapi/client/gpi/GpiClient.scala, modules/giapi/src/main/scala/giapi/client/package.scala, modules/giapi/src/main/scala/giapi/client/syntax/giapiconfig.scala, modules/giapi/src/test/scala/giapi/client/GiapiArbitraries.scala, modules/giapi/src/test/scala/giapi/client/GiapiCommandSpec.scala, modules/giapi/src/test/scala/giapi/client/GiapiStatusSpec.scala, modules/main/src/main/scala/MainServer.scala, modules/seqexec/server/src/main/scala/seqexec/server/GiapiInstrumentController.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/GhostController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiController.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala, modules/telnetd/src/main/scala/gem/telnetd/TelnetServer.scala, modules/web/src/main/scala/gem/web/WebServer.scala, project/Settings.scala
This PR remove usages of `ExecutionContext` by `Timer[IO]` simplifying parts of the giapi code.
I also move some methods of `GiapicConfig` to the companion object
=> Timer implicit and GiapiConfig

modules/seqexec/web/server/src/main/resources/logback.xml
AsyncHttpClient emits lots of info to debug polluting the logs. This PR limits logs to INFO or above
=> SEQNG-867: Reduce verbosity of AsyncHttpClient

build.sbt, modules/seqexec/server/src/main/scala/seqexec/server/GiapiInstrumentController.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/GhostController.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/GhostHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/GdsClient.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/Header.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/ObsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/StandardHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsKeywordReader.scala
This PR converts a big chunk of the code related to keywords to tagless final encoding.
It started with one line change that cascaded through a bunch of code
Ideally we'd change `SeqActionF[F, A]` for `F[A]` but that is a much bigger change
=> Convert some of the keyword collection to tagless final encoding

modules/seqexec/model/src/main/scala/seqexec/model/Notification.scala, modules/seqexec/model/src/main/scala/seqexec/model/enum/SingleActionOp.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/QueueOperationsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/RemoteRequestsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala
This PR supports showing errors when configuring a single resource:
=> SEQNG-823 Properly display single resource configuration errors

modules/seqexec/web/server/src/main/resources/logback.xml
There is still some unnecessary logging from the async client
=> Further reduce logging from the async client

modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriKeywordReader.scala
The method name `toSeqAction` is a bit misleading as it not only converts a value to `SeqAction` but also defaults if the value is empty
This confused me quite a bit so I'm proposing to rename it
=> Rename toSeqAction to toSeqActionDefault

modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/GhostHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/DhsClient.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/DhsClientHttp.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/GdsClient.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/Header.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/StandardHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/keywords/DhsClientSimSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/keywords/GdsClientSpec.scala
This is a largish PR that (hopefully) simplifies the Headers using `F[A]` rather than `SeqActionF[F, A]`. There are some tricky business related to error handling but I think this preserves the current semantics
Some notes:
* This has been thoroughly tested with GPI and the behaviour is correct
* I could have changed the existing `KeywordReaders` but i didn't want to make more noise
* NifsHeader will however use the new style
@jluhrs Should we test this with the DHS?
=> Header tagless style

modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsController.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriController.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerSim.scala
In `InstrumentSystem` the method `calcObserveTime` should IMHO return an `F[Time]`. This because for some instruments, in particular Niri and apprently Nifs we need to read an epics channel to calculate the observe time
Doing it this way respects referential transparency
=> calcTotalExposureTime should be referentially transparent

modules/core/shared/src/main/scala/gem/config/DynamicConfig.scala, modules/core/shared/src/main/scala/gem/config/GmosConfig.scala, modules/core/shared/src/main/scala/gem/config/StaticConfig.scala, modules/core/shared/src/test/scala/gem/arb/ArbTime.scala, modules/core/shared/src/test/scala/gem/config/Arbitraries.scala, modules/core/shared/src/test/scala/gem/config/DynamicConfigSpec.scala, modules/core/shared/src/test/scala/gem/config/GmosConfigSpec.scala, modules/core/shared/src/test/scala/gem/config/StaticConfigSpec.scala
This PR adds lenses to GMOS config, both static and dynamic.  Ultimately the goal is to use these lenses to simplify sequence generation but I'll need a few more lenses/prisms in `Step` to get there. A few questions that I anticipate:
* Why write them out manually instead of using `@Lenses` or `GenLens`?
I'm not married to this but I thought I'd try it when @tpolecat mentioned he preferred it that way.  Because I wrote them out manually, I felt obligated to write out the tests as well which revealed missing `Eq`, `Order`, `Arbitrary`, and `Cogen` instances and a problem with arbitrary `Duration`.  So that seemed worthwhile in the end.
* Why not use the weathervane operators like `^|->`?
I don't like them and can't remember them.  `composeLens` seems a lot clearer to me.  If there is a …
=> Added GMOS config lenses

modules/core/shared/src/main/scala/gem/config/GcalConfig.scala, modules/core/shared/src/main/scala/gem/config/TelescopeConfig.scala, modules/core/shared/src/test/scala/gem/Arbitraries.scala, modules/core/shared/src/test/scala/gem/arb/ArbCoAdds.scala, modules/core/shared/src/test/scala/gem/arb/ArbGcalConfig.scala, modules/core/shared/src/test/scala/gem/arb/ArbStep.scala, modules/core/shared/src/test/scala/gem/arb/ArbTelescopeConfig.scala, modules/core/shared/src/test/scala/gem/config/Arbitraries.scala, modules/core/shared/src/test/scala/gem/config/GcalConfigSpec.scala, modules/core/shared/src/test/scala/gem/config/TelescopeConfigSpec.scala, modules/json/src/test/scala/gem/json/instances/CoAddsJsonSpec.scala, modules/json/src/test/scala/gem/json/instances/GcalConfigJsonSpec.scala
Adds lenses for `GcalConfig` and `TelescopeConfig` along with a few `Eq` and one `Order` instance. Along the way I'm moving stuff out of `gem.Arbitraries` and `gem.config.Arbitraries` in favor of specific instances in `gem.arb`.
=> More config lenses

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala
Tiny bug fix. Show system buttons after an error
=> SEQNG-890: Show system buttons after an error

modules/core/shared/src/main/scala/gem/Step.scala, modules/core/shared/src/main/scala/gem/config/DynamicConfig.scala, modules/core/shared/src/test/scala/gem/StepSpec.scala, modules/core/shared/src/test/scala/gem/arb/ArbFlamingos2.scala, modules/core/shared/src/test/scala/gem/arb/ArbGnirs.scala, modules/core/shared/src/test/scala/gem/arb/ArbStep.scala, modules/core/shared/src/test/scala/gem/config/F2ConfigSpec.scala, modules/core/shared/src/test/scala/gem/config/GnirsConfigSpec.scala
This PR adds some Lenses, Prisms, and `Eq` instances for `Step` and its friends.  For context, in order to do sequence generation I’ll need to set up a `Step.GmosN` (for example) and then modify it repeatedly to form a sequence.  Doing it without all of the optics I’ve now added was going to be brutal.
Nevertheless I can’t help but feel I’ve driven into a ditch in this one.  I’ll point out a few specific concerns in comments.
=> Step Lenses

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala
The message of a step should be the step state rather than the sequence. This leads to erroneous error messages
=> SEQNG-902 Show the step state msg rather that the sequence step

app/seqexec-server-gn/src/main/resources/app.conf, app/seqexec-server/src/main/resources/app.conf, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
We need to let the TCC call the guide route over http
=> SEQNG-912: Support access to the guide route over plain http

modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
The default timeout for the http client is 60s which is too long for example when connecting to the DHS. This reduces the timeout to 5s but the actual amount is subject to testing
=> SEQNG-907 Use a shorter request timeout for the http client

modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
Though GNIRS exposes a channel with the time left for an exposition in practice it is always 0
Thus we need to simulate the progress
=> SEQNG-909 Simulate gnirs progress bar

modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala
Telescope offset must be applied to all beam positions. Otherwise TCS will complain if the difference between beam positions is too big, even if chopping is not used.
=> SEQNG-933 Fixed issue with sky offsets.

modules/acm/src/main/java/edu/gemini/epics/acm/CaWindowStabilizer.java, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
The problem was that the in position value was filtered to remove spurious changes. That introduces a delay in the changes (the input has to be stable for XX seconds before the output changes). The problem is that when Seqexec checked the filtered value, it had not yet changed to "false" because of that delay.
=> SEQNG-934 Fixed issue with TCS in position

modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala
Seqexec left the TCS in an unrecoverable state after enabling guiding. The issue is that it was enabling guiding for beam C, but neither the TCC nor the TCS dm screens consider that option. The end result was that TCC would not turn off the beam C guiding when changing guiders, which resulted in TCS complaining because the previous guider was left as still in use.
=> SEQNG-937 Don't enable beam C guiding.

modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriKeywordReader.scala
Easy one. The value for the NIRI keyword EXPTIME must be the sum of two values read from the instrument.
=> SEQNG-896 Fixed calculation of EXPTIME for NIRI.

build/buildkite-build.sh
This disables the docker image / deploy step for now since it leaks images sometimes and we're not using it and our deployment strategy is up in the air right now.
=> disable image/deploy step

modules/acm/src/main/java/edu/gemini/epics/acm/CaWindowStabilizer.java, modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairController.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala, modules/seqexec/server/src/test/scala/seqexec/server/tcs/GuideConfigDbSpec.scala
* Predicting the next AO target position before applying an offset requires to know the current value but retrieving it at each step is unreliable. Instead, now TCC captures the position when the Altair is enabled, and passes it to Seqexec.
* Fixed a bug where Altair was not enabled if was not disabled in the same step (it would fail to restart after an unguided step)
* In Altair, check the current status to decide if it necessary to send a command.
* Fixed some typos in the code the retrieves the current P2 and OI configuration from TCS.
=> SEQNG-939 First batch of Altair bugfixes

modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/ScienceFoldPositionCodex.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala, modules/seqexec/server/src/test/scala/seqexec/server/tcs/ScienceFoldPositionCodexSpec.scala
Reading of the science fold position would sometimes cause an error. It is OK if the error was that it couldn't read an EPICS channel, but in most cases, the error was caused because it could not transform the read position into a certain type, which is not OK. The type used was designed to represent positions that make sense for a given observation, but missed other posible values of the science fold position.
The solution introduces a new type to represent the real science fold position.
=> SEQNG-925 Fixed reading of current SF position.

modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala
Probes follow demands depending on two settings. The nod/chop guide configuration tells TCS when to send demands to the probes. The follow state tells the probe to follow such demands. When a big offset is applied, probes are frozen: they stay in their last position, and don't move. In this case, Seqexec was setting all nod/chop values to Off, and follow to Off. The last one was unnecessary, but also should have been inocuos. It ended up that it was causing problems with OIWFS, so I changed the code to not turn follow Off when freezing a probe (which is the behavior of the Tcl Seqexec)
=> SEQNG-942 Keep frozen probes in following state.

build.sbt, modules/acm/src/main/java/edu/gemini/epics/acm/CaApplyRecord.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/acm/src/test/scala/edu/gemini/epics/acm/ObserveStateSpec.scala, project/Settings.scala
There is a report of NIRI observations not working after the last updates
This PR adds unit tests to reproduce the issue and tests for NIFS and GMOS. This was a fix can be done without having regressions
These tests require epics but for speed sake the epics layer has been mocked using ScalaMock
=> SEQNG-922A: Unit test for the observation state machine

modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/acm/src/test/scala/edu/gemini/epics/acm/ObserveStateSpec.scala
NIRI's observations aren't running properly after the last change to the ACM's state machine. This should fix it by handling the case where apply val changes after the clid
=> SEQNG-922: Support NIRI's way to run observations

modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
It would be useful to do a sync of the sequence when it is loaded. This way you get a fresh representation of the sequence
This PR does that on the backend
=> SEQNG-697: Sync the sequence when loading

modules/seqexec/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala, modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
We've seen several times the session queue being empty. Some experiments demonstrate that if there is an exception when reading the odb sequences the stream that polls the odb dies. In that case the seqexec keeps running but there are no sequences
I want that if this happens (some error on the odb reading process) happens we log and kill the seqexec. While it may seem drastic it will ensure we fix any problems and note it right away
I tried to make the code exit gracefully but a `cats-effect` bug https://github.com/typelevel/cats-effect/issues/487 makes it harder, having to resort to `sys.exit`. When the bug is fixed this can be revisited
=> SEQNG-928: Protect reading odb observations

modules/seqexec/server/src/main/scala/seqexec/server/InstrumentGuide.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala, modules/seqexec/server/src/test/scala/seqexec/server/tcs/TcsControllerEpicsSpec.scala
Offsets can be applied without interrupting guiding if they are small enough. This PR implements that, and makes the decision threshold depend on the guider used.
=> SEQNG-944 Use guider dependent threshold for guiding while offsetting.

modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala
This is to fix a bug where Seqexec was enabling guiding for the AO target in TCS, even for Altair modes without a guide target.
=> SEQNG-948 Only enable AO target guide on relevant Altair modes.

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SubsystemControlCell.scala
This is a small bug fix. The subsystem buttons should be sorted consistently
Before:
After:
=> SEQNG-952 Consistently sort the subsystems

modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala, modules/seqexec/model/src/main/scala/seqexec/model/events.scala, modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/SequenceDisplayHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala
The action buttons on the UI are disabled while an action is happening. they should be enabled when an action completes but there are a few edge cases where it isn't happening
This PR fixes several of them
=> SEQNG-950 Handle several border cases enabling action buttons on them

modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/StepsTableFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
The steps table shows the running subsystems buttons when the user selects a row. However when a sequence is running the selection is not updated. This is clearer when you pause in a breakpoint, there the sequence stops but the next step to be executed is not selected and the subsystems button doesn't show up until you click
this PR tracks the running sequence and updates thus showing the subsystem buttons right away:
=> SEQNG-963: Smarter selection of the next step

app/seqexec-server/src/main/resources/update_smartgcal, build.sbt, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SmartGcalRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
We have noted that smartgcal updates, every 1h, may interfere with sequence execution. Besides, the data doesn't change often enough to need this frequent updates
This PR removes this auto update and adds an http endpoint to manually trigger the update
A cronjob will be setup on the seqexec hosts to daily update smartgcal files during the day giving the options for users to manually trigger if needed
=> SEQNG-903: Update smartgcal less often

modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
This PR modifies the back end to provide the ability to start a sequence from an arbitrary step. This is a feature already present in the old Tcl Seqexec. The implementation uses existing features. It marks all steps preceding the selected one as to be skipped (excluding already completed steps), and then runs the sequence.
=> SEQNG-124 Sequences can be started from arbitrary step.

modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
Turns out chrome needs the responseType unlike FF
=> SEQNG-976: Fix bug doing login in chrome

modules/seqexec/server/src/main/scala/seqexec/server/ConfigUtilOps.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/reusability/package.scala
Since anything can be stored on the mode sometimes we get weird objects from ocs2 `Some/None` types
This PR fixes this and also does a fix for F2 filters
After the fix we get:
=> SEQNG-967: Step configuration shows wrong values for optional parameters 

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTools.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SubsystemControlCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/TabOperations.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
This PR changes the color of the subsystem buttons in an observation step, using:
- Blue: Idle / not configured.
- Yellow: Configuring.
- Green: Configured.
This is done by introducing a new state for subsystem configuration, namely `ResourceRunComplete`.
One thing I'm not entirely happy about is that when the table is first loaded, the map of resources to steps is an empty map; after that point, it becomes populated, and resources are moved to `ResourceRunIdle`.
One thought, given that I don't think we want to assume what resources are going to be used in advance: we use `Map.empty.withDefaultValue(ResourceRunOperation.ResourceRunIdle)` for the resource state map in `TabOperations.Default`. The issue with this is that the return from `SortedMap.withDefaultValue` is a `Map` instead of a …
=> SEQNG-911: Subsystem button colors

modules/acm/src/main/java/edu/gemini/epics/acm/ApplySenderWithResource.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaApplySenderImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaCommandSenderImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaResource.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaService.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaSimpleObserveSenderImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaStatusAcceptorImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaTaskControlImpl.java, modules/acm/src/test/scala/edu/gemini/epics/acm/ObserveStateSpec.scala, modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/gsaoi/DhsConnected.java, modules/seqexec/server/src/main/resources/Gsaoi.xml, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiEpics.scala, modules/seqexec/web/server/src/main/resources/app.conf
I had to create a specialized version of `CaObserveSenderImpl` for GSAOI, called `CaSimpleObserveSenderImpl`. It is actually simpler, because it does not use two CAR records, but only one.
When writing the tests for `CaSimpleObserveSenderImpl` I found a bug in `CaObserveSenderImpl`, and another in the tests that hid the bug in `CaObserveSenderImpl`. They will be fixed in SEQNG-978
=> SEQNG-959 Implemented GSAOI Epics code.

build.sbt, modules/acm/src/main/java/edu/gemini/epics/acm/CaApplyRecord.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaApplySenderImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaCarRecord.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaService.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaSimpleObserveSenderImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CadDirective.java, modules/acm/src/main/java/edu/gemini/epics/acm/SafeExecutor.java, modules/acm/src/test/scala/edu/gemini/epics/acm/ObserveStateSpec.scala
This PR includes several changes to the epics code to handle observations:
* Epics channels can be mocked using `EpicsReader` and `EpicsWriter` rather than `EpicsService`. This way we can test the listeners and avoid certain failures
* Failures to write to DIR are properly handled
* GSAOI ignored tests are now enabled
* GSAOI abort properly ends on failure
* the executors used on the the classes handling state changes will caught exceptions. This should help to debug exceptional situations not yet considered
=> SEQNG-978: ObserveStateSpec rework and fix for ignoring fixes to write DIR

modules/shared/web/server/src/test/scala/web/server/common/StaticRoutesSpec.scala, project/Settings.scala
Http4s 0.20.0 has been released. Note that we are still using the async client
=> Upgrade http4s and other libraries

modules/seqexec/engine/src/main/scala/seqexec/engine/Event.scala, modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala, modules/seqexec/model/src/main/scala/seqexec/model/RunningStep.scala, modules/seqexec/model/src/main/scala/seqexec/model/SequenceView.scala, modules/seqexec/model/src/main/scala/seqexec/model/events.scala, modules/seqexec/model/src/test/scala/seqexec/model/ModelSpec.scala, modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/model/src/test/scala/seqexec/model/arb/ArbRunningStep.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SessionQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/SequenceTab.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/InitialSyncHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ObservationsProgressStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ModelSpec.scala
At the moment you can select step x and if you execute run on a previous step you end up with an odd situation where the run subsystem buttons are available though the sequence is running as:
This PR fixes that removing the step selection in this case. Additionally we forbid step selection while a sequence is running
=> SEQNG-979 Better handling of step selection when a sequence is running

modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Epics.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriKeywordReader.scala
We should do all epics reads in a referentially transparent way. Some instruments are already doing that but we should port the others. This is a largish task so I'm doing a part here, porting F2 and NIRI
Note there are plenty of opportunities for further refactoring but I'm trying to make smallish PRs
=> SENG-887A: Make Epics reads referentially transparent

modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/RemoteRequestsHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala
There are some discrepancies across multiple clients when a resource is executed. this PR fixes two things:
* If a resource in step x is executed the state of execution is reflected in all clients
* If a second client has selected another step y and step x is executed at the first client, the step being executed is selected in all clients
=> SEQNG-821 Synchronize resource execution across clients

modules/seqexec/server/src/main/scala/seqexec/server/EpicsHealth.scala, modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecFailure.scala, modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerSpec.scala
Another PR to make GWS do reads as referential reads inside an `F[_]`
There is a bigger change in this PR, we normally return things like `F[Option[A]]` acknowledging that Epics reads can return null. We could simplify this code a bit doing reads as `F[A]` taking care of checking of nulls and raising an error
If this style seems appropriate we could refactor the other classes as well
=> SEQNG-877C: Convert GWS to do epics reads inside an effect

modules/seqexec/model/src/main/scala/seqexec/model/Step.scala, modules/seqexec/model/src/main/scala/seqexec/model/StepState.scala, modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala, modules/seqexec/model/src/test/scala/seqexec/model/arb/ArbStepState.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
This bug slipped through on the last large refactoring leading to some situations where the steps table didn't update when it should
=> SEQNG-998 Properly decide when the status step has changed for redrawing the UI

modules/core/shared/src/main/scala/gem/enum/GiapiStatusApply.scala, modules/giapi/src/main/scala/giapi/client/gpi/GpiClient.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/StepType.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiStatusApply.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsKeywordReader.scala, modules/seqexec/server/src/test/scala/seqexec/server/gpi/GpiArbitraries.scala, modules/seqexec/server/src/test/scala/seqexec/server/gpi/GpiSpec.scala, modules/sql/src/main/resources/db/migration/V071__Gpi_Align_And_Calib.sql
This PR adds support for GPI Align And Calib. 
It supports the current mode of operation where you have a special sequence with a calibration and A&C, but it also supports a mode where all the steps are in one sequence:
This mode could eventually simplify night time operations but needs testing
There is still work on UI and actual testing but the core functionality is done in this PR
=> SEQNG-993/994: GPI Align & Calib

modules/seqexec/model/src/main/scala/seqexec/model/enum/Resource.scala, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/TabFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/SeqexecTabs.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/SequenceTab.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/TabOperations.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/icon/Icon.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/label/Label.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
When a system is active in another tab we want to show it to the other tabs
This PR adds little icons to the tabs as shown below:
=> SEQNG-824: Display icons on the tab while a subsystem is active

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecUI.scala
This is a small bug fix. Seqexec urls should be navigable. If you go to
http://localhost:9090/preview/GNIRS/GS-2019B-Q-30-2/step/1 it should jump to that
However urls without the step are ignored
This PR fixes that supporting urls like
http://localhost:9090/preview/GNIRS/GS-2019B-Q-30-2
=> SEQNG-1001 Improved navigation for sequences' urls without a step

modules/seqexec/model/src/main/scala/seqexec/model/events.scala, modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/WebSocketFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OpenConnectionHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecAppRootModel.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
As the Seqexec UI often runs for a long time, when a new version is released old clients may remain using the old client requiring a user reload
This PR sends the version to the client. If the client detects a version change it will self reload
=> SEQNG-975: Auto reload the client ui if the server version changes

modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/ObsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/StandardHeader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala
This is (i think) the last Pr to reform the keyword header readers. There will be a last PR cleaning up some unused code.
This PR changes `ObsKeywordReader` which gathers data from the ODB. I'm treating ODB reads as potentially dangerous coming from Java although it is mostly memory reads
Along the process a bug was found where the keywords for MAXAIRMASS are not properly read. Testing on instrument show them missing
=> SEQNG-887/SEQNG-1004: Refactor StandardKeywordHeader and a bug fix

modules/acm/src/main/java/edu/gemini/epics/acm/CaCommandMonitor.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaCommandMonitorImpl.java, modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java, modules/acm/src/test/scala/edu/gemini/epics/acm/ObserveStateSpec.scala
Sometimes during a GNIRS observation, the event of the main DC apply record going BUSY is not received (or is not generated by the instrument?), causing Seqexec to wait forever for it (ending in a timeout). This PR fixes it. It also adds tests cases for GNIRS, and factors some of the test code.
=> SEQNG-974 Fix for GNIRS observe.

build.sbt, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SessionQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, project/Settings.scala
We had for a while the ability of the table to autoscroll when a sequence was running. it was lost in one of the refactorings and due to bugs on the upstream libraries
With the latest `react-virtualized` release we can restore it.
With this PR once you press run the sequence will jump to the next step to run and track the running step:
If we were out of view the table will jump to the running step
If the user scrolls independently care is taken to avoid jumping back to the next step as that is likely confusing
=> SEQNG-245: Restore autoscrolling to the steps table

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/CalQueueFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/CalQueueSeq.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SessionQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala
When a day cal is running there is no display of exactly what is running. They are shown on the session queue table but not on day cal
This PR improves that:
=> SEQNG-777: Display sequences state on the day cal table

modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala
On SEQNG-821 We started showing the state of common resources (tcs, gcal) on the tab. There is a bug with respect to clients not doing the configuration:
This PR fixes it
=> SEQNG-1006 Reset execution state on the proper place

modules/seqexec/server/src/main/scala/seqexec/server/keywords/ObsKeywordReader.scala
Fixes a bug that slipped on a refactoring. Properly read the datalabel from the sequence config
=> SEQNG-1009: Invalid data label

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala
Small bugfix. Under some circumstances the `runFrom` button may show up even when the user is logged off. This is harmless as the server rejects unauthenticated requests but still it should be rather not be available
=> Ensures runFrom button is hidden if user is logged off

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
Executed bugs are not displayed properly as in this screenshot:
This PR fixes it and also will gray out executed steps with breakpoints:
=> SEQNG-1013 Fixes a bug displaying executed breakpoints

modules/seqexec/model/src/main/scala/seqexec/model/enum/M1Source.scala, modules/seqexec/model/src/main/scala/seqexec/model/enum/TipTiltSource.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/WebSocketFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/ConnectionState.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/ControlMenu.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/Footer.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/FooterStatus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/GuideConfigStatus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecAppRootModel.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/reusability/package.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
With this PR we display the guide configuration at the page's footer
e.g: no guiding
all enabled
Some other combinations
=> SEQNG-986 Display the guide config info on the footer

modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorthControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouthControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerEpics.scala
Gmos is the last instrument to get the treatment of SEQNG-887. This is a largish update and it would be good to be reviewed in detail and test it on hardware
Main changes are:
* Put all epics reads inside an `F[_]`
* Reform on the way the decision to apply a param is done. Now we take a full snapshot of the instrument state and use that to decide
There is space for further improvements but I'm trying to keep this constrained on the change size and time invested
=> SEQNG-887: Make epics reads for GMOS referentially transparent

modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Epics.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsKeywordReader.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerSpec.scala
I've been doing this large refactoring to make all epics reads referentially transparent. While some improvements can still be done we should close this
This PR removes some duplicated code that was able to work on the old and new world and rename `EpicsCommandF` to `EpicsCommand` and `ObsecveCommandF` to `ObserveCommand`
As changes go this PR is fairly mechanical
=> SEQNG-887: Final touches on SEQNG-887

modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala
This PR contains three bug fixes
* First we need to pass the `TcsEpics` items per ref as the initialization logic is handled in another place of the app. This is not an issue in production but affects us in simulation. The fix in the current PR is a workaround until we have a better fix
* Two gmos channels were being read as int while they are doubles
* During testing I noted that N&S guidingWithBeam can come on the sequences as a String or as `StandardGuideOptions.Value`
=> Small bug fixes

modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala
I noted a small bug while testing. If you start a sequences from a step using the start from button, the observation control buttons are disabled:
The issue was setting the wrong state when `RunFrom` completes
=> SEQNG-1024 Properly mark start from operation as complete

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SubsystemControlCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/SequenceTab.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/TabOperations.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ModelSpec.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/arb/ArbTabOperations.scala
This is the first PR to properly show A&C. This is the minimum which is to display that we are running A&C but a next PR will show the steps while doing so
While doing this PR I noted that subsystem failures were not properly displayed. That fix accounts for a big part of the size of this PR, but benefits all instruments
=> SEQNG-995A: Display A&C name while executing

modules/giapi/src/main/scala/giapi/client/GiapiDb.scala, modules/giapi/src/main/scala/giapi/client/GiapiStatusDb.scala, modules/seqexec/model/src/main/scala/seqexec/model/Step.scala, modules/seqexec/model/src/main/scala/seqexec/model/events.scala, modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/WebSocketFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/AlignAndCalibProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepBreakStopCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTools.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/AlignAndCalibStep.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecAppRootModel.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/StepItems.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ModelSpec.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala, modules/seqexec/web/server/src/test/scala/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala, modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala, modules/seqexec/web/shared/src/test/scala/seqexec/web/model/boopickle/ModelBooPicklersSpec.scala
Align and calib is a slow action but the instrument provides status as it progresses. This PR changes the UI to handle this case. It will expand a row with A&C and show the steps along a progress bar to provide feedback
The code is not too explanatory, so I'm attaching a video (It is recorded at 4x to make it more interesting). The video was recorded running with the actual hardware. There are a few minor cosmetic changes in the latest version but the core is the same. 
https://www.dropbox.com/s/vjh1q6buuv56vb9/acscreencast.mp4?dl=0
This same technique will be applied for Nod & Shuffle
=> SEQNG-995B: Show the substeps of align and calib

modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Step.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala, modules/seqexec/model/src/main/scala/seqexec/model/Step.scala, modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/seqexec/server/src/main/scala/seqexec/server/ObserveActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/StepType.scala, modules/seqexec/server/src/main/scala/seqexec/server/System.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/Gcal.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/Gsaoi.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouth.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
This is a last refactoring to remove the usage of monad transformers preferring `F[A]` over `EitherT[F, Throwable, A]`
This seems to simplify the code quite a bit at the expense of requiring care to handle all errors at the appropriate places
This was tested on instrument (GPI) and in simulation in several scenarios. The change is very transparent for regular operations but it is bigger to handle exceptional cases
=> SEQNG-331 Further refactorings

modules/seqexec/server/src/main/scala/seqexec/server/InstrumentControllerSim.scala, modules/seqexec/server/src/test/scala/seqexec/server/InstrumentControllerSimSpec.scala
This is a relatively small refactor of the instrument simulator. Mostly came out about me trying to understand it
Changes are mostly about making it more configurable, remove `Thread.sleep` calls and more importantly a unit test
There is also a small bugfix about the pause/resume
=> Refactor instrument simulator

modules/seqexec/server/src/main/resources/Tcs.xml, modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairController.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gems/Gems.scala, modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsController.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/Gaos.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouth.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthController.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala, modules/seqexec/server/src/test/scala/seqexec/server/tcs/GuideConfigDbSpec.scala
This PR is limited to applying the tracking configuration of GeMS guiders (nod/chop and follow state). There is a lot left to do, like the notifications to GeMS of guide changes, and starting/stopping the guiders.
One small complication is that all the settings go through TCS. But in most cases it does not have a dedicated CAR for every possible GeMS guider. Instead, because only 4 can be used at a time, TCS defines 4 virtual telescopes for GeMS (G1 to G4), and a mapping to the actual guiders.
=> SEQNG-1028 Apply GeMS guiders tracking configuration.

modules/core/shared/src/main/scala/gem/enum/GiapiStatusApply.scala, modules/core/shared/src/main/scala/gem/enum/GpiReadMode.scala, modules/core/shared/src/main/scala/gem/enum/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/ConfigUtilOps.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiHeader.scala, modules/seqexec/server/src/test/scala/seqexec/server/gpi/GpiArbitraries.scala, modules/sql/src/main/resources/db/migration/V073__Gpi_ReadMode.sql, modules/sql/src/main/scala/gem/sql/enum/GpiEnums.scala
The sample mode for GPI is a parameter on the odb that cannot be edited and or all intents it is always UTR. However, it is still possible using the engineering to set it to some of the other values. Normally the value would be set automatically when doing an observation but in a rare case, doing a calibration may not set it and if combined with manual changes could produce FR-40693 where the readout mode was set to Single.
This PR will read the value from the ODB, compare it to the actual value and set it on the instrument if needed
Another set of parameters in the same category are the readout area. While there hasn't been a case of using a subarray ever, it is still possible to be set using the engineering level tools. Thus the readout area params receive the same treatment
This PR …
=> SEQNG-1034: GPI Wrong Sample mode

modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
The seqexec banner was not being displayed at the start of the logs. It probably was missed in some refactoring. This PR restores it
=> Restore start banner

modules/seqexec/server/src/main/scala/seqexec/server/CleanConfig.scala, modules/seqexec/server/src/main/scala/seqexec/server/ConfigUtilOps.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/seqexec/server/src/main/scala/seqexec/server/ObserveEnvironment.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SequenceConfiguration.scala, modules/seqexec/server/src/main/scala/seqexec/server/System.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/Gcal.scala, modules/seqexec/server/src/main/scala/seqexec/server/gems/Gems.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/Gsaoi.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/ObsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouth.scala, modules/seqexec/server/src/test/scala/seqexec/server/CleanConfigSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/ConfigUtilSpec.scala
Flats, arcs and biases steps inserted in a N&S sequence have N&S parameters that the Seqexec might try to apply. This is not supported, and the old Seqexec deals with them by treating them as no N&S steps.
I tried different approaches, like trying to cancel the effects of the N&S parameters everywhere they are used, but at the end I went for the simpler solution of fixing the step configuration by overriding the `useNS` parameter. The class used to read the step configuration is a mutable Java class (`Config`). To avoid mutation I built a wrapper, and passed it instead of the original `Config`.
=> SEQNG-1052 Transform N&S biases, flats and arcs into normal ones.

modules/seqexec/server/src/main/scala/seqexec/server/ObserveActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
Fixed bug where the notification send to the ODB to signal the start of the sequence execution was not using the dataId.
=> SEQNG-1055 Use dataId in call to sequenceStart.

modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiGuider.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/package.scala
The real GeMS code needs access to GSAOI statuses and commands. The issue was that it was using `GsaoiEpics.instance` even if Gsaoi was internally simulated (and therefore, `GsaoiEpics.instance` was not initialized). I opted for creating an interface for GeMS to access GSAOI functionality, one that is instantiated following the Gsaoi simulation parameter. Besides fixing the bug, this implementation has the advantage of allowing mixing real GeMS control with simulated GSAOI.
=> SEQNG-1040 Fixed issue with mixing real GeMS with simulated GSAOI.

modules/seqexec/server/src/main/scala/seqexec/server/InstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/package.scala
N&S with multiple cycles was not properly done, in part because of a misunderstanding  of the  `replicateA`, method. However the simple fix also showed some other issues which led to a larger rewrite.
N&S was originally done with multiple actions for each subexposure but instead it needs to be done with a single large action
More was discussed about this here:
https://gist.github.com/cquiroz/50ae3fe89711243a9f06a0515c257bad
The simulator also needed updates to support multiple cycles
=> SEQNG-1048 Fixes actions for N&S on multiple cycles

modules/db/src/main/scala/gem/dao/StaticConfigDao.scala, modules/db/src/main/scala/gem/dao/TargetEnvironmentDao.scala, modules/ephemeris/src/main/scala/gem/horizons/tcs/TcsEphemerisExport.scala, modules/seqexec/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala, modules/seqexec/server/src/main/scala/seqexec/server/ObserveActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerSim.scala, modules/telnetd/src/main/scala/gem/telnetd/command/SiteOpt.scala
I was playing around with [comby](https://comby.dev) and had it rewrite `map(f).sequence` → `traverse(f)` and `traverse(f).void` → `traverse_(f)`. 
It's really cool. Not as safe and flexible as ScalaFix but a hell of a lot easier.
=> simplifications

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- Reinstate (un)setting breakpoint by pressing middle button in Seqexec UI
- Don't disable auto scroll in the step table if the user scrolls manually
=> Seqexec small UI fixes

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/AlignAndCalibProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/OffsetDisplayCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/RunFromStep.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SequenceTabContent.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepBreakStopCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTools.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SubsystemControlCell.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/TabsArea.scala, modules/shared/web/client/src/main/scala/web/client/ReactProps.scala
This is a refactor to change the way in which components and their props are defined so that the call site code is simpler.
So far, all components in the `sequence/steps` package are refactored.
=> Simplify calling React components. `sequence/steps` components.

modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
GMOS Darks and Biases don't need to configure the CC. This change skips the CC configuration for those two observe types.
=> SEQNG-1068 Disabled GMOS CC configuration for Darks and Biases.

modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SmartGcalInitializer.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SmartGcalRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
While doing some other work I noted that the way we initialize the SmartGCal updater could be improved.
This PR does it in a separate step and ensure initialization is done before it can be invoked
=> Better initialization logic for smartgcal

modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorthControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouthControllerEpics.scala
This PR adds some fixes to successfully run N&S with epics, thanks @jluhrs 
The two main changes are
* Remove the call to set rows in between stages
* Handle the response of the observe pause differently if N&S
There are few other logger related changes
=> SEQNG-1072 Fixes to execute N&S in Epics

modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala
While testing I noted that one specific error (Retrieving the fileId) wasn't properly handled for N&S
This PR fixes this adding an extra obs handler. For all other observations this is done at the upper level but N&S has a slightly different structure
=> SEQNG-1071 Handle errors thrown during filedId reads for N&S

modules/seqexec/engine/src/main/scala/seqexec/engine/Action.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Execution.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Sequence.scala, modules/seqexec/model/src/main/scala/seqexec/model/NSSubexposure.scala, modules/seqexec/model/src/main/scala/seqexec/model/NodAndShuffleStatus.scala, modules/seqexec/model/src/main/scala/seqexec/model/enum/NSAction.scala, modules/seqexec/model/src/test/scala/seqexec/model/ModelSpec.scala, modules/seqexec/model/src/test/scala/seqexec/model/arb/ArbNSRunningState.scala, modules/seqexec/model/src/test/scala/seqexec/model/arb/ArbNSSubexposure.scala, modules/seqexec/model/src/test/scala/seqexec/model/arb/ArbNodAndShuffleStep.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/StepsView.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosStepView.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/NodAndShuffleState.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/partials.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala, modules/seqexec/web/shared/src/test/scala/seqexec/web/model/boopickle/ModelBooPicklersSpec.scala
This is the second part of sending N&S updates to the client. This PR adds a field to `NodAndShuffleStatus` containing the state of the current execution
There are some changes on the way N&S actions are structured to send events before and after each substage is produced
=> SEQNG-1069B Send to the client the state of running ns actions

modules/seqexec/model/src/main/scala/seqexec/model/GmosParameters.scala, modules/seqexec/server/src/main/resources/Gmos.xml, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala
GMOS detector controller can crash during an observation if the stop, abort or pause command are issued at the wrong time. This PR assures they are not.
=> SEQNG-906 GMOS stop, abort and pause allowed only if acquiring and with enough time left

build.sbt
When trying to do a release we found 2 issues 
Javadocs were attempted to be built but there is a problem with `@typeclass`
More complicated `sjs` jar files were now included and that created troubles with the log4s dependenecy
We should aim to remove that in favor of log4cats but http4s depends on log4s anyway
At the end it was down to sbt magic. I suspect the original source of this is 
https://github.com/gemini-hlsw/ocs3/commit/fcc665143b6e8402f840cb8bddbb6f12db366ffb
or 
https://github.com/gemini-hlsw/ocs3/commit/5beb16c0c8819fe6d101dfff6b69ad37999be126
=> SEQNG-1076 Fix building distributions

modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SequenceConfiguration.scala, modules/seqexec/server/src/main/scala/seqexec/server/StepType.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
GMOS is picky when it comes to taking darks and biases, so this PR turns the GCAL lamps off for them. A consequence is that GMOS darks and biases will prevent the execution of other calibrations in parallel, because they take control of GCAL.
=> SEQNG-1063 Turn off GCAL lamps for GMOS darks and biases.

modules/seqexec/model/src/main/scala/seqexec/model/Step.scala, modules/seqexec/model/src/main/scala/seqexec/model/operations.scala, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/DividedProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/AlignAndCalibProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ControlButtonResolver.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/NodAndShuffleProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressDisplay.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SmoothProgressBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/StepItems.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/reusability/package.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/progress/Progress.scala
Display cycle and subexposure progress for N&S steps in Seqexec UI, shown when a step is selected or running.
Also display graceful and immediate pause and stop buttons when the user is logged in and the step is running.
This PR integrates the changes from https://github.com/gemini-hlsw/ocs3/pull/1114 but not yet the ones from https://github.com/gemini-hlsw/ocs3/pull/1119 (no running state yet).
=> [SEQNG-333] Display of Nod and Shuffle Step

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/NodAndShuffleProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/reusability/package.scala
I undid the previous changes to the progress bar component and abstracted away the logic to compute the progress message, which is now shared with a specialized component to show it in N&S.
@cquiroz I'd appreciate your input on generalizing the standard and N&S step reusability instances without `config`.
=> [SEQNG-1078] N&S progress messages and total remaining time.

modules/seqexec/server/src/main/scala/seqexec/server/InstrumentControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/Settings.scala, modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/GdsClient.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerSim.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
Constructions of subsystems has been distributed across several places, web server and the seqexec engine. It also uses some unsafe actions. 
This PR tides this removing the `unsafe` calls and it puts the initialization of all systems in one place plus some other internal improvements
=> Improve construction of subsystems

modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala
Tests showed that e-offset wasn't being properly set with N&S.
This PR fixes it, the core reason was a badly read type from the ocs config
=> SEQNG-1088 Set electronic offset in between nods

modules/seqexec/server/src/main/scala/seqexec/server/ObserveActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
Paused observations commands were build from two pieces: a function that would send a command to the instrument and wait for a result, and a function that would process that result. The first function could be a continue, a stop or an abort, and it does not depend on the actual observation, only the instrument. The second function does depend on the observation, and was build at the moment the observation was paused.
This scheme covered all instruments, except for GMOS N&S. This PR changes that. Now, when the observation is paused, three functions are built: one to continue the observation, one to stop it, and one to abort it. For normal observations they are built the same way than before. When the user call for resuming, stopping or aborting the paused observation, the right function is …
=> SEQNG-1083 Refactored paused observation commands

modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
This is a small detailed noted while checking the old seqexec code.
We should set the beam as `OutOfBeam` if FPU is "None"
=> Set OutOfBeam if FPU is None

modules/seqexec/engine/src/main/scala/seqexec/engine/Sequence.scala, modules/seqexec/model/src/main/scala/seqexec/model/enum/ObserveCommandResult.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/seqexec/server/src/main/scala/seqexec/server/ObserveActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/Gsaoi.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
Implementation of the N&S interruption commands pause, pause gracefully, stop, stop gracefully, and abort.
This PR also includes the commands to resume, stop or abort a paused N&S observation.
The commands were tested sending HTTP commands with curl.
=> SEQNG-328 N&S interrupt commands

modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/AoFold.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/BasicEpicsTcsConfig.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideControl.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/ScienceFold.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/ScienceFoldPositionCodex.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigDecoders.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEncoders.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/package.scala, modules/seqexec/server/src/test/scala/seqexec/server/tcs/ScienceFoldPositionCodexSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/tcs/TcsControllerEpicsCommonSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/tcs/TcsNorthControllerEpicsAoSpec.scala
We have an objective to redo some of the Epics connections to make them more robust and reduce the need for restarts in cases where instruments are not available when booting.
This is hampered by the use of global variables like `TcsEpics.instance`. We have already ported some instrument code to instead have the epics instance passed as a variable and this PR does the same for the TCS
The PR is fairly large but the changes are mostly mechanical
* Move inner classes to top level
* Put al epics encoders/decoders on separate traits
* Make algebras for TcsConfigRetriever, TcsCommonEpicsController, TcsSouthControllerEpicsAo and TcsNorthControllerEpicsAo
* Abstract the effect type on tagless final style
* Use log4cats where appropriate
A next PR will do the same for the remaining instruments
=> Refactor of TCS Epics controllers

modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerSim.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorthControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouthControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala
This is the continuation of #1152 applied to instruments.
Same set of changes:
* Remove static calls to epics systems
* Convert to a tagless final encoding
* Use Logger where appropriate
=> Always pass the epics instances as build params

build.sbt, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/security/FreeLDAPAuthenticationService.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/security/HttpAuthenticator.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/security/TestAuthenticationService.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/security/authentication.scala, modules/seqexec/web/server/src/test/scala/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala, modules/seqexec/web/server/src/test/scala/seqexec/web/server/security/JWTTokensSpec.scala, modules/shared/web/server/src/main/scala/web/server/common/RedirectToHttpsRoutes.scala, project/Settings.scala
This PR revamps the auth code with the following improvements:
* Update to the latest jwt library
* Replace argonaut for circe
* Use tagless style
The code could have used a bit more improvements (Some bits were use to learn about free monads) but given time constraints I'll leave it as is
=> Tagless auth

modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala
After doing an pause immediately issue an observe pause rather than a stop pause. Thanks @jluhrs for pointing out where to look
=> SEQNG-1113 Do pause after pauseNS rather than stop

modules/seqexec/model/jvm/src/main/scala/seqexec/model/config/SystemsControlConfiguration.scala, modules/seqexec/server/src/main/scala/seqexec/server/CaServiceInit.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
I was a bit surprised to see the CaService initalized even in full simulation, then I noted it was ok to do so but I want to add a log item just to make it clearer
This PR adds that and moves the init part out of SeqexecEngine
=> Improve initalization of the ca service

modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/Gsaoi.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala
It seems to me the concept of graceful abort is not used and could be removed. @jluhrs Why did we have it in the first place?
=> Remove the concept of graceful abort

modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Sequence.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Step.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/StepSpec.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/Step.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/StepState.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/StepsView.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosStepView.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/StepsViewSpec.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
This is a small refactoring while I'm doing some changes to abort. It adds a syntax to find the status of an engine Step and removes some duplicated bits
It also removes some references to the deprecated graceful abort mode
=> Improvements to StepState

modules/seqexec/server/src/main/scala/seqexec/server/ObserveActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala
Some testing shows that on abort we get two abort events on the odb:
This is because the abort sends one, and we have a generic one for errors.
A future change will make abort act without using an error but in the meanwhile this PR fixes it
=> SEQNG-1124: Avoid duplicated abort notifications to the odb

modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiStatusApply.scala
Turns out the original comparison function to decide if we should move GPI's polarizer angle was too naive not taking into account wraparounds on 360
This PR improves it calculating the shortest angle difference and fixes an additional bug on comparisons
This code was tested on instrument and surfaced an extra bug on GPI TLC code: REL-3752
=> SEQNG-1038 Custom tolerance function for polarizer angle

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
[SEQNG-1125]: Disable GMOS N&S "Stop at end of cycle" button while paused
Regarding [SEQNG-1116]: Indicate detector is reading out after Stop
*  I'm changing the message to "Stopping - Reading Out" whenever a stop is requested in any kind of observation. I just need confirmation that a "Reading Out" always takes place whenever a Stop is requested in any kind of step.
* Also, @jluhrs @cquiroz  we seem to be missing an event that should happen whenever a graceful stop starts. Without that, we have no way to display the "Reading Out" message when the end of the cycle is reached. (At least without knowing that a graceful stop has been requested).
=> [SEQENG-1125] & [SEQNG-1116] (partial)

modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/NodAndShuffleProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala
I'm detecting a number of cases where the UI is not receiving the `ReadingOut` status:
- Regular observation stopped early.
- N&S graceful stop reached.
- N&S observation completes normally.
Consulting with @jluhrs it seems this is a simulation issue. However, I'm keeping some heuristic logic to show "Reading Out" when the observation is stopping or the remaining time is 0, just in case.
=> [SEQNG-1116] Indicate detector is reading out after stop.

modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/HeaderSideBarFocus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/ControlMenu.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/HeadersSideBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SessionQueueTable.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ClientStatus.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
The user-edited was being remembered but it seems the current interfaced proved a bit confusing.
This is how it is looking now:
As always, I accept suggestions regarding UI in general: fonts, colors, behavior, etc.
=> [SEQNG-1123] Remember user-edited Observer name

app/seqexec-server/src/main/resources/seqexec-server.env, app/seqexec-server/src/main/resources/seqexec-server.service, build.sbt, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala, project/plugins.sbt
This PR adds scripts to launch the seqexec via systemd. Note that we install the scripts manually rather than using e.g rpms.
The scripts are designed to keep the current location of the seqexec so they should work with new deployments.
I'm not an expert on this an apparently `systemd` would allow much finer grained control but this suffice for our needs
This seems a bit of an arcane art, I expect we'll be iterating about it for a while
=> Add systemd launcher scripts

modules/seqexec/server/src/main/scala/seqexec/server/CleanConfig.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SequenceConfiguration.scala, modules/seqexec/server/src/main/scala/seqexec/server/StepType.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/seqexec/server/src/test/scala/seqexec/server/CleanConfigSpec.scala
OIWFS guiding is now forced to freeze for GCAL calibrations inside a night sequence, if there is an OI in use.
=> SEQNG-1140 Disable OI guiding for GCAL calibrations.

modules/seqexec/web/client/src/main/resources/dev.js, modules/seqexec/web/client/src/main/scala/seqexec/web/client/SeqexecApp.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/DividedProgress.scala, modules/shared/web/client/src/main/scala/web/client/table/ColumnWidth.scala, modules/shared/web/client/src/main/scala/web/client/table/package.scala
We have detected some unnecessary re renderings. I traced at least some of them to the calculations on tables. The original calculation was too naive and we should account for small changes
This PR seems to reduce the warnings of unneeded refreshes
=> SEQNG-1145 Improve reusability of tables

build.sbt, modules/seqexec/web/client/src/webpack/dev.webpack.config.js, modules/seqexec/web/client/src/webpack/prod.webpack.config.js
We use `favicons-webpack-plugin` to generate favicons for the app. This plugin is now obsolete and throws a bunch of warnings. This PR switches to `app-manifest-webpack-plugin`
=> Switch to app-manifest-webpack-plugin

build.sbt, modules/seqexec/web/client/src/webpack/dev.webpack.config.js, modules/seqexec/web/client/src/webpack/prod.webpack.config.js
This reverts commit 6fb87866bd92792211adf360ff76abaaebcce426. (https://github.com/gemini-hlsw/ocs3/pull/1219)
It is the right move but it seemed to break a clean build. I'm reverting for now to unlock other PRs and we can investigate later how to upgrade the library and eliminate the warnings from the old version.
Luckily, it was possible to revert without consequences.
=> Revert "Switch to app-manifest-webpack-plugin"

modules/seqexec/server/src/main/scala/seqexec/server/GiapiInstrumentController.scala, modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/GhostController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala, modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala
Added some missing log messages when interacting with external systems, and gave some uniformity to them. For example:
* Now every "start observe" message includes the file id.
* All long commands have a "start" and "completed" message
* All log messages related to interactions with external systems are at the DEBUG level.
=> SEQNG-1155 Put some order in the real system log messages.

.github/workflows/create-release.yml, .github/workflows/packtracker.yml, .github/workflows/scala.yml, build.sbt, modules/seqexec/web/client/src/webpack/packtracker.webpack.config.js, modules/seqexec/web/client/src/webpack/prod.webpack.config.js, modules/seqexec/web/client/src/webpack/test.webpack.config.js
Buildkite has become very unstable. I propose we switch to github actions
This PR sets it up running tests only for the seqexec part. This is because we are going to split the repo and I don't want to setup postgress yet
On buildkite we measure the asset sizes. I added another action that would do something equivalent using https://app.packtracker.io/organizations/422/projects/321. The latter task would only run on merge thus making the build faster
=> Use github actions instead of buildkite

.github/workflows/packtracker.yml, .github/workflows/scala.yml
This change should build the js only if relevant files have changed. Hopefully it will reduce CI times in some cases
=> Reduce the amount of times we build the js file

.github/workflows/packtracker.yml, modules/seqexec/model/shared/src/main/scala/seqexec/common/FixedLengthBuffer.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/events.scala, modules/seqexec/model/shared/src/test/scala/seqexec/common/ArbitrariesCommon.scala, modules/seqexec/model/shared/src/test/scala/seqexec/model/SeqexecEventSpec.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/reusability/package.scala
Sometimes we show log lines duplicated on the client. I tracked this to multiple subscriptions on the client when you do login/logout. Fixing the root maybe complicated due to the asynchronous nature of the events so I'll simply filter duplicates on the UI
=> SEQNG-551 Remove duplicate log lines

modules/seqexec/model/shared/src/main/scala/seqexec/common/HttpStatusCodes.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/SeqexecCircuit.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/UserLoginHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/WebSocketHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecAppRootModel.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/WebSocketConnection.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala, modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala, modules/seqexec/web/client/src/webpack/dev.webpack.config.js, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/PingRoutes.scala, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
The seqexec has a session of 2h which gets renewed when the user does something.
If the user leaves without logging out, after the TTL actions are rejected. That is working fine but the UI shows it like it still logged in
Detecting that your session expired is a bit tricky as if the user does nothing we can't tell and the websocket channel only checks auth at the start
The solution is to define a "ping" route that the client hits ever n minutes. If you are logged in and the ping returns unauthorized then the UI will log itself out
=> SEQNG-1170 Auto logout when the session expires

modules/seqexec/model/shared/src/main/scala/seqexec/model/ObservationProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/BiasStatus.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/NodAndShuffleProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
Two of the fixes are related to issues reported in SEQNG-1163:
1. Display "Reading Out" on BIAS observations.
2. Disable observation control buttons during readout (this is implemented now for all kinds of observations).
Also, beyond the reported issues, this PR attempts to fix a problem with a "dancing" (going back and forth) countdown in N&S observations. This has to be tested on the telescope since our N&S simulation is not yet reflecting the same behavior.
=> [SEQNG-1163] Display "Reading Out" in BIAS observations, disable control buttons during readout, fix N&S countdown

modules/acm/src/test/scala/edu/gemini/epics/acm/ObserveTimeoutSpec.scala, modules/seqexec/server/src/main/scala/seqexec/server/CleanConfig.scala, modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/seqexec/server/src/main/scala/seqexec/server/ObserveActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecFailure.scala, modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/Gsaoi.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerSim.scala, modules/seqexec/server/src/test/scala/seqexec/server/ObserveActionsSpec.scala
If the instrument observe were to fail (e.g the instrument crashes) the seqexec waits for ever and becomes mostly non-operational
This PR adds a timeout to the observe. This is a bit hard to test but I managed to reproduce it on a simulated GPI and added a test
We should consider adding timeouts to other parts of the obs process
=> SEQNG-1157 Add a timeout to observes

modules/seqexec/server/src/main/scala/seqexec/server/ObserveActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsController.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerSim.scala
The `timeoutTo` became redundant after the observe timeout in the acm code was fixed, and was causing problems because it was triggered before the ACM one in some cases.
=> SEQNG-1181 Removed redundant observe timeout, adjusted timeouts.

modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/GuideConfigStatus.scala
Some styles were missed on the last port to semantic-ui-react affecting the guide status bar
=> SEQNG-1199 Fixes missing styles on the guide config bar

modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsHeader.scala
Seqexec does not need to write the WCS FITS keywords for NIFS anymore, because the writing of the keywords was moved to the instrument (as it should be).
This PR must not be merged until the new NIFS DC software is officially deployed.
=> SEQNG-1189 Removed WCS for NIFS.

modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala
We had an instance of the "pendIO timeout" problem when Seqexec called the endObserve CAD record on NIRI. The old Seqexec does not use that record, so I removed the call.
=> SEQNG-1198 Removed call to NIRI endObserve command.

modules/seqexec/model/shared/src/main/scala/seqexec/model/Conditions.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/SequencesQueue.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/boopickle/ModelBooPicklers.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/enum/CloudCover.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/enum/ImageQuality.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/enum/SkyBackground.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/enum/WaterVapor.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/StandardHeader.scala
The old seqexec included the concept of unknown for conditions but it wasn't included in the new seqexec. This PR adds that value and sets it as the default
A special case for unknown is added to write keywords with that value
=> SEQNG-512 Add the concept of unknown conditions

modules/seqexec/server/src/main/scala/seqexec/server/keywords/ObsKeywordReader.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/StandardHeader.scala
Use proprietaryMonths to calculate release date regardless of the value of headerVisibility, as the old Seqexec does.
=> SEQNG-1205 Fixed RELEASE keyword.

modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Event.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/Handle.scala, modules/seqexec/engine/src/main/scala/seqexec/engine/UserEvent.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/SequenceSpec.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/StepSpec.scala, modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala, modules/seqexec/server/src/main/scala/seqexec/server/ObserveActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/ObserveEnvironment.scala, modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqEvent.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/server/src/main/scala/seqexec/server/SequenceGen.scala, modules/seqexec/server/src/main/scala/seqexec/server/StepsView.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosStepView.scala, modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala
The event was sent only when executing the first step, which meant there was not event when starting a partially executed sequence.
I also found several cases where the server was not notifying the web clients when a sequence started, particularly when run from the calibration queue. That was also fixed.
=> SEQNG-1206 Send event sequenceStart to ODB

app/seqexec-server-gn/src/main/resources/app.conf, app/seqexec-server-gs/src/main/resources/app.conf, modules/seqexec/model/jvm/src/main/scala/seqexec/model/config/SeqexecEngineConfiguration.scala, modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala, modules/seqexec/web/server/src/main/resources/app.conf, modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala, modules/seqexec/web/server/src/test/scala/seqexec/web/server/config/ConfigurationLoaderSpec.scala
Some DHS operations were taking up to 11 seconds, causing a timeout in Seqexec. I increased the timeout from 5 to 20 seconds, and made it a configuration parameter.
=> SEQNG-1210 Set DHS timeout to 20 seconds.

build.sbt, modules/seqexec/server/src/main/scala/seqexec/server/SequenceConfiguration.scala
This fixes a fault reported where the Wavelength wasn't properly set on each step.
It was tracked to the value from the OT using a different type than expected and 
the error was silently discarded.
This makes the values of the Wavelength on the headers incorrect but worse the TCS
wasn't getting the correct values. It may invalidate some observations.
=> SEQNG-1218 Properly read the Observing wavelength from the OT

modules/seqexec/server/src/main/scala/seqexec/server/ConfigUtilOps.scala, modules/seqexec/server/src/main/scala/seqexec/server/SequenceConfiguration.scala, modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala, modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/Gsaoi.scala, modules/seqexec/server/src/main/scala/seqexec/server/keywords/DhsClientHttp.scala, modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/seqexec/server/src/main/scala/seqexec/server/package.scala
We've been trying  to reduce the use pf type aliases in the seqexec.
This OR removes `TrySeq`
=> Remove TrySeq alias

modules/seqexec/web/client/src/main/resources/dev.js, modules/seqexec/web/client/src/main/resources/less/semantic-ui-alerts.less, modules/seqexec/web/client/src/main/resources/less/style.less, modules/seqexec/web/client/src/main/resources/prod.js, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/DividedProgress.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/Footer.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecMain.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala
It is not possible now to copy the version of the seqexec from the UI.
We want to make it easier for users to report the version number.
This PR will copy the version when the area is clicked
I also used this as an opportunity to test semantic-ui-toasts for notifications.
=> Support copying the seqexec version

modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/StepItems.scala, project/Settings.scala
A fault was reported for a GMOS sequence containing a custom mask for some steps and FPU none for others.
The expected behavior is to set custom or no on the respective steps but the seqexec
is trying to set the custom mask at each step
The root cause is that the OT indicates that each step uses a custom mask mode, and that indication
is used to select the mask.
Ideally this would be fixed in the OT but otherwise we can workaround checking the particular case that FPU is none for custom mask mode.
The change is required both in the backend and the frontend as we don't have real types at that level on the frontend, relying instead on the String representation provided by the OT.
The UI shows the difference
Before:
After:
It require testing against a few sequences
=> SEQNG-1220 Don't use a custom mask if FPU is NONE

modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
The channel used was not suitable, because it was not updated until an observe was executed. Now Seqexec uses the same channel used by the old Seqexec, which is updated as soon as the new exposure time is configured.
=> SEQNG-1222 Compare current GMOS exposure time using same channel as Tcl Seqexec

modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala
This is another attempt to properly read from the OT when to use the built in FPU mask or a custom mask
All provided sample sequences work as expected
=> Fix to read FPU in some composite cases

modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
It happens that a missing Disperser Order in a GMOS sequence was not an error, but a "feature".
=> SEQNG-1224 Use order 0 when GMOS is missing the disperser order parameter

.gitignore, modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
After discussing it with Science, we decided to use Order 1 as the default value for GMOS. that will be used when the sequence is using a grating but missing its order. Order 1 requires `disperserWavelength`. Its absence will still be treated as an error.
=> SEQNG-1224 Changed default for GMOS disperser order to 1.

modules/seqexec/model/shared/src/main/scala/seqexec/model/UserPrompt.scala, modules/seqexec/model/shared/src/main/scala/seqexec/model/boopickle/ModelBooPicklers.scala, modules/seqexec/model/shared/src/test/scala/seqexec/model/arb/ArbUserPrompt.scala, modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/UserPromptBox.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/UserPromptHandler.scala, modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
The observing conditions check was combined with the already existing target check, using the same user prompt box and the override mechanism.
=> SEQNG-1203 Implemented observing conditions check.

modules/server/src/main/scala/seqexec/server/gmos/GmosHeader.scala, modules/server/src/main/scala/seqexec/server/keywords/package.scala
Tcl Seqexec can limit the number of decimals for the value of floating point keywords, as a consequence of everything been strings in Tcl.  I implemented a similar feature in the new Seqexec.
=> SEQNG-1231 Optional limit to precision of floating point keywords.

modules/web/client/src/main/resources/less/style.less, modules/web/client/src/main/scala/seqexec/web/client/components/ControlMenu.scala, modules/web/client/src/main/scala/seqexec/web/client/components/Footer.scala, modules/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala, modules/web/client/src/main/scala/seqexec/web/client/components/SeqexecMain.scala, modules/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala, modules/web/client/src/main/scala/seqexec/web/client/components/TableContainer.scala, modules/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTabContent.scala, modules/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala, modules/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueToolbar.scala, modules/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala, modules/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala, modules/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceControl.scala, modules/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbar.scala, modules/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceInfo.scala, modules/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala, modules/web/client/src/main/scala/seqexec/web/client/components/tabs/SequenceTabContent.scala, modules/web/client/src/main/scala/seqexec/web/client/components/tabs/TabsArea.scala
The seqexec used semantic ui grids to organize the main layout but that was more complicated than needed, especially when making the UI responsive
This PR changes all that making it use flexbox instead
=> Rework of the main grid

modules/server/src/main/scala/seqexec/server/gems/Gems.scala, modules/server/src/main/scala/seqexec/server/tcs/Gaos.scala, modules/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala, modules/server/src/test/scala/seqexec/server/tcs/GuideConfigDbSuite.scala
Seqexec interacts with GeMS by notifying it of events that may affect GeMS AO and guiding. There are three types defined:
1. Sky: Natural guide stars will not be available for an observation because of a big offset.
2. Dither: The telescope will apply an offset.
3. Filter: It only applies if using GSAOI ODGW. ODGW will be unavailable.
Seqexec sends events when the conditions appears (pause command) and when it ends (resume command). Dither is the easiest one, because both events occur inside the setup of a single step (pause Dither -> TCS offset -> resume Dither -> observe).
The issue this PR fixes is for the Sky events. The pause Sky event must be sent before the first unguided exposure, and the resume Sky must be sent before the next guided one. I added a mechanism to carry the state of …
=> SEQNG-1193 Remember that Gems was paused because of a Sky between steps.

modules/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala
Night time calibrations inside an Altair sequence were failing with the error "Found useAo set for non AO step".
The issue was that class `TcsControllerEpicsCommon` is used to setup the telescope for calibrations and non AO observations, but assumed that the useAo flags must be always off. That is not the case for calibrations inside an Altair sequence.
Strictly speaking, having the useAo flag set is only an error if PWFS2 is used. I used this fact to make the check more restricted.
=> SEQNG-1232 Fixed useAo flag being checked for night time calibrations.

modules/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsKeywordReader.scala, modules/server/src/main/scala/seqexec/server/tcs/TrackingFrame.scala, modules/server/src/test/scala/seqexec/server/tcs/TcsSpec.scala, modules/server/src/test/scala/seqexec/server/tcs/TestTcsEpics.scala
The change affects the keyword CRFOLLOW, set for GPI, GeMS and Altair.
=> SEQNG-1235 CRFOLLOW value is now calculated from TCS rotator tracking frame

modules/engine/src/main/scala/seqexec/engine/Engine.scala, modules/model/shared/src/main/scala/seqexec/model/Step.scala, modules/model/shared/src/main/scala/seqexec/model/StepState.scala, modules/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala
Running from a step other than the first is accomplished by marking all the previous steps as skipped, and then starting the sequence normally. Of course, the process of marking the previous steps as skipped left completed or already skipped steps untouched. The bug was that partially run steps were also left untouched, so when calling start on the sequence, it founded this unrun step not skipped, and would start from it.
After the changes some code became redundant. I remove it.
=> SEQNG-1238 Fixed problem with trying to run a sequence from a step other than the first

modules/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
Always set the number of ROIs parameter. To be reverted when the GMOS status channel is fixed.
=> SEQNG-1242 Workaround for FR-41232: GMOS Numrois broken.

modules/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/server/src/main/scala/seqexec/server/gmos/GmosHeader.scala, modules/server/src/main/scala/seqexec/server/gmos/GmosKeywordReader.scala
This is a workaround for the problem with the GMOS status channel that gives the number of ROIs used. Instead of relying on that channel, the number of ROIs given in the sequence is used. That number is also used to determine how many ROI parameter sets must be written in the header.
=> SEQNG-1244 Used sequence value for keyword DETNROI.

modules/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala, modules/server/src/main/scala/seqexec/server/gmos/GmosHeader.scala
When configuring GMOS, whenever the number of roy or binning is changed, the ROI CAD is marked. This is necessary because the ROI configuration depends on those parameters, but they are not connected to the ROI CAD.
I also went back in the workaround for the DETNROI keyword, because at the point the value is read from GMOS, it already got the updated value.
=> SEQNG-1248 Mark GMOS ROI CAD when changing unconnected parameters.

modules/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala, modules/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala, modules/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala, modules/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala, modules/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala
The logs show instances of timeout errors where the actual time taken by GMOS to finish the observation was close to the timeout time used by Seqexec, probably causing a false timeout error. I increased the timeout for GMOS.
GMOS is not the only instrument that has frequent observation timeouts. Because of that, I also increased the timeout for other instruments. That would either fix the timeout problem, or allows us to discard that they are caused by a too short waiting time.
=> SEQNG-1252 Increased estimated readout time for observe timeout.

modules/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
Seqexec was trying to flatten Altair DM at the same time it was enabling Altair guiding, which caused a problem. That was an error when translating the old Tcl code. With this PR the two commands are sequenced. Also, I noticed that the Tcl code also enables the BTO loop on resuming, something I forgot to put in the Web Seqexec. That was also fixed.
=> SEQNG-1258 Altair: execute mirror flattening before reenabling loops.

app/seqexec-server-gn/src/main/resources/app.conf, app/seqexec-server-gs/src/main/resources/app.conf, modules/server/src/main/scala/seqexec/server/keywords/DhsClientHttp.scala
Actually, it was disabled only for the last package (the "final" one).
I also adjusted the DHS timeout after analyzing the record of request service time. 24s is the worst case.
=> SEQNG-1262 Restored retries for DHS keyword messages.

modules/server/src/main/scala/seqexec/server/tcs/TcsController.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala, modules/server/src/main/scala/seqexec/server/tcs/package.scala
Log every EPICS parameter changed in TCS. The log message has the parameter name, old value, and new value.
The new messages are output only if seqexec.server.tcs.trace is defined.
=> SEQNG-1268 Log reasons to change TCS configuration.

modules/server/src/main/scala/seqexec/server/tcs/package.scala
This is a small PR to adjust the timeout used when waiting for the science fold to get in position. It happens that sometimes it takes longer than 60 seconds.
=> FR-72094: increased timeout when waiting for science fold in-position.

modules/server/src/main/resources/Tcs.xml, modules/server/src/main/scala/seqexec/server/tcs/BasicEpicsTcsConfig.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala, modules/server/src/test/scala/seqexec/server/tcs/TcsControllerEpicsCommonSpec.scala, modules/server/src/test/scala/seqexec/server/tcs/TcsNorthControllerEpicsAoSpec.scala, modules/server/src/test/scala/seqexec/server/tcs/TestTcsEpics.scala
Seqexec was trying to park the OI probe when none was selected in the A&G Sequencer. The result was a no operation that wasted a couple of seconds on each step. This PR makes sure that Seqexec parks the OI only if it selected in the A&G Sequencer.
=> SEQNG-1270: Check selected OI before trying to park it.

modules/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
I removed the translation once used to fix the target check for major bodies, because it is not needed anymore and is causing problems when in the OT, the Horizon code is used instead of the body name.
=> FR-72196 Removed name translation of major bodies for target check

modules/web/client/src/main/resources/less/style.less, modules/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
Sync should update the table column's values if e.g. the exposure time changed in the backend. The current caching mechanism was too aggressive and that didn't happen.
=> SEQNG-1240 Support refreshing after sync

modules/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala, modules/server/src/test/scala/seqexec/server/altair/AltairControllerEpicsSpec.scala
Fixed a bug: Seqexec was not restoring M2 guiding after an offset for Altair LGS mode.
=> SEQNG-1279 Restore M2 guide after offset for Altair LGS mode.

modules/server/src/main/scala/seqexec/server/SeqexecEngine.scala, modules/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/server/src/test/scala/seqexec/server/StepsViewSpec.scala, modules/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala, modules/web/server/src/test/scala/seqexec/web/server/http4s/SeqexecCommandRoutesSpec.scala
The problem was that, in order to see the change of the observer name when commanding a system configuration, the system was forcing a sequence refresh in the client. That made the client load the new observer's name, but also reset the subsystems state.
I change the way the observer name is set when triggering other actions. Now it will generate an event to the client to refresh just the observer's name, removing the need to force a full refresh.
=> SEQNG-1281 Fixed problem with system configuration indicator.

modules/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala, modules/server/src/main/scala/seqexec/server/altair/AltairEpics.scala
Control of Altair's SFO is weird, in that it does not use a CAD record. All that is needed is to write a value to an EPICS channel. But Seqexec was handling it as it was another CAD, which caused problems.
=> SEQNG-1282 Fixed handling of Altair's SFO control.

modules/server/src/main/resources/Tcs.xml, modules/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
Added explicitly the VAL field to TCS channels that did not have a field. VAL is the default field, so the change has no major effect.
The change was required because of a problem with the new TCS Simulator written in Scala.
=> Added VAL field to definition of TCS channels.

modules/server/src/main/scala/seqexec/server/altair/AltairController.scala, modules/server/src/main/scala/seqexec/server/altair/AltairControllerDisabled.scala, modules/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala, modules/server/src/main/scala/seqexec/server/altair/AltairControllerSim.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala, modules/server/src/test/scala/seqexec/server/altair/AltairControllerEpicsSpec.scala
The main problem was that pausing the target filter was depending on if the ao guiding would be paused on this step or not. Which means that Seqexec was not disabling the filter if the ao was being paused in this step because it was paused in the previous one. 
Target filter must be disabled for all offsets, except for small offsets that will be applied with ao guiding enabled.
=> FR-72718 Fixed some bugs in target filter control.

modules/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala, modules/server/src/test/scala/seqexec/server/altair/AltairControllerEpicsSpec.scala
Seqexec does not stop AO guiding in LGS mode, as the laser star is always visible. This PR reverts that behavior to keep it in line with the Tcl Seqexec. This is only for a test.
=> Disable Altair in LGS mode when using offsets.

modules/server/src/main/scala/seqexec/server/tcs/TcsNorth.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsSouth.scala
Don't check if guider is used in current guider configuration to decide if it must be parked. There are use cases where it is valid to have a guider probe following a target and not use it to guide.
=> Removed guide use from decision to park probes.

project/Settings.scala
Reverts gemini-hlsw/seqexec#2132
This updates breaks smart gcal updates
=> Revert "Update commons-httpclient to 3.1"

modules/server/src/main/scala/seqexec/server/tcs/TcsNorth.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsSouth.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpics.scala
There are many cases where Seqexec complained about not having received a GeMS or Altair guide configuration from TCC, which were actually valid (i.e. the user actually wanted to run a GeMS or Altair observation without setting up GeMS or Altair in TCC). One example is running a pupil alignment sequence with GSAOI.
I removed the checks for a GeMS or Altair guide configuration, and used a default instead.
=> FR-42381: Removed check for GeMS and Altair configuration in GeMS and Altair mode.

modules/model/jvm/src/main/scala/seqexec/model/config/SeqexecEngineConfiguration.scala, modules/server/src/main/scala/seqexec/server/FileIdProvider.scala, modules/server/src/main/scala/seqexec/server/ObserveEnvironment.scala, modules/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/server/src/main/scala/seqexec/server/Systems.scala, modules/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/server/src/main/scala/seqexec/server/gmos/Gmos.scala, modules/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/server/src/main/scala/seqexec/server/gsaoi/Gsaoi.scala, modules/server/src/main/scala/seqexec/server/keywords/DhsClientHttp.scala, modules/server/src/main/scala/seqexec/server/keywords/DhsClientProvider.scala, modules/server/src/main/scala/seqexec/server/keywords/package.scala, modules/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/server/src/test/scala/seqexec/server/TestCommon.scala, modules/web/server/src/main/resources/app.conf, modules/web/server/src/test/scala/seqexec/web/server/config/ConfigurationLoaderSpec.scala
Limit the size of keyword messages for the DHS. Long list of keywords are now split into smaller chunks before sending them to the DHS.
=> Split keyword messages in smaller chunks.

.github/workflows/scala.yml, modules/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala, modules/server/src/test/scala/seqexec/server/tcs/TcsSouthControllerEpicsAoSpec.scala
GeMS opens internally opens the LGS loop on skies. Accordingly, Seqexec should not enable M1 corrections on skies, because GeMS will produce none.
=> FR-42705 Don't enable M1 guiding for GeMS on skies.

modules/server/src/main/scala/seqexec/server/gems/Gems.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala, modules/server/src/test/scala/seqexec/server/gems/GemsControllerEpicsSpec.scala, modules/server/src/test/scala/seqexec/server/gems/TestGemsEpics.scala, modules/server/src/test/scala/seqexec/server/tcs/TcsSouthControllerEpicsAoSpec.scala
The main issue was that some logic depended on reading the statuses of c1, c2 and c3, but in RTC2 they don't work.
Also, fixed some unit tests.
=> FR-42704 Fixed bug in GeMS control, where Seqexec disabled guiding.

modules/server/src/main/java/edu/gemini/seqexec/server/tcs/ParkState.java, modules/server/src/main/scala/seqexec/server/tcs/GuideControl.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala, modules/server/src/main/scala/seqexec/server/tcs/package.scala, modules/server/src/test/scala/seqexec/server/tcs/TcsSouthControllerEpicsAoSpec.scala, modules/server/src/test/scala/seqexec/server/tcs/TestTcsEpics.scala
Seqexec had troubles with GeMS sequences where the old Tcl Seqexec had not. The problem was that TCS declared that the ODGW, and sometimes the Canopus guiders, where not in position, causing timeouts when applying offsets. The main difference between both Seqexec is that the Tcl Seqexec sends the park command for each Canopus guider and ODGW that is not in use.
I implemented the parks in this Seqexec hoping that that fixes the problem.
=> FR-42703 Park GeMS guiders when not in use.

modules/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala, modules/server/src/test/scala/seqexec/server/tcs/TcsSouthControllerEpicsAoSpec.scala
This problem was like the parallel of the one where Seqexec did not parked GeMS probes if they were not defined in the TCS mapping, but now it was that Seqexec did not recognize they were parked if not defined in the TCS mapping. Which they never were, because they were parked. This caused Seqexec to send the park command on each step. Not a critical problem, but it made it waste ~5 seconds per step.
=> Fixed retrieval of GeMS probes state when parked.

project/Settings.scala
Downgraded cats-effect to version 3.4.11 because 3.5.1 was suspected of causing problems.
=> Downgraded cats-effect.

modules/server/src/main/resources/Tcs.xml, modules/server/src/main/scala/seqexec/server/InstrumentSpecifics.scala, modules/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/server/src/main/scala/seqexec/server/ghost/GhostConfig.scala, modules/server/src/main/scala/seqexec/server/tcs/BasicEpicsTcsConfig.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsController.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsNorth.scala, modules/server/src/main/scala/seqexec/server/tcs/TcsSouth.scala, modules/server/src/test/scala/seqexec/server/ghost/GhostArbitraries.scala, modules/server/src/test/scala/seqexec/server/tcs/TcsControllerEpicsCommonSpec.scala, modules/server/src/test/scala/seqexec/server/tcs/TcsSouthControllerEpicsAoSpec.scala, modules/server/src/test/scala/seqexec/server/tcs/TestTcsEpics.scala
This PR adds support to set the extra defocus term for GHOST when configuring the TCS.
* The amount to defocus is calculated from the coordinate values (eventually we'll move the calculation back to the OT)
* Then it is written to the tcs apply on the channel `$top:dtelFocus.B`
* Prior to write the value it is compared with the current value at `$top:sad:dtelFocus.B`
This is subject to testing
=> Defocus support for GHOST

modules/engine/src/main/scala/seqexec/engine/Action.scala, modules/engine/src/main/scala/seqexec/engine/Engine.scala, modules/engine/src/test/scala/seqexec/engine/StepSpec.scala, modules/server/src/main/scala/seqexec/server/InstrumentSystem.scala, modules/server/src/main/scala/seqexec/server/SeqTranslate.scala, modules/server/src/main/scala/seqexec/server/SequenceGen.scala, modules/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala, modules/server/src/main/scala/seqexec/server/ghost/Ghost.scala, modules/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala, modules/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala, modules/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala, modules/server/src/main/scala/seqexec/server/gpi/Gpi.scala, modules/server/src/main/scala/seqexec/server/gsaoi/Gsaoi.scala, modules/server/src/main/scala/seqexec/server/nifs/Nifs.scala, modules/server/src/main/scala/seqexec/server/niri/Niri.scala, modules/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala, modules/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala, modules/server/src/test/scala/seqexec/server/TestCommon.scala
For IGRINS2 we need a way to inform the instrument when the sequence has been completed
This PR adds a new method for `InstrumentSystem`, `sequenceComplete` which will be called when the last  step gets completed.
In this PR none of  the instrument will use this action but in the near future IGRINS2 will add an implementation
=> Add endObserve event

modules/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
Addresses [GNFR-73603](https://noirlab.atlassian.net/browse/GNFR-73603) / [REL-4430](https://noirlab.atlassian.net/browse/REL-4430).
The offsets column was hidden unless the first step was of type `Object`. This PR changes the logic so that the column is now hidden if there are no `Object` steps at all in the sequence.
=> [GNFR-73603] Show offsets column whenever there's an Object step in the sequence

dockerfiles/Dockerfile.gn_test
I forgot to update the path for the test build directory in the Dockerfile used to build gn_test
https://noirlab.atlassian.net/browse/REL-4604
=> REL-4604 Fix build Dockerfile for gn_test

flake.nix, modules/server/src/main/scala/seqexec/server/Systems.scala, modules/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
We need to make the giapi connection name unique.
If we have multiple seqexec instances (production/test) connected at the same time there will be a conflict.
This PR solves it by attaching the seqexec host to the connection name
=> REL-4609 Use a different connection name for different instances
