- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SequenceSearch.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/TopMenu.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/button/Button.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/icon/Icon.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/message/CloseableMessage.scala
this PR brings a React button component and fixes a bug on the Search results button that wouldn't work on firefox. This version works correctly on firefox and chrome
> Button component fixes firefox bug

- modules/edu.gemini.seqexec.server/build.sbt
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ExecutorImpl.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/package.scala
- modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/DhsClientSimSpec.scala
- modules/edu.gemini.seqexec.shared/build.sbt
- modules/edu.gemini.seqexec.web/build.sbt
- project/Settings.scala
This PR brings the ocs port to scalaz 7.2. It also unifies scalaz versions across JVM and JS
> Scalaz 7.2

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/NavBar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SequenceSearch.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/SemanticUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/icon/Icon.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/package.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/index.html
This PR contains updates to the UI, there are minimal logical changes. Many of the updates make the application usable on mobile devices. A big new addition is the ability to display a step's configuration
Fixes #32 
Fixes #31 
Fixes #25 
Fixes #23
> UI improvements

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/NavBar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SequenceSearch.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- project/Settings.scala
This is a small PR updating the diode library to the version 1.0.0. It can be considered pure UI code
> Port to diode 1.0.0

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/NavBar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SequenceSearch.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/TopMenu.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
This PR completes the WebSockets reconnection task with UI updates. It will display a message on the UI and disable buttons when the connection is lost
Here's a screenshot:
> Reconnecting WS ui

- .gitignore
This commit is a good chance to include more ignores. Let me know if you want to list more.
> Additional gitignores

- .travis.yml
- modules/edu.gemini.seqexec.web/build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/ArbitrariesWebClient.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuitQueueHandlerSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuitSequenceDisplayHandlerSpec.scala
- project/plugins.sbt
This PR fixes some compilation errors on the tests. These tests are disabled at the build level as there is a **yet-unsolved** conflict between the available runtime environments (Rhino/node.js/phantom) and jquery
At least this PR will not let check in with non-compilable tests
Additionally this PR advances scala.js version to 0.6.10
> Test improvements

- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
It is just the list of tests, with no implementation yet.
> SEQNG-7: Added list of basic tests.

- .gitignore
I'm not sure if for this commit it's worth making a PR, but I'm doing so just in case.
> Git ignore `buildinfo.properties`

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
Please make sure the load sequence function stub has the correct type signature. If that's the type signature loading the sequence from the UI is trivial.
> SEQNG-49 Load Sequence from from UI

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Handler.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/NewBooPicklers.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/SharedModel.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
With this commit now it's possible to see that the first sequence is loaded properly though the web console in the browser.
> SEQNG-53 SEQNG-54 Fix sequence load through websocket

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
Following @cquiroz hints about this bug I found out there was a problem with operator preference. Now it should load the first *Sequence* fine, I tried 3 times in a row and worked on my machine 💻.
The `Process` execution is controlled implicitly by `http4s` and I'm pretty sure it creates a different `Process` per websocket. This didn't seem to affect the bug in this PR, but it will be an issue when different users run the Seqexec at the same time.
We will have to look into some kind of broadcast mechanism with `scalaz-stream` (*topics*?) in order to make sure all users run only one engine `Process`. So I'm filing a separate ticket for that case.
> SEQNG-60 Load first Sequence correctly #resolve

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Commands.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/WebSocketsEventsHandlerSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
This PR mostly integrates the "run" command in the web ui. There are some issues on the way events are emitted, another PR will likely be done to be compatible with any fixes
> SEQNG-72A: Integrate sequence control commands in Web UI - RUN

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2ControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerEpics.scala
The biggest change is the inclusion of initialization of the EPICS connections. Not sure if it is in the right place. The rest are small bug fixes or improvements to simulations.
> SEQNG-74 Bugfixes to make it work with EPICS systems.

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/WebSocketsEventsHandlerSpec.scala
This is a small PR simplifying a bit the event model and thus removing a bit of duplicated code
> Model simplification

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
Previously it was only logging it.
> Return state for `refresh` command

- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SequenceSearch.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/LoadHandlerSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- project/SeqexecEngineModules.scala
This PR fixes several UI artifacts and request a refresh of the event upon connection
It also contains a small fix releated to SEQNG-72
> SEQNG-71: Ensure clients get refreshed upon connection to server

- modules/edu.gemini.p1backend/edu.gemini.p1backend.client/src/main/scala/edu/gemini/p1backend/client/P1BackendApp.scala
- modules/edu.gemini.p1backend/edu.gemini.p1backend.server/src/main/resources/app.conf
- modules/edu.gemini.p1backend/edu.gemini.p1backend.server/src/main/resources/css/semantic.css
- modules/edu.gemini.p1backend/edu.gemini.p1backend.server/src/main/scala/edu/gemini/p1backend/server/WebServerLauncher.scala
- modules/edu.gemini.p1backend/edu.gemini.p1backend.server/src/main/scala/edu/gemini/p1backend/server/http4s/WebServerLauncher.scala
- modules/edu.gemini.p1backend/edu.gemini.p1backend.server/src/main/scala/edu/gemini/p1backend/server/http4s/package.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/package.scala
- modules/edu.gemini.web.server.common/src/main/scala/edu/gemini/web/server/common/LogInitialization.scala
- modules/edu.gemini.web.server.common/src/main/scala/edu/gemini/web/server/common/StaticRoutes.scala
- modules/edu.gemini.web.server.common/src/test/scala/edu/gemini/web/common/http4s/StaticRoutesSpec.scala
- project/AppsCommon.scala
- project/Common.scala
- project/OcsBuild.scala
- project/Phase1BackendApps.scala
- project/Phase1BackendModules.scala
- project/SeqexecEngineModules.scala
- project/SeqexecWebModules.scala
- project/Settings.scala
This PR adds several bare bones modules for the future phase1 backend server/client that @sraaphorst will work on
It adopts essentially the same tools and structure of the seqexec app. Some classes are moved to a common module to be shared across the applications. This is done only for server classes but most likely client classes will be split in the near future too
> P1 Backend project skeleton

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
Small codefix discussed in PR #133
> Code simplification

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
- project/Settings.scala
For a while I've been trying to do more tests on the backend. Tests on regular routes is fairly straightforward but for websockets sending data in binary frames it turns out more tricky
The tests below simulate a connection and verify that we get a `ConnectionOpenEvent(u)` on the websocket pipe. The first test is for anonymous users and the second is for a logged in user
> SEQNG-90: Web sockets unit test

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
`Start` is *Green* and `Pause` is *Red*.
> SEQNG-89 Add colors Start/Pause buttons

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2ControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
Created F2 simulation object that always fails configuration. It is used if setting _instForceError_ in app.conf is _true_
> SEQNG-103: Implemented switch to force F2 simulation to fail.

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/TabularMenu.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/message/IconMessage.scala
As in other cases this PR is to share the UI design. This is how we could display errors on a given step. I'm not clear if we need the ack system. Do we?
If so, is this something that others should see, meaning if one user presses ack, the others don't need to see it? We could discuss this a bit, it may complicate the backend model
Here is a screenshot in the error state:
> SEQNG-98: Find a place for F2 sequence execution errors

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Execution.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/ExecutionSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
The `fileId` is set in the Step when an action returns successfully an `Observed` `Result`.
> Set FileId for completed Step

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
Now the effect of the breakpoint applies only at the beginning of the Step. Unit test included.
This PR includes a simpler solution to SEQNG-127, and some improvements to the tests.
> SEQNG-129 Fixed bug that activated breakpoint in the middle of a Step.

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
This PR connects the breakpoints set on the UI to the backend
> SEGNG-121: Link UI for breakpoints with the backend

- modules/edu.gemini.seqexec.server/src/main/resources/DhsHdr.xml
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsKeywordReader.scala
By "standard" I refer to the keywords that always go in the image. I left out some TCS keywords that may or may not go, depending on the guide configuration used (there is another task for them)
> SEQNG-131: Added standard TCS keywords.

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/NavBar.scala
> SEQNG-137 Display version number on UI

- modules/edu.gemini.seqexec.server/src/main/resources/Tcs.xml
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Tcs.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsKeywordReader.scala
Wrote all the keywords related to guiders' targets.
> SEQNG-140 Write guiders keywords: P1, P2, OI and AO.

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ConfigUtilOps.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Header.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
- modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/ConfigUtilSpec.scala
Also include a change to the errors produced when reading values from the ODB sequence.
> SEQNG-143 Implemented data privacy keywords.

- build.sbt
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/dhs.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Controller.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2ControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2ControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Header.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosSouth.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Header.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Instrument.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ODBProxy.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
- project/Settings.scala
I have links to all the required notification methods, and put the notification for the start and end of observations in place. I am not too happy about it though.
The notifications are in `ODBProxy`. The first method was implemented by Shane using `TrpcClient`, but for the rest I used the XMLRPC interface. The result is a bit of a weird mix.
Inserting the notifications was also a bit ugly. I wish I could have just wrapped the observe from the instrument object, but the notifications need the file ID, that was contained inside the instrument observe method. So I had to break it and rearrange it.
> SEQNG-125 Functions to send notifications to the ODB.

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Execution.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/DhsClient.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ODBProxy.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/DhsClientSimSpec.scala
Implementation is a bit heterogeneous. The Sequence Start and Sequence Complete notifications are sent inside actions in the first an last steps. The Observation Abort and Observation Pause are sent as reactions to events.
There is an issue with the implementation of the Sequence Complete notification. Because it is an action, it may be posible to pause the sequence before it is executed.
> SEQNG-152 Sent sequence notifications to the ODB.

- .gitignore
- app/seqexec-server-gs-test/src/main/resources/app.conf
- build.sbt
- version.sbt
Prepare configuration for the first release with the configuration set for testing
Note that the configuration for production is handled internally
> SEQNG-154: Create and install new release

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/security/authentication.scala
- project/Settings.scala
Some libraries updates:
* http4s
* jwt
* squants
> Versions update

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/package.scala
Updates to write requested observing conditions and timing windows
> SEQNG-151: Write FITS keywords for requested observing conditions

- modules/edu.gemini.seqexec.server/src/main/resources/Gws.xml
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Header.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GwsEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GwsKeywordReader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Header.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/KeywordsReader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsKeywordReader.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
I also modified the way the default values for FITS keywords are handled. Now they are defined in one place. If the value to be written is an Option, and it is None, then the default value is used.
> SEQNG-163 weather keywords

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
This is a very basic way to specify resources for F2. Adding more instruments by just adding more case patterns to `instrumentResources`.
> SEQNG-164 Specify resources for F2 Step

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalEpics.scala
Model to represent the GCAL configuration. It can be the configuration read from the real system, or the configuration that is meant to be applied.
There are cases when certain elements of GCAL should be left alone. For that, I opted to make every value in the configuration an Option. If any of the values in a requested configuration is None, then that GCAL element will not be configured. In the read configuration a None means the value cannot be read, or the value read cannot be converted.
> SEQNG-167 Implemented configuration of GCAL EPICS system.

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client.cli/src/main/scala/edu/gemini/seqexec/web/client/cli/SeqexecTerminal.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/SeqexecApp.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/Audio.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/cli-dev.html
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/cli.html
- project/plugins.sbt
Today scala.js 0.6.15 was released and this PR upgrades it for our use
> Update to scala.js 0.6.15

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Gcal.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
I did something different with GCAL. For FLAMINGOS-2, all the configuration parameters are always set. With GCAL, the current configuration is read and compared with the required configuration, and only those elements that are different are configured.
This works as only being tested against its internal GCAL simulator. The tests with the real GCAL are a separate task.
> SEQNG-168 Included GCAL in step configuration.

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalControllerEpics.scala
> SEQNG-170 Fixed bug discovered in tests.

- version.sbt
Update version for today's release
> Set version number for release

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/ExecutionSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/encoder/BooEncoders.scala
This PR adds methods to set the image quality independently of the other conditions. After the review it should be expanded to allow updating the other condition subsets
> Allow setting the image quality directly

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/DropdownMenu.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/SemanticUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/dropdown/DropdownMenu.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/ArbitrariesWebClient.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SequenceDisplayHandlerSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/encoder/BooEncoders.scala
This PR enables selecting the conditions from the UI and at the same time displays the current set of conditions selected on the engine
There are still some UI issues to solve but I'll do them on another PR. This is functional enough to be usable
Note that I also disabled the operator field as it wasn't working properly. That will be also addressed in another PR
> SEQNG-157: Allow selection of conditions

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Gcal.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalHeader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalKeywordReader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
Implementation of the Gcal keywords
> SEQNG-169: GCAL FITS keywords

- .travis.yml
- build.sbt
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala
This PR apparently fixes the issues observed when running builds in travis
This comes after several rounds of testing and with the experience of other projects that have large scala.js code bases
> SEQNG-185: Fix for stalled builds

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Resource.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.server/src/main/resources/Tcs.xml
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ConfigUtilOps.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Tcs.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsEpics.scala
The PR ended I bit more complicated than expected. First, I had to write code to deal with the way the name of the Science Fold position is encoded. And then there is the fact that the AG is configured through TCS, so I can not treat it as an independent system.
> SEQNG-171 Implemented configuration of science fold to direct light to instrument.

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
As it turns out this was never implemented. This PR implements this change
Additionally a bug was fixed that would allow non-logged users to set breakpoints
> SEQNG-175: Cannot remove breakpoints from the UI

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/NavBar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SequenceSearch.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/TopMenu.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceDefaultToolbar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
This PR brings some improvements to the UI in different device sizes. Depending on the size of the screens some buttons would get miss-aligned
Also the mobile level view gets too crowded to be usable so I'm turning it into a view-only mode. This is debatable of course and could be changed if there is user demand
> Responsive UI improvements

- .gitignore
- build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/TLS.md
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
- project/Settings.scala
This PR adds code to support TLS. At the moment this is not yet being deployed as there are some issues with the certificates provided by ITS but the code is harmless unless you setup the right values on the configuration
> SEQNG-194: Support tls

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ODBProxy.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/WebSocketsEventsHandlerSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
The mechanism implemented is a periodic polling. Every 10 seconds Seqexec retrieves the list of sequences in the ODB queue and compares it with the sequences loaded. New sequences in the list will be loaded, and sequences not in the list will be unloaded.
> SEQNG-195: Automatic load and unload of sequences from ODB queue.

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
Filter steps of unrecognized type from a sequence and produce warnings.
> Filter unrecognized steps from sequence

- version.sbt
> Prepare next iteration

- .travis.yml
Yet another attempt at getting travis to work more consistently. Travis is supposed to have a max mem of 3G in this case so I'm reducing the amount of memory requested to avoid paging
I have run this several times successfully
> Another try at travis

- project/Settings.scala
Updates the version to the latest available
> Updated ocs libraries to 2017A 1.1.6

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsEpics.scala
This fixes another NullPointerException.
> SEQNG-225 Read OIWFS integration time as a String.

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
This PR changes the top to a fem GMOS channels and enables f2 with epics
> Test fixes

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosEpics.scala
The AmpCount values should be written as a String according to the seqexec LUT
> SEQNG-234: AmpCount should be written as a string

- modules/edu.gemini.p1backend/edu.gemini.p1backend.client/src/main/scala/edu/gemini/p1backend/client/P1BackendApp.scala
- modules/edu.gemini.p1backend/edu.gemini.p1backend.server/src/main/scala/edu/gemini/p1backend/server/http4s/WebServerLauncher.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
- project/Settings.scala
This PR updates http4s to version 0.16-M2. This version should be more stable when stopping the server but it bring some API changes
> Http4s update

- .travis.yml
I suspect our troubles with travis are on the commands below to build distributions. That may explain why it works on the local branches but not on PR
I'm not sure if it totally helps but we can try
> Don't attempt to build distributions in Travis

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Header.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalHeader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosHeader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Header.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
While doing #238 I noted that we do implicit conversions. They are not so much recommended nowadays given that they lead to unexpected actions, see [JavaConverters and JavaConversions](https://stackoverflow.com/questions/8301947/what-is-the-difference-between-javaconverters-and-javaconversions-in-scala)
I also added a little typeclass to make the conversion more generic
> Better implicit conversions

- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
The test tries to run an sequence with an Action that blocks, and is awaken by a later event. So if the event is not run, the sequence never ends, causing the test to fail.
> SEQNG-238 Created unit test to prove that event processing is not blocked by Actions.

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ConfigUtilOps.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosHeader.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosSouth.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosSouthController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
This PR adds support for custom ROI reading the values from the sequence and setting the epics channels as needed.
I added some improvements to the types to forbid invalid values when setting ROIs
> SEQNG-231: GMOS support for Custom ROI

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Engine.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/package.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
This PR is to have an initial review. I still need to fix the tests.
> SEQNG-241 Pass events as an output instead of relying on Queue.enqueueOne

- project/plugins.sbt
Minor update on the scalajs side. It should improve building the tests javascript files, I noted around 30sec saved on building the whole suite
> Upgrade to scalajs 1.7

- modules/edu.gemini.seqexec.server/src/main/resources/Tcs.xml
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Header.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
Fixed two problems:
Default values were applied even when not needed.
Guide values had to be converted to expected Strings.
> Fixed FITS keywords

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
Not very configurable yet but better than a `println`, specially when testing with the instrument.
> Engine logging

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
I still have to take care of Steps marked as skipped and write some tests, but the most important feature of this PR is already there. I could confirm manually from the UI that it can load an ongoing Sequences.
> SEQNG-146 Load sequences with executed steps from the ODB

- project/plugins.sbt
> SEQNG-287: Upgrade to scala.js 0.6.18

- app/seqexec-server-gn-test/src/main/resources/app.conf
- app/seqexec-server-gs-test/src/main/resources/app.conf
- app/seqexec-server-gs/src/main/resources/app.conf
- build.sbt
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/app.conf
- project/Settings.scala
This PR takes the updates made by @swalker2m to unroll smart gcal sequences to make them usable on the seqexec
> SEQNG-291: Support Smart Gcal

- app/seqexec-server-gs/src/main/resources/app.conf
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Tcs.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerSim.scala
I also put in this PR the fix for the server configuration.
> Park OIWFS for calibration steps

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceToolbars.scala
Small bug fix. While pausing the Pause button would disappear while it should still be there but disabled
> SEQNG-273: Display the disabled pause button while stopping

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
Now the values set in the UI end up in the FITS.
> SEQNG-299 Carried values for operator, observer and conditions to the FITS keywords.

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Tcs.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerEpics.scala
Fixed bug introduced in implementation of SEQNG-293
> SEQNG-304 Fixed bug in TCS EPICS configuration.

- build.sbt
- project/Common.scala
I finally found how to make the typelevel compiler and scala.js to play along
> SEQNG-279: Use the typelevel compiler for both jvm and js

- .gitignore
- build.sbt
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/SeqexecApp.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/NavBar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceToolbars.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SequenceDisplayHandlerSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/WebSocketsEventsHandlerSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/package.scala
This PR introduces several changes to the UI to support instruments from GN as well as from GS removing many instances of references to GS instruments
> SEQNG-305: Support GN/GS on the ui

- app/seqexec-server-gn-test/src/main/resources/app.conf
- app/seqexec-server-gn/src/main/resources/app.conf
- app/seqexec-server-gs-test/src/main/resources/app.conf
- build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
- version.sbt
configuration for seqexec GN production and version update
> SEQNG-314: New seqexec release

- .travis.yml
- build.sbt
- project/plugins.sbt
This change to the build will add the header to files without it on compile
> Automate header creation on compile

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/operations.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsControlButtons.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/SeqexecCircuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
This PR updates the code behind the step buttons row. It will send a request to the backend but right now it is just answering ok. It should be hooked up to the engine later on
> SEQNG-335: Send Stop and Abort commands from client

- build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/SeqexecApp.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LoginBox.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/NavBar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/TopMenu.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceToolbars.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsControlButtons.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/ArbitrariesWebClient.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SequenceDisplayHandlerSpec.scala
- project/Common.scala
- project/Settings.scala
- project/build.properties
With this PR we solve a problem where the websocket data is filtered for anonymous users and that remains after logging in.
This is easily solved by closing the websocket and reconnecting on Login. The same thing is done on Logout
The PR is much bigger because I moved some classes around to make the separation of classes cleaner. If you prefer i can split the PR into refactoring and actual changes
> SEQNG-256: De anonymize websocket feed after login

- project/Settings.scala
Some updates, the most important one is going to http4s 0.16.0
> Library updates

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Event.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SharedModelArbitraries.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
I also added some tests, and fixed some bugs that the same tests uncovered.
> Implemented command to cancel a pause request

- build.sbt
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Engine.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
In connection to #327 I thought I could switch the lenses used in engine to Monocle
> Use Monocle lenses rather than scalaz on engine

- build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/logback.xml
- modules/edu.gemini.web.server.common/src/main/scala/edu/gemini/web/server/common/LogInitialization.scala
To help finding the issues in production this PR increases the amount of heap memory and lower level debugging with CAJ/JCA
> Increase heap memory and epics-level debugging

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceToolbars.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceAnonymousToolbar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceInfo.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceObserverField.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
This PR lets the user to cancel a pause command and return to a running state
> SEQNG-370: Pause button must be kept visible, and reflect if a pause was requested

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/test/scala/edu/gemini/seqexec/web/common/FixedLengthBufferSpec.scala
Sometimes a test fails. I think it is overflowing on the JS side. This fix was tested several times on travis always passing
> Fix for broken test

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LoginBox.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/ResourcesBox.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/modal/Content.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/modal/Header.scala
In this PR we capture the event when there is a resource conflict and display and indication to the user.  Note that in the future resources conflicts should be handled by putting the sequence in the queue
Here's a screenshot of the box displayed
> SEQNG-212: Display an indication on the UI when there are resource conflicts

- modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaApplySenderImpl.java
- modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaCommandListener.java
- modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaCommandMonitor.java
- modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaCommandMonitorImpl.java
- modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaCommandSenderTest.java
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/EpicsUtil.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Epics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GcalEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsEpics.scala
Added the paused state for EPICS commands. This PR includes only the changes in module ACM. I had to make some changes on `seqexec.server` to make it compile, but those changes have to be revisited when proper behavior for paused exposures is implemented.
> SEQNG-380 CAR pause value is now properly processed.

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsControlButtons.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
Small update to the stop/abort buttons to update properly with the sequence state
> SEQNG-379: Link abort/stop buttons on the UI

- build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/prod.webpack.config.js
- project/Settings.scala
This magic restores the minification of the js libraries reducing their size from 1.3M to 400k
> SEQNG-390: Optimize size of js libraries

- .gitignore
- .travis.yml
- app/seqexec-server/src/main/resources/app.conf
- build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/prod.webpack.config.js
This PR contains a small update to further minimize react.js in production reducing the overall lib size from 411k to 335k.
It also fixes a bug introduced with the update of `scalajs-bundler` to `0.9.0`
> Optimize react in production

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/package.scala
These are a small fixes required to #353 after some testing
> SEQNG-393: Small fixes to subsystems updates

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqexecEngineSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/label/Label.scala
This PR updates the UI to display the updates to each subsystem as they run and complete. Note that this is simulation so to appreciate it the times of each subsystems have been increased but they are fixed
This can be better appreciated with this video
https://www.dropbox.com/preview/Monosnap/screencast%202017-10-25%2018-03-17.mp4
> SEQNG-341: Show step progress in client

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TaskRef.scala
- project/Settings.scala
And downgrade of log4s to match http4s
> Scala version update

- app/seqexec-server-gn/src/main/resources/app.conf
Fixes the redirects on the production seqexec at GN
> SEQNG-407: Fixed redirect url

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/ModelLensesSpec.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SharedModelArbitraries.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ConfigUtilOps.scala
- modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/ConfigUtilSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
I noted that we are displaying the target name to anonymous users through the step configuration. This PR will hide that information on the UI for anonymous users
It contains also improvements to the model removing some String usage
Here's a screenshot of a hidden element
> SEQNG-414: Target name leakage

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceAnonymousToolbar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceInfo.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceObserverField.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/label/Label.scala
Just a couple of minor changes to alignments and colors on the sequence table
> UI touches

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/ModelLensesSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceInfo.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceObserverField.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/lenses.scala
Display the target name on the queue area and the sequence area only for logged in users
> SEQNG-415: Display target name

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
The filtering of empty sequences has some undesirable effects as all sequences in the queue are removed when one of them is empty due to the way all `SeqAction` are squashed
This PR reverts that
> SEQNG-404 Revert filtering out of empty sequences #time 1h

- modules/edu.gemini.seqexec.server/src/main/resources/Gmos.xml
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/InstrumentSystem.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/System.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2Controller.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2ControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2Epics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gcal/Gcal.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/Gmos.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosEpics.scala
GMOS require the endObserve notification to capture dtaZEnd, so I added it. Also, dhsZStart was not captured because I was using gm:dc:observe instead of gm:observe. That was fixed too.
> SEQNG-402: Triggered observe in GMOS from IS, not DC, added endObserve notification

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gcal/GcalKeywordReader.scala
Values were read on startup only. Now they should work.
> SEQNG-403: Put reading of GCAL values for keywords in Tasks.

- build.sbt
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ActionType.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelLenses.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/README.md
- project/Common.scala
- project/build.properties
- project/plugins.sbt
This PR updates the build to run on sbt 1.0.4
I tested building, running the seqexec ui from the prompt and deploying
> SEQNG-411: Update to sbt 1.0.4

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/dropdown/DropdownMenu.scala
The combobox are not working at the moment to select different conditions. This was traced to a typo on a jquery selector and fixed on this PR
> SEQNG-427: Condition combo boxes unresponsive

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelLenses.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/events.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/BoopicklingSpec.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/ModelLensesSpec.scala
- modules/edu.gemini.seqexec.model/src/test/scala/edu/gemini/seqexec/model/SharedModelArbitraries.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/WebServerLauncher.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/logging/AppenderForClients.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/test/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
This PR adds a column to show the guiding state as on/off. The icons are up for discussion though I agreed on these ones on discussion with science
As part of this PR I moved the `SeqexecEvent` class hierarchy to another file as the `Model` object is getting very large
> SEQNG-423: Display guiding per step

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LogArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/checkbox/Checkbox.scala
Changes the sliders for checkboxes to filter the logs
> SEQNG-325: Switch the sliders for checkboxes

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/SeqexecApp.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LogArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- project/Settings.scala
This PR updates the log table to display the times in local (as in the server's local) time
here's an example. Feel free to comment especially about the format, e.g. should we use the month name or number? Should we have miliseconds?
> SEQNG-418: Display log times on local time

- build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LogArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecStyles.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/package.scala
- modules/edu.gemini.web.client.facades/src/main/scala/edu/gemini/web/client/facades/semanticui/SemanticUI.scala
- project/Settings.scala
This is a facility to support copying log lines to the clipboard. An extra button was added to the last column that can be used to copy the line to the clipboard
Do you think this is useful? Should we support selecting n lines and copy them all at once?
Here it is the feature in action
https://monosnap.com/file/MD6y69T6T9td4kHYJBfQXfy73rEUbl#
> SENQG-420: Support copying log lines to clipboard

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/SeqexecApp.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceAnonymousToolbar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
After the last major UI rework the step config had some small UI details
This PR fixes that and adds some improvement, in particular the step config has their own url route
> SEQNG-412: Improvements to step config UI

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Execution.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/ExecutionSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/operations.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/Gmos.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerSim.scala
- modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqTranslateSpec.scala
- modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqexecEngineSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/SequenceDisplayHandlerSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
Implemented the observation pause for GMOS.
> GMOS pause observation

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
Fix for problem with step not being updated in client when action failed and it was a single action.
> SEQNG-451 Produce a SeqexecUpdated event when actions fail.

- build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/resources/logback.xml
- project/Settings.scala
This is an experiment where we are able to send logs to a centralized server. I'm not sure how useful will this be but enabling it will let me play with the data
There is little downside as far as I can tell except for the network traffic
> SEQNG-358: Send logs to a logstash server

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Step.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/SequenceSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/packageSpec.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqTranslateSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
The biggest change was in the Sequence states.
> SEQNG-455 Modified Step and Sequence state.

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/StandardHeader.scala
TCS keywords use values read from TCS only if they were configured for this observation. The decision is made by TCS subsystem. For example, a FLAT, which uses the science fold but does not point the telescope, will have proper values for the science fold position, but not for the science target.
> SEQNG-436 Set values for TCS keywords only if TCS is used.

- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/Sequence.scala
- modules/edu.gemini.seqexec.engine/src/main/scala/edu/gemini/seqexec/engine/package.scala
- modules/edu.gemini.seqexec.engine/src/test/scala/edu/gemini/seqexec/engine/StepSpec.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/operations.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerSim.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/QueueArea.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
This PR hides/show the pause/resume button depending on the pausing state. This is better visualized on the following video
https://monosnap.com/file/lN0TPuXgEkbwavxxS3cN8ikq2ZpKo9#
There are some cleanups of the current code too
> SEQNG-456: Enable/disable observe buttons in client

- project/Settings.scala
- project/build.properties
Across the board library updates and sbt update to 1.1
> Libraries and sbt updates

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/ModelOps.scala
This PR will keep the step controls buttons while pausing a sequence
This can be better shown on this video
https://monosnap.com/file/nw9kVQdZaeYRgfexIwW8HfpD81mdko
> SEQNG-465: Do not hide exposure control buttons during sequence pause

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
This PR is a small aid for development. It adds a flag to control starting smartgcal
By default it will always start but a developer can disable it with the setting `seqexec-engine.smartGCalEnable`
> Support to disable smartgcal for development

- .travis.yml
This is an experimental PR, it may take a while to get it right but the idea is to calculate how much the js changes on each pull request
I can't really tell if this working unless I do a PR
> Test the size of the produced javascript size

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
it has been requested that we show in the log when another user logs in
> Show on the log when somebody logs in

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTableContainer.scala
Small fix moving the method `internalStopRequested` to the `Ops` implicit class
> Move internalStopRequested

- build.sbt
- project/plugins.sbt
There is an update to scalajs-bundler that lets us upgrade to scala.js 0.6.22
> Update to scala.js 0.6.22 and scalajs-bundler 0.10.0

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/InstrumentControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerSim.scala
Also, improved simulation of resuming a paused exposure.
> SEQNG-516 Fixed issue with observe delay in instrument simulator.

- modules/edu.gemini.seqexec.server/src/main/resources/Gnirs.xml
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/EpicsUtil.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsEpics.scala
Setup of the GNIRS EPICS system according to a GNIRS configuration. Also implemented observe commands.
I adjusted the model for GNIRS configuration as I worked in implementing the setup of the EPICS system.
> SEQNG-494 GNIRS EPICS configuration and commands.

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/Model.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/InstrumentControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2Controller.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2ControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gmos/GmosControllerSim.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerSim.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
This PR adds to the log the following:
* Show the hostname of a user when he/she logs in
* Show the observation id when taking an observation
> SEQNG-514: Add details to log

- modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaApplySenderImpl.java
- modules/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java
- modules/edu.gemini.seqexec.server/src/main/resources/Gnirs.xml
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/Gnirs.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsEpics.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsHeader.scala
- modules/edu.gemini.seqexec.server/src/test/scala/edu/gemini/seqexec/server/SeqTranslateSpec.scala
Included several changes made after testing with the real instrument. GNIRS showed several bugs in the code, specially in the ACM assumptions on the order of events.
Also, I had to abandon my intention of triggering all commands from the top level apply record, because I found the corresponding CAR record does not have its CLID connected.
> Create GNIRS Step from Sequence values

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/Gnirs.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsController.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsControllerEpics.scala
Somehow I missed this parameter.
> SEQNG-537 Configure GNIRS central wavelength.

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/gnirs/GnirsHeader.scala
> SEQNG-538 Fixed label for GNIRS keywords UTEND.

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/popup/Popup.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/package.scala
- modules/edu.gemini.web.client.facades/src/main/scala/edu/gemini/web/client/facades/semanticui/SemanticUI.scala
This PR fixes a bug where the button popups would be hidden in many cases. The original popups were pure CSS but presented this problem
In this PR i'm adding a new Popup component and use it in the correct places. The component is very basic as i'm planning to switch to the proper react components from `react-semantic-ui` in the near term
The change can be observed in the image below:
> SEQNG-457: Tooltips not visible

- .travis.yml
- build.sbt
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/TimeZonesSpec.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.server/src/main/scala/edu/gemini/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- project/plugins.sbt
This PR brings a new version of `sbt-tzdb` which is more reliable and adds a test to ensure the TZs are always available.
I'm also including a minor bugfix on the logs presented to the client
> SEQNG-547: Timezone generation bugfix

- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqTranslate.scala
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecEngine.scala
This solves the issue of the last step not being marked as completed if exposure is stopped, and also ensures the notification is sent, even if the last step is skipped.
> SEQNG-554 Moved SequenceEnd notification to ODB out of last step.

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/SeqexecUI.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/actions.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/handlers.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/model.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/services/SeqexecWebClient.scala
This PR will let users check if sounds are working on their workstations. This is a bit convoluted as we need to ensure that the sound is triggered the same way as when a sequence runs.
Instead of adding a button to the UI I added a route that can be used. like
<hostname>/soundtest
after loading the regular UI this will emit the `Sequence completed` sound
> SEQNG-559: Sound verification

- modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/ModelBooPicklers.scala
- project/Settings.scala
Some library updates, most notably `boopickle`
> Lib updates

- .travis.yml
- build.sbt
- project/Common.scala
- project/plugins.sbt
As suggested by @tpolecat this change will do an updates check on sbt startup or reload
> Use sbt-updates at startup

- .gitignore
- .travis.yml
- project/Common.scala
- project/plugins.sbt
Thanks @tpolecat for the pointers. This should properly setup `sbt-updates`
> Properly setup sbt-updates

- build.sbt
- modules/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/flamingos2/Flamingos2.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/model/circuit.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/test/scala/edu/gemini/seqexec/web/client/model/ArbitrariesWebClient.scala
- project/Common.scala
- project/Settings.scala
As with gem this PR remove using Typelevel Scala and returns to the base Lightbend scala.
I'm also bumping to the latest scala version
> Switch to LBS

- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/Footer.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/LoginBox.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/ResourcesBox.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/HeadersSideBar.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/InstrumentsTabs.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/components/sequence/toolbars/SequenceObserverField.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/dropdown/DropdownMenu.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/message/CloseableMessage.scala
- modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.client/src/main/scala/edu/gemini/seqexec/web/client/semanticui/elements/popup/Popup.scala
- project/Settings.scala
This is an upgrade to react 16 with no functionality changes. We also get rid of the last bits of scalaz usage
> SEQNG-568: Update to react 16

- project/Settings.scala
Just a minor library update. There is no effect on actual code
> Update logstash version

- .gitignore
- build.sbt
- modules/edu.gemini.giapi.client/src/main/scala/edu/gemini/giapi/client/gpi/GPIClient.scala
- modules/edu.gemini.giapi.client/src/main/scala/edu/gemini/giapi/client/package.scala
- project/Settings.scala
This is a small library to support GIAPI instruments. At the moment this only supports the `get` status item operation but more will be added as needed.
This is my first attempt at tagless final style. @tpolecat could you check if it is ok?
The GPI Example has been tested against GPI to verify it is working
> SEQNG-252: GIAPI status getter library

- build.sbt
- modules/edu.gemini.giapi.client/src/main/scala/edu/gemini/giapi/client/commands.scala
- modules/edu.gemini.giapi.client/src/main/scala/edu/gemini/giapi/client/gpi/GPIClient.scala
- modules/edu.gemini.giapi.client/src/main/scala/edu/gemini/giapi/client/package.scala
- project/Settings.scala
This is the next step on GIAPI support with the ability to send commands.
> SEQNG-250: Support sending commands through GIAPI

- .travis.yml
- project/Settings.scala
Update scala version and added a flag to improve compilation performance
> Update scala version and increase paralellism flags

- build.sbt
- modules/edu.gemini.giapi.client/src/main/scala/edu/gemini/giapi/client/gpi/GPIClient.scala
- modules/edu.gemini.giapi.client/src/main/scala/edu/gemini/giapi/client/package.scala
- project/Common.scala
- project/Settings.scala
This is an extension to the library to read status items. This allows us to stream items as they are produced.
> SEQNG-252: Add operation to stream GIAPI status items

- modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala
This PR fixes two unit tests for seqexec.engine.
> SEQNG-602 Fixed unit tests broken by port to FS2.

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepConfigTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/model.scala
While working on GPI I noted the step settings back button wasn't working and there were some small missalignments
This PR fixes that. Here's the button that's now properly working
> SEQNG-623: Step config table back button not working

- build.sbt
- modules/seqexec/web/client/src/webpack/dev.webpack.config.js
- modules/seqexec/web/client/src/webpack/prod.webpack.config.js
On the last build updates for the UI side we lost the favicons on the seqexec. This PR restores it by` `favicons-webpack-plugin` which automatically generates all the icons' resolutions from a base image
This also updates other npm packages to their latest versions
> SEQNG-622: Auto generate favicons with webpack

- app/seqexec-server-gs/src/main/resources/app.conf
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/web/server/src/main/resources/app.conf
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
This a small update adding a configuration parameter to connect to GPI. I also fixed the launcher which was unnecessarily calling `unsafeRunSync`
> SENQG-624: Add configuration to connect to GPI

- modules/giapi/src/main/scala/giapi/client/commands.scala
- modules/giapi/src/main/scala/giapi/client/gpi/GPIClient.scala
- modules/giapi/src/main/scala/giapi/client/package.scala
- modules/giapi/src/test/scala/giapi/client/CommandsSpec.scala
- modules/giapi/src/test/scala/giapi/client/GiapiArbitraries.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPI.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPIController.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala
- modules/seqexec/server/src/test/scala/seqexec/server/gpi/GpiSpec.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
This PR add supports for setting GPI non standard modes. 
I took the opportunity to improve the giapi API hiding some of the javaness behind a nicer scala API
Here is a video of a sequence executed on GPI and changing the filter as we go
https://monosnap.com/file/WcCtPZ8e8cawtQhllGpai8qm6r3CIg#
> SEQNG-617: Support custom observing modes

- modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java
This PR fix the problem with the cascade of "unresponsive channel" messages coming from CAJ. It seems that is not a good idea to call CAJ functions inside a channel monitor callback.
> SEQNG-590 Removed EPICS reads from EPICS monitor callback.

- modules/seqexec/web/client/src/main/resources/less/style.less
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- project/Settings.scala
Fix for logs not being sent to the client. It also does some improvements to the logs table ui
> SEQNG-644:  Webclient does not show logs

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LoginBox.scala
if on the login box you login, the logout and try to login again, the credentials from the original login remain. This is a security risk so this this PR will clear the credentials instead
> SEQNG-647: Credentials are not cleared on login

- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecConfiguration.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/StandardHeader.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
I missed removing a couple of usages of the old `Site` class
> SEQNG-648: Remove legacy Site class usage

- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPI.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPIHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/GDSClient.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/Header.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/ObsKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/StandardHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsKeywordReader.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala
This PR does the bulk of the work to get keywords onto GPI images. It has been tested against the instrument and it gets the keywords written except for the following exceptions:
* CRFOLLOW which seems to be not in use. we'll follow up with science
* Keywords from gcal/gws. They need to be modified to work with either the DHS or GDS
> SEQNG-613: GPI Keywords

- modules/seqexec/server/src/main/resources/Tcs.xml
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPIHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsKeywordReader.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala
- modules/seqexec/server/src/test/scala/seqexec/server/tcs/TcsSpec.scala
This adds support for the CRFOLLOW keyword in Gpi and also fixes reading the corresponding epics channels from the TCS
> SEQNG-654: Support CRFOLLOW

- modules/seqexec/web/client/src/main/resources/less/style.less
- modules/seqexec/web/client/src/webpack/dev.webpack.config.js
Tiny css fix that's breaking the the UI with breakpoints for logged out users
> SEQNG-658; Strange display of breakpoints

- modules/seqexec/model/src/main/scala/seqexec/model/Model.scala
- modules/seqexec/model/src/main/scala/seqexec/model/properties.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ConfigUtilOps.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOST.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOSTController.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala
- modules/seqexec/server/src/test/scala/seqexec/server/ghost/GhostSpec.scala
- project/Settings.scala
Read the GHOST model from the ocs
> SEQNG-643: GHOST Model

- README.md
- build/buildkite-build.sh
- modules/sql/src/main/scala/Main.scala
> Fail the build if genEnums produces unchecked code

- modules/seqexec/web/server/TLS.md
> Updated TLS config documentation

- modules/core/shared/src/test/scala/gem/util/LocationSpec.scala
- project/Settings.scala
- project/plugins.sbt
This updates a few things
- cats 1.2.0
- flyway 5.1.4
- decline 0.4.2
- wartremover 2.3.1
> dependency updates

- modules/giapi/src/main/scala/giapi/client/commands.scala
- modules/giapi/src/main/scala/giapi/client/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecFailure.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPIController.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala
The giapi client isn't properly handling command errors. This PR fixes that and also removes some unused code
> SEQNG-633 Proper error treatment of unhandled commands

- modules/seqexec/engine/src/main/scala/seqexec/engine/Sequence.scala
Sequences were not properly updated because I forgot to add new steps.
> SEQNG-702 Fixed sequence update.

- modules/seqexec/web/client/src/main/resources/less/style.less
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepBreakStopCell.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/icon/Icon.scala
Some users have requested the breakpoint button to be made bigger. This PR addresses this and also shows a representation of the breakpoint while hovering. This should be user tested to get a better idea if this is enough
The PR is somewhat larger than the actual changes as I did some small refactorings here and there
> SEQNG-691: Increase size of the step pause button

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/reusability.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/InstrumentsTabs.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/SequenceArea.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceAnonymousToolbar.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala
- project/plugins.sbt
While doing another task I noted a mistake on the way circuit subscribers are created. Those should be created only once but instead they were created on each render. This has some important performance implications
I'm also upgrading to scala.js 0.6.25 which should help an occassional error seen on buildkite
> Performance improvements

- build.sbt
Fixes setting to include prometheus files on the seqexec GN
> Fix for build for GN

- build.sbt
- modules/seqexec/web/client/src/webpack/webpack.parts.js
With the update to uglyfyJS to 2.x i can restor minification of js to get a nice reduction on the final size
> SEQNG-596: Enable minification of js

- modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala
- modules/seqexec/model/src/main/scala/seqexec/model/events.scala
- modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/package.scala
- modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala
This PR adds http endpoints to modify the calibration queue
> SEQNG-562: Cal queue endpoints

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
Implementation, test and http entry point.
> SEQNG-709 Implemented clearQueue function.

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/encoder/BooEncoders.scala
Server side and client side endpoints to add multiple sequences
> Endpoint and client side implementation for add sequences

- modules/giapi/src/main/scala/giapi/client/GiapiClient.scala
- modules/giapi/src/main/scala/giapi/client/ghost/GHOSTClient.scala
- modules/giapi/src/main/scala/giapi/client/gpi/GPIClient.scala
- modules/giapi/src/main/scala/giapi/client/package.scala
Here's my attempt at a `GHOSTClient` implementation following my last PR that refactored out part of `GPIClient` to `GIAPIClient`.
I'm still not entirely sure that the `GHOSTExample` has the right things in it, so if it looks wrong, please let me know :-).
> SEQNG-677: GHOST Client implementation

- modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala
- modules/seqexec/web/client/src/main/resources/dev.js
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/QueueTabContent.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/QueueToolbar.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/reusability.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/CalQueueFocus.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/CalQueueSeq.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala
- modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/CircuitReaderSpec.scala
- modules/shared/web/client/src/main/scala/web/client/table/package.scala
- modules/shared/web/client/src/main/scala/web/client/utils.scala
This does the basic setup for the calibration queue. it can display the contents once added
https://monosnap.com/file/9dFGMsTqK7x7BgUt08M63YY8UGxheU#
The table is setup to support reordering in the near future
There are several small ui details to improve but i want to get the ball rolling
> SEQNG-565: Add calibration queue table

- app/seqexec-server-gn/src/main/resources/app.conf
- app/seqexec-server-gs/src/main/resources/app.conf
- app/seqexec-server/src/main/resources/app.conf
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOSTController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOSTHeader.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
- modules/seqexec/web/server/src/main/resources/app.conf
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
As per @jluhrs' comment, this is actually the work needed for 680 and not 676.
Thus, I have renamed the PR and will close the other once we get it merged.
> SEQNG-680: Configuration for GHOST.

- modules/seqexec/web/client/src/main/resources/less/style.less
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecMain.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala
Chrome 69 did some changes that broke the top bar. This PR fixes that
wrong:
fixed:
> SEQNG-748 Fix title bar on chrome

- modules/acm/src/test/java/edu/gemini/epics/acm/test/CaCommandSenderTest.java
- modules/acm/src/test/java/edu/gemini/epics/acm/test/CaConfigFileConverterTest.java
- modules/acm/src/test/java/edu/gemini/epics/acm/test/CaStatusAcceptorTest.java
- modules/acm/src/test/java/edu/gemini/epics/acm/test/TestSimulator.java
- modules/acm/src/test/java/edu/gemini/epics/acm/test/XMLBuilderTest.java
- modules/seqexec/model/src/main/scala/seqexec/model/enum/BatchCommandState.scala
- modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
Also, set observer for each sequence as they are run.
> SEQNG-745 Select sequences for instruments when running queue.

- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOST.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GHOSTController.scala
This PR:
1. Implements `GHOSTController.observe` in the same way that `GPIController.observe` is implemented; and
2. Fixes a variable naming issue.
> SEQNG-679: Implement observe in GHOSTController.

- modules/seqexec/model/src/main/scala/seqexec/model/enum/QueueManipulationOp.scala
- modules/seqexec/model/src/main/scala/seqexec/model/package.scala
- modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/CalibrationQueues.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/QueueSeqOperations.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/actions.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/CalQueueControlFocus.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/CalQueueFocus.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/SeqexecCircuit.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/OpenConnectionHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueOperationsHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueRequestsHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/handlers/QueueStateHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/icon/Icon.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
- modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
- modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala
- modules/shared/web/client/src/main/scala/web/client/table/package.scala
This PR lets you remove indiviual rows from the queue
It ended up being a lot larger as it handles all/most cases during the transients between clicking the button and the queue being updated
> SEQNG-739: Support removing a single sequence

- app/seqexec-server-gs/src/main/resources/app.conf
- app/seqexec-server/src/main/resources/app.conf
The spacing in the app.conf files was wonky for GHOST for some reason, so this fixes it.
> SEQNG-676: Fixing weird spacing.

- modules/seqexec/server/src/main/scala/seqexec/server/gcal/Gcal.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalControllerSim.scala
Also added logging to GCAL setup.
> SEQNG-755 Added timeout to GCAL setup.

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueToolbar.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/circuit/CalQueueControlFocus.scala
- modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/CircuitReaderSpec.scala
- modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ModelSpec.scala
Fixes to support launching a queue after one has completed
> SEQNG-771: Use execState to define the state of the toolbar

- build.sbt
- project/plugins.sbt
This let's us use the latest tzdb format
> Upgrade sbt-tzdb

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala
- modules/shared/web/client/src/main/scala/web/client/table/ColumnWidth.scala
- modules/shared/web/client/src/main/scala/web/client/table/SortableRow.scala
- modules/shared/web/client/src/main/scala/web/client/table/UserModified.scala
- modules/shared/web/client/src/main/scala/web/client/table/package.scala
this fixes a bug in chrome that sometimes prevents the remove from queue button of clicking
Tested in OSX, FF and Chrome version 69
/cc @jluhrs Could you test it in Linux?
> SEQNG-773: Remove button sometimes doesn't work in chrome

- build.sbt
- project/Settings.scala
- project/plugins.sbt
Instead of generating the tzdb we can use an external package with our custom db. This should shave some seconds out of the build
> Use fixed locales/tzdb package

- modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala
Every processed event can produce new events, in the form of an`Option[Stream]`. The code was queuing a `Stream` even if the result was `None`. I removed that.
There is also some code formatting.
> SEQNG-782 Avoid processing empty streams.

- modules/seqexec/server/src/main/scala/seqexec/server/ProgressUtil.scala
Also, fixed countdown for simulated resumed exposures.
> SEQNG-798 Fixed internal exposure countdown.

- modules/giapi/src/main/scala/giapi/client/GiapiClient.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GPI.scala
Estimation of obs time for GPI, good for the progress bar
https://www.dropbox.com/s/bld44uy99hh8pxr/screencast%202018-11-14%2012-08-47.mp4?dl=0
> SEQNG-812 Refine the estimated observation time

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/SeqexecCircuit.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/WebSocketFocus.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/ControlMenu.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SoundControl.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/SoundOnOffHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecAppRootModel.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecUIModel.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/reusability/package.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/icon/Icon.scala
- modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
This PR removes sounds while executing for logged off users
> SEQNG-689 Don't play sounds for logged off users

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala
This PR change the way the remaining time is displayed on the progress bar. It was in hours, mins, secs but now it is just seconds.
I also changed the text to say "Reading out" after the exp is done (SEQNG-482)
> SEQNG-816: Show remaining time in seconds and show

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LoginBox.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecMain.scala
This PR fixes a tiny UI bug. If you click outside the login box it gets dismissed but you can't reopen it.
Besides that, this code is fairly old so it is updated to the current set best practices
> SEQNG-827 Fix bug on closing the login box and some refactorings

- modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/Sequence.scala
- modules/seqexec/engine/src/test/scala/seqexec/engine/SequenceSpec.scala
- modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SequenceData.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SequenceGen.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerLensesSpec.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SubsystemControlCell.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
Implementation of the Single System Configuration command, that allows the user to apply a step configuration to a system.
The command was connected to the UI.
The feedback in the UI is not yet implemented.
> Back end side of system config command

- modules/seqexec/web/client/src/main/resources/dev.js
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
Adds more logging to the web server. Each request and response is logged. This should be useful for debugging and statistics
I took care not to log confidential data, in particular username/pw
> Add logger to the http server

- modules/seqexec/model/src/main/scala/seqexec/model/operations.scala
There was almost nothing to do, I just added the list of valid operations for NIRI.
> SEQNG-839 Added NIRI to web client

- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/niri/BeamSplitter.java
- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/niri/BuiltInROI.java
- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/niri/Camera.java
- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/niri/DetectorState.java
- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/niri/Disperser.java
- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/niri/Mask.java
- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/niri/ReadMode.java
- modules/seqexec/server/src/main/resources/Niri.xml
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriEpics.scala
Code to set parameters, trigger commands, and read back statuses from NIRI EPICS channels.
> SEQNG-836 NIRI Epics code.

- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/gnirs/DetectorState.java
- modules/seqexec/server/src/main/resources/Gnirs.xml
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsEpics.scala
Check GNIRS connection to DHS and that its detector array is active before trying to start an exposure.
> SEQNG-841 GNIRS checks before observe.

- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GhostController.scala
As per my discussion with @tpolecat, I added the `Eq` operators for the subclasses of `GhostConfig` and `GhostConfig` at large.
(@tpolecat, is this what you had in mind?)
> SEQNG-784: Added GhostConfig Eq operators.

- build.sbt
- modules/seqexec/model/src/main/scala/seqexec/model/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GhostController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiController.scala
- modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala
- project/Settings.scala
Some library updates, mostly on the client side
> Library upgrades

- modules/seqexec/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
Smallish refactoring making ODBProxy parametrized on the effect type `F[_]`
> Parametrize ODBProxy

- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GhostController.scala
Rob made a comment after I merged about how this PR could be cleaned up a little, so here we go!
> SEQNG-784: Small cleanup as per earlier PR comments.

- modules/seqexec/server/src/main/resources/Niri.xml
- modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriEpics.scala
This PR implements special behavior to configure NIRI DC.
> SEQNG-857 Trigger DC apply for NIRI configuration.

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala
This fixes a small bug where the preview was lost when logging in/out
> SEQNG-859 Fixes preview removal upon login

- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Gaos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala
Interface to the Gemini Adaptive Optics System, to be implemented for Altair and GeMS.
It will probably change when implementing the real thing.
> SEQNG-851 GAOS interface.

- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
This PR prints the seqexec version at startup and banner:
> SEQNG-868 Print the version of the seqexec at startup

- modules/seqexec/model/src/main/scala/seqexec/model/operations.scala
- modules/seqexec/server/src/main/scala/seqexec/server/InstrumentControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecFailure.scala
- modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsHeader.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
This implements a minimal NifsConfigurator and integrates it to the `SeqexecEngine`. At this level we can load and simulate sequences
> SEQNG-873: Nifs Instrument

- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Gaos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/GuideConfigDbRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
Seqexec now keeps track of the guide configuration set from TCC. It defines a HTTP API, that TCC uses to inform Seqexec when a new configuration is set.
> SEQNG-881 Keep track of guide configuration set by TCC.

- modules/seqexec/server/src/main/resources/Nifs.xml
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsEpics.scala
Add some missing epics channels for NIFS
> SEQNG-875 Add missing channels and fixes reading from the ccStates

- build.sbt
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SessionQueueTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/shared/web/client/src/main/scala/web/client/table/TableState.scala
- modules/shared/web/client/src/main/scala/web/client/table/package.scala
- modules/shared/web/client/src/main/scala/web/client/utils.scala
- modules/shared/web/client/src/test/scala/web/client/table/TableArbitraries.scala
- project/Settings.scala
upgrades some scala js libs and lets me remove some bits of duplicated code
> Scala.js libs upgrade

- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorthControllerEpics.scala
- project/Settings.scala
this PR upgrades the ocs libs to get a fix for one of the GPI params. it also brings a new gmos north filter
> Upgrade ocs libs

- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
This is the first PR to get NIFS epics working. Up to this point it supports configuring the DC but the CC is pending
This PR is to get some early feedback
Note that I'm trying to simplify the code by using `F[_]` rather than `Either[F, E, _]` but this needs testing
> SEQNG-879A: Nifs epics DC configuration

- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsEpics.scala
This is the code to configure NIFS CC. It is more or less a direct translation of the tcl code though the two pass setup of the CC is now made explicit
This of course requires intensive testing to be verified
> SEQNG-879: Nifs CC setup

- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsHeader.scala
This PR contains a simplified calculation of the WCS for NIFS
> SEQNG-888 Approximate calculation of WCS for NIFS

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala
Small UI fix. It shows the subsytem buttons if the sequence is paused
> SEQNG-845 Show the step subsystem control if we pause the observation

- modules/seqexec/server/src/main/resources/Tcs.xml
- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/Gems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Gaos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/ScienceFoldPositionCodex.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/package.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala
- modules/seqexec/server/src/test/scala/seqexec/server/tcs/TcsControllerSpec.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
Implementing Altair made me revisit the TCS code, that I wrote almost 3 years ago. I found bugs, things that are now done differently, and a bit of a mess in regard of how the configuration is handled. I tried to improve all that.
There are now three types of configuration. One is the guide configuration coming from the TCC. The other is the configuration coming from the sequence. The last one is internal to `TcsControllerEpics`, and is built from the values read from the EPICS system. All of them are combined to finally decide how to setup the TCS.
> SEQNG-892 Refactored TCS code

- modules/acm/src/main/java/edu/gemini/epics/acm/CaApplySenderImpl.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaCarRecord.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaStatusAcceptorImpl.java
- modules/acm/src/test/java/edu/gemini/epics/acm/test/TestSimulator.java
NIFS doesn't follow the action model as it should be thus we need to change the whole Action Mode code. This PR fixes that and it has been tested on NIFS and also checked for regressions with the other instruments
> Seqng 894: Fix ACM to support NIFS

- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/nifs/ReadMode.java
- modules/seqexec/server/src/main/java/edu/gemini/seqexec/server/nifs/TimeMode.java
- modules/seqexec/server/src/main/resources/Nifs.xml
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsEpics.scala
This is a draft PR to track the changes to NIFS code while testing
> NIFS fixes while testing

- modules/core/shared/src/main/scala/gem/config/DynamicConfig.scala
- modules/core/shared/src/test/scala/gem/config/GmosConfigSpec.scala
I needed a few more lenses in order to simplify sequence generation over in [basic-case](https://github.com/gemini-hlsw/basic-case/pull/9).
> Adds lenses that were needed for GMOS longslit sequence generation

- modules/seqexec/server/src/main/resources/Altair.xml
- modules/seqexec/server/src/main/resources/Tcs.xml
- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/Gems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Gaos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/ScienceFoldPositionCodex.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
The full Altair implementation. There are some details missing, like a special behavior for OIWFS.
Some Altair commands are not ACM compliant, and will require a different monitoring procedure. For now, they are commented out .
> Altair control

- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala
- modules/seqexec/server/src/test/scala/seqexec/server/tcs/GuideConfigDbSpec.scala
> SEQNG-917 Fixed bug in parsing coma option from Json

- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerSim.scala
> SEQNG-923 Updated progress bar time estimates for NIFS

- modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala
Fixes the properties to display on GNIRS, giving a correct FPU and Filter, and adding Decker
> SEQNG-915: Fix GNIRS FPU and Filter and Decker

- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsEpics.scala
The type of central wavelength should be double rather than string
> SEQNG-929: NPE setting NIFS central wavelength

- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsEpics.scala
This PR fixes an NPE setting the maskOffset and improves smart setting of the disperser and mask
> SEQNG-930: NIFS NPE an maskOffset and smart params

- modules/acm/src/main/java/edu/gemini/epics/acm/CaApplySender.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaAttribute.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaCommandSender.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaCommandSenderImpl.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaCommandTrigger.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaParameter.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaParameterStorage.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaService.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaTaskControl.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaTaskControlImpl.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaTaskControlRecord.java
- modules/acm/src/main/java/edu/gemini/epics/acm/TaskControlState.java
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairEpics.scala
Altair uses a special record to control commands, called taskControl. This PR adds support to handle those records, to be able to change parameters, trigger them , and monitor their execution.
Warning: this is in the EPICS support package ACM, in Java.
> SEQNG-913 Implemented support for Altair special control records

- modules/seqexec/server/src/main/resources/Tcs.xml
- modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
Implemented the follow and park control for probes.
The code became a bit convoluted when handling PWFS2. It is a special case, because PWFS2 cannot be used when using Altair or GeMS. I am not happy with this first implementation, but I am bit pressed of time and need to move to Altair control code, so I'll leave the code improvements for another task (SEQNG-936)
> SEQNG-935 Completed guider probe configuration.

- modules/seqexec/server/src/main/resources/Altair.xml
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
More bug fixes for Altair:
* There was a bug in the logic to determine if the control matrix was OK.
* The channels for the current control matrix star position were swapped.
* The science fold position was using the wrong light source for Altair
> SEQNG-940 For Altair, fixed SF set position, prepare matrix logic.,

- modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/Gems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Gaos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
Implemented two missing features:
* If Altair is the source for M2 and/or M1, pause them when Altair is paused.
* Configure coma and reset M2 guiding when off.
> SEQNG-943: Pause M1/M2 guiding when Altair is paused.

- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
In dark mode the Mask goes always to BLOCKED but we should check if it is already in that position
> SEQNG-932: On dark mode for NIFS check if we need to move the mask

- modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala
- modules/seqexec/model/src/test/scala/seqexec/model/ModelLensesSpec.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala
This PR adds support to show NIFS fields on the steps table
> SEQNG-877 Show the appropriate NIFS fields on the steps table

- modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java
- modules/acm/src/test/scala/edu/gemini/epics/acm/ObserveStateSpec.scala
The apply/observe state machine is not handling the case where observe car gets into an error state
This PR fixes that and adds a couple of test cases
> SEQNG-938 Properly handle the case where observe CAR goes to error

- modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala
After making the seqexec die if the odb reads fail, the server cannot start if the odb is down or restarted. This PR fixes that by checking the particular wdba exception and ignoring it
> SEQNG-949 Don't kill the seqexec if the odb is down

- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala
The feature would work sometimes, and sometimes not. I found the problem was that the value sent by the ODB for parameter `windowCover` was not always of the same type.  I cover for all possible types in the code.
> SEQNG-692 Fixed bug reading sequence parameter windowCover for F2.

- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala
This is the same `windowCover` fix, but applied to `reads` and `readoutMode`.
> SEQNG-965 Fixed reading of engineering parameters for F2.

- modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java
Extra debug info to investigate SEQNG-891
> SEQNG-973 Enabled debug info for CaObserveSenderImpl

- modules/seqexec/web/client/src/main/resources/less/style.less
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/RunFromStep.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/QueueRequestsHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/RemoteRequestsHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/TabOperations.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/reusability/package.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
- modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
This PR adds the support to start a sequence from any step
There is some code related to the state of the action which could be improved. I'll do that in another PR removing boilerplate
> SEQNG-970: UI to trigger start from actions

- modules/seqexec/server/src/main/scala/seqexec/server/ConfigUtilOps.scala
- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/Gsaoi.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/Nifs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/niri/Niri.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
First round of doing GSAOI configuration model
I did a little refactoring of `InstrumentSystem` too. That refactoring should be expanded to all instruments but I'll do that in another PR
> SEQNG-954: Gsaoi configuration model

- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiHeader.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
Minimal code to get GSAOI sequences to load
> SEQNG-958 Support loading GSAOI sequences

- modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala
- modules/seqexec/model/src/test/scala/seqexec/model/ModelLensesSpec.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiController.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerArbitraries.scala
- modules/seqexec/server/src/test/scala/seqexec/server/gsaoi/GsaoiArbitraries.scala
- modules/seqexec/server/src/test/scala/seqexec/server/gsaoi/GsaoiSpec.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala
this PR adds support to properly display GSAOI sequences showing the read mode as shown below
I'm also adding a few tests to Gsaoi classes
> SEQNG-957: GSAOI Client support

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/ObservationProgressBar.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala
This is a fix for a little annoyance. When doing a stop the progress bar keeps advancing. This PR freezes it in place until the stop completes
> SEQNG-898 Freeze progress bar while stopping

- modules/seqexec/model/src/main/scala/seqexec/model/operations.scala
I forgot to enable the stop/abort buttons for GSAOI
> Enable buttons stop/abort for GSAOI

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
It has been commented that the controls to set breakpoints can be hard to use
This PR provides two alternative ways to flip a breakpoint
* Click on any part of the row with ALT pressed
* Click on any part of the row with the middle button
It is difficult to demonstrate but the video below shows the feature
> SEQNG-981: Alternative ways to set breakpoints

- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala
- modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriKeywordReader.scala
As a followup of #916 this PR unifies the style of the Niri and F2 keyword readers
> SEQNG-887 Refactor of Niri and F2 keyword reader

- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/Gcal.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalKeywordReader.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
Another refactoring to do epics calls inside an effect. This time GCAL is updated
> SEQNG-877B: Make GcalEpics referentially transparent

- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- project/Settings.scala
Upgrade of cats-effect. This lets me remove some workarounds to die gracefully in presence of certain errors
> Upgrade cats-effect to 1.3.0

- modules/seqexec/model/src/main/scala/seqexec/model/Notification.scala
- modules/seqexec/model/src/test/scala/seqexec/model/ModelSpec.scala
- modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala
- modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala
- modules/seqexec/model/src/test/scala/seqexec/model/arb/ArbNotification.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/NotificationsHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/RemoteRequestsHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SequencesOnDisplay.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/TabOperations.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
- modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala
- modules/seqexec/web/shared/src/test/scala/seqexec/web/model/boopickle/ModelBooPicklersSpec.scala
At the moment the server will safely ignore requests to configure a subsystem e.g. TCS if busy. However the client does not get informed thus it looks like it is still trying to run it
This PR sends a notification in this case
> SEQNG-822 Indicate if a user tries to configure a resource in use

- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala
We have a report of an error reading epics channels. This PR attempts to fix it but I'd like to have some discussion about the details
> GWS Read errors not handled properly

- build.sbt
- modules/giapi/src/main/scala/giapi/client/ghost/GhostClient.scala
- modules/giapi/src/main/scala/giapi/client/gpi/GpiClient.scala
- modules/giapi/src/main/scala/giapi/client/package.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala
This PR adds a method to invoke align and calib on GPI and also does a bit of refactoring on giapi aligning it to other parts of the code
> SEQNG-992: Refactoring in preparation for gpi A&C and add A&C command

- modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SequenceData.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SequenceGen.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerLensesSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
As port of SEQNG-993 I've been doing some somewhat mechanical refactorings. I'm putting them in a separate PR to make the review process simpler
This refactoring has let me found a couple of difficult places to refactor especially so I guess it is a win
> SEQNG-993A: Some refactorings

- modules/seqexec/model/src/main/scala/seqexec/model/SequenceState.scala
- modules/seqexec/model/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/SequenceDefaultToolbars.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/ModelOps.scala
- modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala
This PR is more of a question to discuss. We have the `SequenceState.Stopped` value but we never really set it on the server
@jluhrs Are we really using it?
> Removed stopped state

- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala
Convert GnirsKeywordReader to the current model plus some refactorings of SeqTranslate out of SEQNG-993
> SEQNG-887: Refactoring of header calculations

- app/seqexec-server-gs/src/main/resources/app.conf
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosHeader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/package.scala
Another PR refactoring the gmos keyword reader.
This refactoring was slightly harder due to the handling of ADC and ROI, thus it was tested against the  gmos epics db
> SEQNG-887 Refactor GmosKeywordReader and cleanup

- modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala
- modules/seqexec/model/src/main/scala/seqexec/model/Step.scala
- modules/seqexec/model/src/main/scala/seqexec/model/enum/StepType.scala
- modules/seqexec/model/src/test/scala/seqexec/model/ModelLensesSpec.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/StepItems.scala
Let's show how a step is A&C on the type column
> SEQNG-996 Show when a step is A&C

- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
Another PR making the Epics reads referentially transparent. This time is GNIRS
> SEQNG-887: Make Gnirs epics reads referentially transparent

- modules/seqexec/engine/src/main/scala/seqexec/engine/Step.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SequenceGen.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerLensesSpec.scala
I started implementing SEQNG-1000 but that will be postponed. As part of that I did a few refactorings I want to preserve. Those are contained on this PR
> Small refactoring

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/CalibrationQueueTab.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/input/InputEV.scala
The use of the State monad for React is no longer recommended. I've already removed a couple of uses but this PR removes the last bits
> Remove use of ReactS

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/Altair.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/Gems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/Tcs.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/tcs/TcsControllerEpicsSpec.scala
This is the first change in the path to integrate GeMS
> SEQNG-1007 Refactored TCS code into tagless style.

- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Epics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsEpics.scala
Another refactoring of the Epics code to wrap calls into `Sync.delay` rather than directly calling side-effecting code
> SEQNG-887 Transform Flamingo2 Epics

- app/seqexec-server/src/main/resources/app.conf
- build.sbt
- project/Settings.scala
- project/plugins.sbt
I took several updates suggested by `scala-steward` and tested them:
*sbt-build-info
*sbt-native-packager
*logstash update
> Suggested package updates

- modules/seqexec/model/src/main/scala/seqexec/model/events.scala
- modules/seqexec/model/src/test/scala/seqexec/model/SeqexecEventSpec.scala
- modules/seqexec/model/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala
- modules/seqexec/server/src/test/scala/seqexec/server/tcs/GuideConfigDbSpec.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/GuideConfigDbRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- modules/seqexec/web/server/src/test/scala/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
- modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala
- modules/seqexec/web/shared/src/test/scala/seqexec/web/model/boopickle/ModelBooPicklersSpec.scala
This PR sends changes to the GuideConfig to the clients to be displayed on a next PR. It was made quite easy using `SignallingRef`
> SEQNG-986B: Send GuideConfig to the clients

- modules/seqexec/server/src/main/scala/seqexec/server/EpicsHealth.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala
This is the first Nod & Shuffle PR. We are now able to read the configuration of N&S sequences
> SEQNG-1015 Read N&S configuration from the sequence

- modules/seqexec/model/src/main/scala/seqexec/model/ModelLenses.scala
- modules/seqexec/model/src/main/scala/seqexec/model/enum/StepType.scala
- modules/seqexec/model/src/main/scala/seqexec/model/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/InstrumentSystem.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SequenceConfiguration.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/StepItems.scala
This PR does some refactoring delegating to instrument the decision of step type out of `SeqTranslate`
We use this to tell when a step is Nod and Shuffle and show it on the UI:
> SEQNG-1018 Assign StepType N&S to the corresponding sequences

- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
We realized that `nsPairs` should be set always for N&S sequences and for non N&S sequences. Thus this is a bug on the current seqexec
This PR fixes it and also adds a special `NSConfig` case class. This is useful as N&S configuration is neither completely CC nor DC
> SEQNG-1019: Set nsPairs for all GMOS sequences

- modules/core/shared/src/main/scala/gem/enum/GiapiStatus.scala
- modules/giapi/src/main/scala/giapi/client/GiapiClient.scala
- modules/giapi/src/main/scala/giapi/client/GiapiStatusDb.scala
- modules/giapi/src/main/scala/giapi/client/gpi/GpiClient.scala
- modules/giapi/src/main/scala/giapi/client/gpi/package.scala
- modules/giapi/src/main/scala/giapi/client/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/Gpi.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiStatusApply.scala
- modules/sql/src/main/resources/db/migration/V072__Gpi_Statuses.sql
- modules/sql/src/main/scala/gem/sql/enum/MiscEnums.scala
This PR contains code with some adjustments to allow running align and calib with Gpi.
The main changes are
* Set a longer timeout for the specific command
* Verify that we are not guiding before sending align and calib
> SEQNG-1025: Gpi Align And Calib

- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GemsSource.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/package.scala
Added several EPICS commands and statuses in TCS to control GeMS.
> SEQNG-1032 Added Gems control channels in TCS Epics code.

- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
Fixed bug where GMOS disperser's wavelength was not set between steps with the same disperser.
> SEQNG-1033 Set GMOS disperser wavelenght even if disperser does not change

- project/Settings.scala
Update of scala version. It should make compilation faster. The ui seems just fine
> Scala and http4s update

- modules/seqexec/engine/src/main/scala/seqexec/engine/Execution.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/Sequence.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/Step.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/package.scala
- modules/seqexec/engine/src/test/scala/seqexec/engine/ExecutionSpec.scala
- modules/seqexec/engine/src/test/scala/seqexec/engine/SequenceSpec.scala
- modules/seqexec/engine/src/test/scala/seqexec/engine/StepSpec.scala
- modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SequenceGen.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerLensesSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala
I continuously get confused with the definition of actions as `List[List[Action[F]]`. I also realized that the inner list shouldn't be empty thus I've changed it to `List[NonEmptyList[Action[F]]]` and renamed the type alias to `ParallelActions`
> SEQNG-331 Refactor of Actions list

- modules/seqexec/engine/src/main/scala/seqexec/engine/Action.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/Execution.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/Result.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/package.scala
- modules/seqexec/model/src/main/scala/seqexec/model/enum/NodAndShuffleStage.scala
- modules/seqexec/model/src/test/scala/seqexec/model/ModelSpec.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ControlStrategy.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala
- modules/seqexec/server/src/main/scala/seqexec/server/Response.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqEvent.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SequenceData.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/partials.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecServerSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala
- modules/seqexec/server/src/test/scala/seqexec/server/gmos/GmosSpec.scala
- modules/seqexec/web/server/src/test/scala/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
While experimenting with N&S I ended up making lots of small changes to help me navigate the code and other changes. Instead of piling them up with the core of the work I'm sending this a separate PR. It is mostly code hygiene:
* Move several classes from being defined in a package to their own files
* Minor code style edits
* Refactor of `OdbProxy/OdbCommands`
* Improve type safety of Nod And Shuffle parameters
* Some cleanups to test code
> SEQNG-331d Refactorings

- modules/seqexec/server/src/main/scala/seqexec/server/ConfigUtilOps.scala
- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/Gems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/ObsKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GemsSource.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideConfigDb.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorth.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouth.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/package.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/tcs/GuideConfigDbSpec.scala
This PR implements the control of GeMS. GeMS loop control is notified when starting an unguided step,  and when starting/completing a telescope offset. ODGW control is incomplete, but with this we can start testing with the real systems.
The code referred to the Canopus WFS in three different ways. I normalized all references to use just CWFS.
> SEQNG-1029 Implemented control of GeMS.

- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Epics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/Gems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gws/GwsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala
Status read method used the old style of producing a `F[Option[A]]`, where a `None` signaled a null value. They were changed to `F[A]`with a null value signaled by an exception that can be managed up the stack.
> SEQNG-1041 Changed style of GeMS and GSAOI Epics statuses.

- modules/seqexec/server/src/main/scala/seqexec/server/ConfigUtilOps.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/Gcal.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalKeywordReader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/package.scala
The implementation of GCAL was simplified and changed to follow the other systems.
> SEQNG-1044 Improved the implementation of GCAL.

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/SeqexecApp.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecUI.scala
Small update on the client side to use `IOApp` rather than a plain object
> Make the client app use IOApp

- build.sbt
- modules/seqexec/server/src/main/scala/seqexec/server/OdbProxy.scala
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/DhsClientHttp.scala
- modules/seqexec/server/src/test/scala/seqexec/server/InstrumentControllerSimSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
- project/Settings.scala
This improves a bit logging related to keyword's creation and a few small improvements
> Small logging improvements

- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/StepType.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala
The implementation was easier than what I expected. A N&S dark is basically a N&S with the list of systems and the headers of a Dark.
> SEQNG-1047 Implemented GMOS N&S darks

- modules/seqexec/web/README.md
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/ControlMenu.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/FooterStatus.scala
Also, update Sqlexec Web README.
> Keep login button visible (and hide guide config) on small screens.

- build.sbt
- project/Settings.scala
- project/build.properties
sbt update, This one was on hold until the ocs libs were upgraded to have a matching squants version
> Update to sbt 1.3 and upgrade ocs libs

- build.sbt
- modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/Event.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/Result.scala
- modules/seqexec/engine/src/test/scala/seqexec/engine/SequenceSpec.scala
- modules/seqexec/engine/src/test/scala/seqexec/engine/StepSpec.scala
- modules/seqexec/engine/src/test/scala/seqexec/engine/packageSpec.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerSim.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
This PR fixes several anomalies detected while testing N&S in terms of error handling. In same cases errors will be detected but the sequences of steps would continue, in other cases errors would be skipped altogether
This PR has been tested simulating errors at each of the N&S substeps
> SEQNG-1061 Improve error handling for N&S

- modules/seqexec/server/src/main/resources/Gmos.xml
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosInstrumentActions.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/NodAndShuffleState.scala
- modules/seqexec/server/src/test/scala/seqexec/server/TestCommon.scala
- modules/seqexec/server/src/test/scala/seqexec/server/gmos/GmosArbitraries.scala
- modules/seqexec/server/src/test/scala/seqexec/server/gmos/GmosSpec.scala
It seems we are missing setting some N&S params when doing the initial gmos config. This PR should fix it but it needs more testing
> SEQNG-1062 Set the nod and shuffle state param

- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
And also simplified a bit the grating configuration code.
> SEQNG-1064 Fixed GMOS grating always being configured.

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerSim.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
Small update to parametrize `AltairControllerSim`
> Parametrize AltairControllerSim

- build.sbt
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/SeqexecCircuit.scala
- project/Settings.scala
> Use pprint for debug console logging in Seqexec-UI, only in development.

- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
We are capturing obs errors here but there is no record in the log. This PR will help on debugging certain reported errors
> Add logging of observation errors

- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala
- modules/seqexec/server/src/test/scala/seqexec/server/gmos/GmosSpec.scala
The BiasTime parameter is not used and could be removed
> Remove unused bias time parameter

- modules/seqexec/model/src/main/scala/seqexec/model/Step.scala
- modules/seqexec/model/src/main/scala/seqexec/model/operations.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/actions.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/OperationsStateHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/RemoteRequestsHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/services/SeqexecWebClient.scala
This is how a paused N&S step is currently looking.
I'm open to suggestions for improvement as to how to place the buttons.
> [SEQNG-1075] Wire N&S UI buttons to actual actions.

- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
PR Take 2, thanks to @jluhrs for the help
Subject to on instrument testing
> SEQNG-1069 N&S exposure time fix

- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
We noted some DHS error not logged properly. This PR fixes that
> SEQNG-1103 Improve logging of errors during observations

- modules/seqexec/model/shared/src/main/scala/seqexec/model/SequenceView.scala
- modules/seqexec/model/shared/src/main/scala/seqexec/model/SequencesQueue.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/circuit/WebSocketFocus.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ServerMessagesHandler.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/SeqexecAppRootModel.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/TabOperations.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/tabs.scala
- modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
> [SEQNG-1089] Show TCS/GCAL on tabs during regular executions

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/package.scala
> Remove some unused code

- build.sbt
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/security/TestAuthenticationService.scala
- modules/shared/web/server/src/main/scala/web/server/common/StaticRoutes.scala
- modules/shared/web/server/src/test/scala/web/server/common/StaticRoutesSpec.scala
Improvements allowed after #1170
> Small refactorings to the web server code

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/ControlMenu.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LogArea.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LoginBox.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SoundControl.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/queue/CalQueueTable.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/RunFromStep.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepProgressControl.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepsControlButtons.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/SubsystemControlCell.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/toolbars/StepConfigToolbar.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/SequenceTab.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/button/Button.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/elements/popup/Popup.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/semanticui/package.scala
- modules/shared/web/client/src/main/scala/web/client/ReactProps.scala
Fixing [SEQNG-1114] and [SEQNG-1115] was fairly trivial, but I took the chance to refactor `Popup` and `Button` like we did with other components before, so that they become simpler to declare at call sites.
The tricky part was that both these components accept children, but a mechanism was established for components that accept children from now on.
> [SEQNG-1114] and [SEQNG-1115] Fix Popup tooltip disappearing.

- modules/seqexec/model/shared/src/main/scala/seqexec/model/Step.scala
- modules/seqexec/model/shared/src/test/scala/seqexec/model/arb/ArbNodAndShuffleStep.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SequenceData.scala
- modules/seqexec/server/src/main/scala/seqexec/server/StepsView.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosStepView.scala
- modules/seqexec/server/src/test/scala/seqexec/server/QueueExecutionSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/SeqexecEngineSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/StepsViewSpec.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/StepItems.scala
- modules/seqexec/web/shared/src/main/scala/seqexec/web/model/boopickle/ModelBooPicklers.scala
The step information send to the client now indicates if there is a stop gracefully or pause gracefully command in progress.
> SEQNG-1104 Send N&S pause and stop command state to web client.

- modules/seqexec/server/src/main/scala/seqexec/server/gpi/GpiStatusApply.scala
- project/Settings.scala
Uses the `difference` function defined on `gsp-math`
> Upgrade gsp-math

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/ObservationsProgressStateHandler.scala
This is an attempt to interpret correctly the data sent from the instrument channels through the progress events.
This is a fix based on our observations with @cquiroz of the instrument logs, which for the time being differ from our simulation.
> [SEQNG-1135] Reading out N&S progress bars misbehave.

- modules/acm/src/main/java/edu/gemini/epics/acm/CaWindowStabilizer.java
- modules/seqexec/model/shared/src/main/scala/seqexec/model/package.scala
- modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSettleTimeCalculator.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala
The TCS in-position signal takes some time to be stable. This PR makes the time to wait for it to stabilize depend on the subsystems used and the magnitude of the displacement.
The parameters for the calculations are placeholders until they are measured. I don't intend to merge the PR until then.
> SEQNG-1067 Tcs in-position stabilization time now depends on magnitude of movement.

- modules/seqexec/web/client/src/main/resources/dev.js
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/LoginBox.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/SeqexecMain.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/OffsetDisplayCell.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/sequence/steps/StepSettings.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/CalibrationQueueTab.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/SeqexecTabs.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/SequenceTab.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/tabs/TabsArea.scala
@cquiroz I wonder if we should add all the confirmed FALSE POSITIVES from http://jira.gemini.edu:8080/browse/SEQNG-1145 into `dev.js`.
BTW: I took the change to convert a few more components to the `ReactProps` mechanism
> [SEQNG-1145] Investigate unnecesary React rerenders

- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
Added the channel name to the error message when failing to write an EPICS parameter.
> SEQNG-1151 Added channel name to failed parameter message.

- modules/seqexec/server/src/main/resources/Tcs.xml
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
This is a fix done in the Tcl Seqexec that I replicated in the new Seqexec.
> SEQNG-1158 updated channels for TCS nod-chop guide configuration.

- build.sbt
- modules/seqexec/model/shared/src/test/scala/seqexec/model/ModelSpec.scala
- modules/seqexec/model/shared/src/test/scala/seqexec/model/SeqexecModelArbitraries.scala
- modules/seqexec/model/shared/src/test/scala/seqexec/model/SequenceEventsArbitraries.scala
- modules/seqexec/model/shared/src/test/scala/seqexec/model/arb/ArbClientId.scala
- modules/seqexec/model/shared/src/test/scala/seqexec/model/arb/package.scala
- modules/seqexec/web/client/src/test/scala/seqexec/web/client/model/ArbitrariesWebClient.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- modules/seqexec/web/server/src/test/scala/seqexec/web/server/http4s/SeqexecCommandRoutesSpec.scala
- modules/seqexec/web/server/src/test/scala/seqexec/web/server/http4s/SeqexecUIApiRoutesSpec.scala
- modules/seqexec/web/shared/src/test/scala/seqexec/web/model/boopickle/ModelBooPicklersSpec.scala
- project/Settings.scala
- project/plugins.sbt
I updated http4s and took the opportunity to add tests for most of the http endpoints
> Upgrade http4s and add tests

- modules/seqexec/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/altair/AltairEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Epics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gcal/GcalEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gnirs/GnirsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gsaoi/GsaoiEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/nifs/NifsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/GuideControl.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala
- modules/seqexec/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
- modules/seqexec/server/src/test/scala/seqexec/server/TestEpicsCommand.scala
- modules/seqexec/server/src/test/scala/seqexec/server/tcs/TcsControllerEpicsCommonSpec.scala
- modules/seqexec/server/src/test/scala/seqexec/server/tcs/TestTcsEpics.scala
The fix was easy, but I made the discovery process a bit too complicated. On the bright side, we now have in place a system to track every interaction with TCS in simulation mode, which helps to find bugs without requiring telescope access.
> SEQNG-1153 Found and fixed P2 guide bug

- build.sbt
- project/Settings.scala
> Build cleanup

- modules/seqexec/server/src/main/scala/seqexec/server/keywords/DhsClientHttp.scala
Retrying the final image keywords command causes an error in the DHS.
> SEQNG-1171 Don't retry DHS image close command.

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
The current heartbeat stream is very noisy and pollutes the log providing little useful info in return
This version instead will detect when there are 5 periods without a heartbeat and then produce an event that could be shown to the user
I'm a bit ambivalent if this should kill the seqexec. At the moment it doesn't instead it can keep working
> Improved heartbeat stream

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
We can use an `InspectableQueue` to check the queue size. This is essentially debugging aid for SEQNG-1162. I'm also adding extra debugging when we call the odb and on every incoming event
> Use InspectableQueue to check the queue size

- modules/seqexec/engine/src/main/scala/seqexec/engine/Engine.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/Event.scala
- modules/seqexec/engine/src/main/scala/seqexec/engine/UserEvent.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
It was requested that we should hearbeat messages in the client.
I don't like this feature at all but it is implemented here
It pollutes the client log and makes it note very useful
We should first fix the freezing bug or leave the messages server only
> SEQNG-1167: Hearbeart log message is not shown in client

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
While testing the other day we encountered an error that would take down the seqexec. It happened when we disconnected the odb after an obs started
This is a rare case but still it shouldn't kill the seqexec. Here's a fix
> SEQNG-1174 Capture odb notification errors

- modules/ocs2_api/src/main/scala/gem/ocs2/Parsers.scala
- project/Common.scala
> Update to scala 2.12.10

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
This adds a lot more debugging to the queue events. This maybe useful to track the pausing issues found on the seqexec
> Additional debugging

- .github/workflows/scala.yml
- build.sbt
- project/Settings.scala
> Restore junit library and include acm and giapi tests on CI

- modules/acm/src/main/java/edu/gemini/epics/acm/CaObserveSenderImpl.java
- modules/acm/src/test/scala/edu/gemini/epics/acm/ObserveStateSpec.scala
This should fix the NPE problem.
> SEQNG-1183 Guard against null CLID value in CaObserveSenderImpl.

- .github/workflows/scala.yml
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/StandardHeader.scala
> SEQNG-1178 Always write CRPA even for calibrations

- project/Settings.scala
Update fs2 to the latest version
> Updated fs2

- .gitignore
- build.sbt
- project/Common.scala
- project/Settings.scala
- project/plugins.sbt
This updates the ocs libraries to start working on GHOST and cleans up some orphaned libraries
> Update libraries and ocs

- modules/seqexec/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala
> Fix log message

- modules/seqexec/server/src/main/scala/seqexec/server/Systems.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- project/Settings.scala
Updates ocs3 to use the latest http4s release as well as updating cats-effect
> Upgrade http4s and cats-effect

- modules/seqexec/web/client/src/main/scala/seqexec/web/client/handlers/WebSocketHandler.scala
> Update obsolete comment

- modules/seqexec/server/src/main/resources/Gems.xml
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsControllerEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsEpics.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gems/GemsKeywordReader.scala
Changed type of EPICS channel myst.cn2 to Float, and removed the commands for Canopus APDs (which do not exist anymore).
> Two fixes for GeMS

- .github/workflows/scala.yml
- build.sbt
- project/Common.scala
- project/Settings.scala
Trying to update circe lead to a chase for conflicting versions of discipline, etc
This PR should update all the libraries needed to make it work
> Several libraries

- modules/seqexec/server/src/main/scala/seqexec/server/ghost/Ghost.scala
- modules/seqexec/server/src/main/scala/seqexec/server/ghost/GhostController.scala
- modules/seqexec/server/src/test/scala/seqexec/server/ghost/GhostArbitraries.scala
- project/Settings.scala
This PR brings the latest ocs model for GHOST and reads the `FiberAgitator` parameter
> SEQNG-1191 Update ocs ghost model

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
To identify the reason of the long pauses in the seqexec we added a lot of logging
This PR reduces that substantially now that the pause issue was solved
> SEQNG-1192 Reduce logging

- modules/seqexec/web/server/src/main/scala/seqexec/web/server/config/package.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- modules/seqexec/web/server/src/test/scala/seqexec/web/server/config/ConfigurationLoaderSpec.scala
- project/Settings.scala
It includes some code changes required on the latest version
> Upgrade pure config

- .github/workflows/scala.yml
- build.sbt
- modules/seqexec/server/src/main/scala/seqexec/server/keywords/ObsKeywordReader.scala
- modules/seqexec/web/server/src/test/scala/seqexec/web/server/config/ConfigurationLoaderSpec.scala
- project/Settings.scala
- project/plugins.sbt
This PR lets us run the seqexec on newer jdks. It requires some minor code updates and the explicit addition of jaxb as a dependency
I tested running with jdk8
> Support newer jdks

- build.sbt
- modules/seqexec/model/shared/src/main/scala/seqexec/model/Observer.scala
- modules/seqexec/model/shared/src/main/scala/seqexec/model/Operator.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/HeadersSideBar.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- project/Settings.scala
- project/plugins.sbt
Updates libraries and adds some simplifications to the build
> Update http4s and gpp-ui

- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/GuideConfigDbRoutes.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- project/plugins.sbt
Some minor changes needed for sbt-gsp
> Upgrade to sbt-gsp

- modules/seqexec/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
This route will be hooked to a cronjob to reset the conditions daily
> SEQNG-512 Add route to reset the conditíons

- modules/seqexec/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
Looking at the logs there is an overabundance of the list of messages sent to each client. This is al leftover of previous attempts to improve logging
> Remove per client/message debug

- .github/workflows/packtracker.yml
- build.sbt
Tiny lib update. It is mostly about trying to get packtracker back running
> jsdom update

- modules/seqexec/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala
We put a log entry when an unsupported instrument shows on the queue.
This log is repeated every one minute polluting the logs
This feature had more sense when we had partial instrument support, but now it just adds noise.
> SEQNG-1219 Skip logging when an unsupported instrument's sequence is loaded

- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosController.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
I'm trying to track a case where exposure time wasn't properly set
This adds a bit of debugging
> Adds a bit of debugging

- modules/seqexec/model/shared/src/main/scala/seqexec/model/enumerations.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/Gmos.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosNorth.scala
- modules/seqexec/server/src/main/scala/seqexec/server/gmos/GmosSouth.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/components/Footer.scala
- modules/seqexec/web/client/src/main/scala/seqexec/web/client/model/StepItems.scala
This is a fix to show the custom mask properly on the steps table for GMOS:
> Fix showing custom masks

- modules/acm/src/main/java/edu/gemini/epics/acm/CaApplySenderImpl.java
I removed the restriction that the apply.VAL cannot change while executing an EPICS command.
> SEQNG-1223 Accept that other commands are executed in TCS while configuring it.

- modules/seqexec/web/server/src/main/resources/app.conf
> Increase session life to 3h

- build.sbt
- project/Settings.scala
- project/plugins.sbt
Update the dependencies to work with scala.js 1.3.0
> Upgrade libraries

- modules/web/client/src/main/scala/seqexec/web/client/components/HeadersSideBar.scala
- project/Settings.scala
> Update lucuma ui

- modules/web/client/src/main/resources/less/style.less
- modules/web/client/src/main/scala/seqexec/web/client/components/ControlMenu.scala
- modules/web/client/src/main/scala/seqexec/web/client/components/HeadersSideBar.scala
- modules/web/client/src/main/scala/seqexec/web/client/components/LoginBox.scala
- modules/web/client/src/main/scala/seqexec/web/client/components/SeqexecStyles.scala
- modules/web/client/src/main/scala/seqexec/web/client/components/tabs/SequenceTabContent.scala
- modules/web/client/src/main/scala/seqexec/web/client/icons.scala
Adds a link to the help page to open in a separate tab:
> Add help button

- modules/server/src/main/scala/seqexec/server/OdbProxy.scala
- modules/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerSim.scala
- modules/server/src/main/scala/seqexec/server/gcal/Gcal.scala
- modules/server/src/main/scala/seqexec/server/gcal/GcalControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/gcal/GcalControllerSim.scala
- modules/server/src/main/scala/seqexec/server/gems/GemsControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/gmos/GmosControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/nifs/NifsControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/niri/NiriControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsControllerSim.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala
I put a "Starting" and "Completed" log message around every interaction with external systems. That way if something breaks while trying to command an external system, we will know exactly where it broke.
> SEQNG-1243 Expanded and standardized log messages for interaction with external systems.

- modules/acm/src/main/java/edu/gemini/epics/acm/CaCommandError.java
- modules/acm/src/main/java/edu/gemini/epics/acm/CaContinuousApplySenderImpl.java
- modules/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/server/src/main/scala/seqexec/server/altair/AltairEpics.scala
- modules/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Epics.scala
- modules/server/src/main/scala/seqexec/server/gcal/GcalEpics.scala
- modules/server/src/main/scala/seqexec/server/gems/GemsEpics.scala
- modules/server/src/main/scala/seqexec/server/gmos/GmosEpics.scala
- modules/server/src/main/scala/seqexec/server/gnirs/GnirsEpics.scala
- modules/server/src/main/scala/seqexec/server/gsaoi/GsaoiEpics.scala
- modules/server/src/main/scala/seqexec/server/nifs/NifsEpics.scala
- modules/server/src/main/scala/seqexec/server/niri/NiriEpics.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsEpics.scala
Added the system name to EPICS errors to make clear that the error was coming from an external system and not from Seqexec.
> SEQNG-1234 Added the system name to errors from EPICS commands.

- modules/engine/src/main/scala/seqexec/engine/Engine.scala
- modules/engine/src/main/scala/seqexec/engine/Handle.scala
- modules/giapi/src/main/scala/giapi/client/GiapiStatusDb.scala
- modules/giapi/src/main/scala/giapi/client/ghost/GhostClient.scala
- modules/giapi/src/main/scala/giapi/client/gpi/GpiClient.scala
- modules/model/shared/src/test/scala/seqexec/model/boopickle/ModelBooPicklersSpec.scala
- modules/server/src/main/scala/seqexec/server/ConfigUtilOps.scala
- modules/server/src/main/scala/seqexec/server/InstrumentActions.scala
- modules/server/src/main/scala/seqexec/server/InstrumentControllerSim.scala
- modules/server/src/main/scala/seqexec/server/ODBSequencesLoader.scala
- modules/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerSim.scala
- modules/server/src/main/scala/seqexec/server/gems/GemsControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/gmos/GmosKeywordReader.scala
- modules/server/src/main/scala/seqexec/server/gpi/Gpi.scala
- modules/server/src/main/scala/seqexec/server/gws/GwsHeader.scala
- modules/server/src/main/scala/seqexec/server/nifs/NifsHeader.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsConfigRetriever.scala
- modules/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- modules/web/server/src/main/scala/seqexec/web/server/security/HttpAuthenticator.scala
- modules/web/server/src/main/scala/seqexec/web/server/security/authentication.scala
- project/Settings.scala
> Many library updates

- app/seqexec-server-gn/src/main/resources/app.conf
- app/seqexec-server-gs/src/main/resources/app.conf
- modules/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/web/client/src/main/scala/seqexec/web/client/components/HeadersSideBar.scala
Unknown conditions values were not displayed properly. This PR fixes that and updates the smart gcal configuration
> Fixes unknown values on conditions and smartgcal config

- modules/server/src/main/scala/seqexec/server/altair/AltairEpics.scala
Code was looking for the two Altair attributes in the wrong status acceptor.
> SEQNG-1251 Fixed status acceptor used for Altair Slow Focus status.

- build.sbt
- modules/giapi/src/main/scala/giapi/client/ghost/GhostClient.scala
- modules/giapi/src/main/scala/giapi/client/gpi/GpiClient.scala
- modules/server/src/main/scala/seqexec/server/Systems.scala
- modules/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- modules/web/server/src/main/scala/seqexec/web/server/security/FreeLDAPAuthenticationService.scala
- project/Settings.scala
- project/plugins.sbt
> Update cats-effect and log4cats

- modules/server/src/main/scala/seqexec/server/tcs/TcsSettleTimeCalculator.scala
As requested after the last GS tests.
> SEQNG-1261 Increased minimum waiting time for OI stabilization.

- modules/server/src/main/scala/seqexec/server/gmos/GmosSouthControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala
- modules/server/src/main/scala/seqexec/server/gnirs/GnirsController.scala
- modules/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
- project/Settings.scala
...and REL-3929 New GMOS-S filter.
This is a task of the June 2021 release. It depends on the June 2021 OCS libraries.
> REL-3915 Added new GNIRS IFUs

- modules/server/src/main/scala/seqexec/server/gnirs/Gnirs.scala
- modules/server/src/main/scala/seqexec/server/gnirs/GnirsController.scala
- modules/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
- project/Settings.scala
The spModel GNIRS Decker has now the values for LF_IFU and HR_IFU. This makes the previous code unnecessary.
> REL-3915 Handle new GNIRS decker values.

- modules/server/src/main/scala/seqexec/server/tcs/TcsController.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsControllerEpicsCommon.scala
- modules/server/src/test/scala/seqexec/server/tcs/TcsArbitraries.scala
- modules/server/src/test/scala/seqexec/server/tcs/TcsControllerEpicsCommonSpec.scala
- modules/server/src/test/scala/seqexec/server/tcs/TestTcsEpics.scala
Fixed comparison of current and demanded offset to decide if it needs to be applied. Also, added a tolerance when comparing wavelength, and added unit tests for setting offset and wavelength.
> SEQNG-1268 Fixed comparison of current and demanded offset.

- modules/server/src/main/scala/seqexec/server/flamingos2/Flamingos2Header.scala
- modules/server/src/main/scala/seqexec/server/gsaoi/GsaoiHeader.scala
- modules/server/src/main/scala/seqexec/server/gsaoi/GsaoiKeywordReader.scala
The problem is that local time was used instead of UT.
> SEQNG-1273 Fixed keyword DATE-OBS for GSAOI and F2.

- modules/server/src/main/scala/seqexec/server/gems/Gems.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsSouth.scala
GSAOI dome flats are special, because they are calibration observations taken on OBJECT targets (the dome position for the flat screen). Seqexec was complaining because OBJECT steps with a GeMS component should be run with a GeMS configuration coming from TCC, which is not the case for dome flats (GeMS is ignored in TCC).
This PT makes Seqexec ignore the problem if the step does not have any GeMS guider active.
> SEQNG-1274 Run GSAOI dome flats even if GeMS was not configured.

- modules/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/altair/AltairEpics.scala
- modules/server/src/test/scala/seqexec/server/TestEpicsCommand.scala
- modules/server/src/test/scala/seqexec/server/altair/AltairControllerEpicsSpec.scala
- modules/server/src/test/scala/seqexec/server/altair/TestAltairEpics.scala
- modules/server/src/test/scala/seqexec/server/tcs/TcsControllerEpicsCommonSpec.scala
- modules/server/src/test/scala/seqexec/server/tcs/TestTcsEpics.scala
Added unit tests for Altair EPICS control. They helped me find some bugs. Additionally, I added some additional debug information to the log.
> Debugged Altair problems

- modules/web/server/src/main/scala/seqexec/web/server/security/LdapConnectionOps.scala
- modules/web/server/src/main/scala/seqexec/web/server/security/authentication.scala
To get the display name of new users we needed to change the LDAP query used.
Also a bit more logging was added
> Fix querying display name for noirlab users

- .gitignore
- modules/server/src/main/scala/seqexec/server/gems/GemsControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/gems/GemsEpics.scala
- modules/server/src/test/scala/seqexec/server/altair/AltairControllerEpicsSpec.scala
- modules/server/src/test/scala/seqexec/server/altair/TestAltairEpics.scala
- modules/server/src/test/scala/seqexec/server/gems/GemsControllerEpicsSpec.scala
- modules/server/src/test/scala/seqexec/server/gems/TestGemsEpics.scala
- modules/server/src/test/scala/seqexec/server/tcs/TestTcsEpics.scala
There are two changes, The first is to the GeMS NGS status, that changed with NGS2. The second is that I added unit tests to the logic that pauses and resumes guiding in GeMS.
> Fixed GeMS NGS status, added tests.

- modules/server/src/main/scala/seqexec/server/altair/AltairController.scala
- modules/server/src/main/scala/seqexec/server/altair/AltairControllerDisabled.scala
- modules/server/src/main/scala/seqexec/server/altair/AltairControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/altair/AltairControllerSim.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsNorthControllerEpicsAo.scala
- modules/server/src/test/scala/seqexec/server/altair/AltairControllerEpicsSpec.scala
Changed the logic to control the target filter to make it as in the Tcl Seqexec
> FR-72718 Inverted logic for target filter, assume it is always on.

- modules/server/src/main/scala/seqexec/server/flamingos2/Flamingos2ControllerEpics.scala
F2 window mechanism was fixed, so I reverted the workaround I put in place.
> Reverted workaround for F2 window problem.

- modules/web/server/src/main/resources/logback.xml
Increased log history to up to a year.
> FR-72993: Increased log history limit.

- project/Settings.scala
This should fix the eviction errors.
> Use http4s-scala-xml-1

- modules/server/src/main/resources/Gsaoi.xml
- modules/server/src/main/scala/seqexec/server/gsaoi/GsaoiControllerEpics.scala
- modules/server/src/main/scala/seqexec/server/gsaoi/GsaoiEpics.scala
- modules/server/src/main/scala/seqexec/server/gsaoi/ReadMethod.scala
The GSAOI read method must be written as an integer, not a String. (I was confused because the status gives a String)
> FR-42504 Fixed configuring GSAOI read method parameter.

- project/Settings.scala
Reverts gemini-hlsw/seqexec#2303
> Revert "Update jul-to-slf4j, slf4j-nop to 2.0.4"

- modules/server/src/main/scala/seqexec/server/tcs/TcsSouthControllerEpicsAo.scala
- modules/server/src/test/scala/seqexec/server/tcs/TcsSouthControllerEpicsAoSpec.scala
- modules/server/src/test/scala/seqexec/server/tcs/TestTcsEpics.scala
I found and fixed two major bugs when running GeMS sequences:
- Seqexec was disabling guide on every step without an offset.
- The logic to find if GeMS was active was wrong.
> FR-42534: Fixed some bugs in the guide control for GeMS.

- modules/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/server/src/main/scala/seqexec/server/SeqexecEngine.scala
- modules/server/src/main/scala/seqexec/server/ghost/Ghost.scala
- modules/server/src/test/scala/seqexec/server/SeqTranslateSpec.scala
Ghost needs to know the selected conditions to specify exposure times for the guide camera and the slit viewer.
This PR adds an extra `Ref` to hold the current configurations and it lets `Ghost` read it at the time of configuration.
I'm not totally happy having conditions both in the core model and on the parallel Ref as they need to be on sync but this works as it is. Alternatives are welcome
> Pass the conditions to Ghost

- modules/server/src/main/scala/seqexec/server/EpicsUtil.scala
- modules/web/server/src/main/scala/scala/web/server/common/StaticRoutes.scala
- modules/web/server/src/main/scala/seqexec/web/server/http4s/GuideConfigDbRoutes.scala
- modules/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecCommandRoutes.scala
- modules/web/server/src/main/scala/seqexec/web/server/http4s/SeqexecUIApiRoutes.scala
- modules/web/server/src/main/scala/seqexec/web/server/http4s/WebServerLauncher.scala
- project/Settings.scala
Backports changes from https://github.com/gemini-hlsw/observe/pull/644.
> CE 3.5 updates

- app/seqexec-server-gn-test/src/main/resources/app.conf
- app/seqexec-server-gn/src/main/resources/app.conf
- app/seqexec-server-gs-test/src/main/resources/app.conf
- app/seqexec-server-gs/src/main/resources/app.conf
- build.sbt
- modules/authtester/src/main/scala/seqexec/auth/tester/LDAPTester.scala
- modules/web/server/src/main/scala/seqexec/web/server/security/FreeLDAPAuthenticationService.scala
- project/Settings.scala
This fix will let the seqexec use a different LDAP server
There is also a new utility that can be used to test logins in the command line
> Fix to for authentication

- modules/server/src/main/scala/seqexec/server/SeqTranslate.scala
- modules/server/src/main/scala/seqexec/server/ghost/Ghost.scala
- modules/server/src/main/scala/seqexec/server/ghost/GhostConfig.scala
- modules/server/src/test/scala/seqexec/server/ghost/GhostSpec.scala
- project/Settings.scala
> REL-4441 Initial rough support for non-sidereal  targets

- GN-Utils/Dockerfile.base
- GN-Utils/Dockerfile.dev
- GN-Utils/GN-README.md
- modules/server/src/main/scala/seqexec/server/gnirs/GnirsControllerEpics.scala
Adding a new readme and docker files to enable building the seqexec at Gemini North. This also includes a small modification to complete REL-4415 pertaining to GNIRS.
> Added GN readme, docker files, and REL-4415 mod

- app/seqexec-server-gn/src/main/resources/app.conf
- modules/model/shared/src/main/scala/seqexec/model/dhs/package.scala
- modules/model/shared/src/main/scala/seqexec/model/enum/KeywordName.scala
- modules/server/src/main/scala/seqexec/server/ghost/GhostHeader.scala
- modules/server/src/main/scala/seqexec/server/igrins2/Igrins2Header.scala
- modules/server/src/main/scala/seqexec/server/tcs/TcsKeywordReader.scala
- modules/web/server/src/main/resources/app.conf
Plus a few minor touches related to Igrins 2
> REL-4453 Add ORIGNAME keyword for GHOST and IGRINS2

- modules/server/src/main/scala/seqexec/server/ghost/GhostConfig.scala
- project/Settings.scala
The ocs was not sending target coordinates, this is solved with the upgraded libs on this PR
> Update ocs libs

- modules/server/src/main/scala/seqexec/server/gmos/GmosSouthControllerEpics.scala
This brings Seqexec up to date with the last change in the instrument.
> Changed the wheel for GMOS filter Y
